### ISSUE TITLE
Add game genre RTT

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#101]
https://en.wikipedia.org/wiki/Real-time_tactics

**Comment by Tesba** [comment]
add 4x too, https://en.wikipedia.org/wiki/4X

**Comment by Tesba** [comment]
2 more genres got suggested on Steam Forum i put them here:
- Grand Strategy
- TCG (Trading Card Game)

**Comment by xsellier** [comment]
Added to the next version
