### ISSUE TITLE
Clearer indicator for des/dev/pol in reviews

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#106]
an indicator in the magazine would help, which shows if the slider was set too highor too low. this would give a better hint on what to do better at the next game of that genre.

e.g.:
red arrows:
up = too much effort in development phase
down = need mor effort in development phase

the cloud is a visual trigger, so people get attentive and get triggerd to hover over it with the cursor, it could display following text (cloud pops up bigger with text):
"too much effort in development phase" or "down = need more effort in development phase"

![review](https://user-images.githubusercontent.com/48098478/53768418-0a1cdd80-3ed9-11e9-8ca6-5270d0a88d4d.jpg)

**Comment by xsellier** [comment]
Hey,
This will be part of the rework of the post-mortems.
I'm linking this issue with the project's item.
