### ISSUE TITLE
Suggestion: Improvement Online Multiplayer Feature

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#107]
did an online game again,  so here's the problem i see with it:

genre/theme: post-apo. / fps
size: normal
price: 15
released on: skylight vista
score: 90
1. month on market: 1,78 m units sold / server at 1,78 m
2. month on market: 1,04 m units sold / server at 1,04 m
3. month on market: 259,02k units sold / server at 259,02k
(in 3.month the server counter in the menu bar says 234,87k <=BUG)

what i get by these numbers, is that only the normal sales go into server and players who bought the game in the first month are gone in the third month. if i look at the sales graph of a normal game and an online game they look really the same, for an online game i would predict, a more stable playerbase, as i see the number above i get that feeling that in the 3. month nobody from the 1. month plays the online game anymore. as it is right now online games feel like a normal game, the only difference is that you have to pay for the servers.

did another online game, as before but price on 4 or 5, the sales and server graph looks the same

for e.g.: sub. based but need to buy copy too, i would do a "calculation" like this:

hit the market:
             copy sales 1m 
             server 1m
2. month:
             new copy sales : 700k
            "subs" by current online players: 800k
             server 1,5m
and so on...
if time flies by, new sales go down (like normal games) but the subs current players stays a bit longer
(the longevity of a game could be improved here later, if you add in the DLC-feature. additional there could be some events within the online games, hacker, glitch-abuse, that leads to less subs/sales)

possible solution:

if you choose to make an online multiplayer, the release window gets 4 options

1. sub based but need to buy the game too, e.g. world of warcraft style
2. only sub based, no need to buy copy, dont have an example in mind here, might be some mmos with it 
3. FTP with MTX, e.g. every free to play game, mmos, dota, Battleroyal...
4. Need to buy copy, with MTX e.g. EA-Sport games,Battlefront, most EA-games xD

![sketchonlinempgames](https://user-images.githubusercontent.com/48098478/53828485-173fd800-3f7e-11e9-961b-351e886a469f.jpg)

**Subprice and MTXprice could be changed later in the server menu**
![sketchonlinempgames2](https://user-images.githubusercontent.com/48098478/53829644-e7de9a80-3f80-11e9-9d19-02a11bc3e4ad.jpg)

**Comment by toxyy** [comment]
To add onto enhancing multiplayer meta:

- game rivals (halo vs cod vs gears), top games of a genre (perhaps maybe even genre + a few themes or something) are rivals of one another. if halo releases in september and cod in october, i should expect a dip in online activity
- more consistent online numbers, i know that the game will not have any numbers near its launch value but the number of people online seems to be pretty low and unaffected by anything else (a new game release for instance)
- online count drops if i release a bad game, bungie released destiny 2 which ill never play but its not detracting from me hopping on any other halo server right now at all... so this behavior is a bit weird in my opinion. though if i were to release a sequel, i suppose that online numbers from the old one should drop and move to the new one

**Comment by xsellier** [comment]
Everyting has been implemented in v0.29.0.
Including:
- Subscription price
- Game price (can be 0 if needed)
- DLC
- Updates

I'm now closing this ticket \o/
