### ISSUE TITLE
Improvement Game-History-Panel (Filter & Review)

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#109]
Add a dropdown menu to select a genre, in that way the game history panel only shows the games of one genre, would really help, because i am fine-tuning some genres, so i compare the last games in a genre with each other.

Button "Filter genres"
	=> opens a drop down menu where you can select a genre
		=> only games in selected genre gets shown

If you want to have displayed all games back again select "show all games" in the filter options, therefore let the first option in the drop down menu be fixed as "show all games".

Add the review (final magazine) for that game here too, as you want to do it while you develop a game.

![5](https://user-images.githubusercontent.com/48098478/53915541-71b16500-4060-11e9-91d1-708adcaa9e9a.jpg)

**Comment by Tesba** [comment]
I add something from Steam Forum here too:
- Please add a platform match indicator to the game history. 

and additionally you could add genre/theme/audience match here too

**Comment by xsellier** [comment]
Platform indicator, theme genre, and also designdevelopment/polish ratio have been added to the panel history

**Comment by xsellier** [comment]
![image](https://user-images.githubusercontent.com/6616005/65617175-50777e00-df8a-11e9-83ae-24cb98a07b4b.png)

Implemented 100%
