### ISSUE TITLE
Pack game (resources) into (archive/binary)

### ISSUE THREAD

**Issue by Heyter** [binogure-studio/city-game-studio-i18n#111]
U can pack game (resources) into (archive/binary) not .exe ?
Because, it eating more RAM.

**Comment by xsellier** [comment]
Sure, Im gonna do so test this weekend, and if it is the case, I'm gonna split it into multiple files.

**Comment by xsellier** [comment]
Thank you, the game runs better that way!
Like it is 100% better. It should be part of the next update
