### ISSUE TITLE
Suggestion: rent out a building

### ISSUE THREAD

**Issue by ekim1991** [binogure-studio/city-game-studio-i18n#135]
if you buy a competitor, you have a lot of buildings. At the moment you can use this building or sell it. Why you cant rent it out to another company to earn some permanently money? :)

**Comment by xsellier** [comment]
Because it is a video game company not a real estate agency

**Comment by xsellier** [comment]
Also, with v0.29.0 you can also use several studio to make one game (joint project).
Im closing this ticket now
