### ISSUE TITLE
Suggestion: Delete some themes, make them simplified.

### ISSUE THREAD

**Issue by Abstimus** [binogure-studio/city-game-studio-i18n#139]
Hey there!

I think we got to many themes for games. It is good to have some, but not too many. I just think to delete the smaller game themes.

**Comment by xsellier** [comment]
If you have a list in mind, feel free to share it.
However as of today, I'm not willing to remove themes (atm)

**Comment by JjustGreg** [comment]
Tbh for me more choice is always better.
Maybe a menu change could make it easier? 
For example, fantasy, dragon, medieval, mythology etc in a category folder.

So you click on the folder and see them.
So in this example maybe call it "Fantasy" or something if it makes sense.
That way you can easily find the type of theme you look for quicker, and doesn't flood the themes section.
Theme categories!

**Comment by toxyy** [comment]
> 
> Maybe a menu change could make it easier?

Or even using the screen from when we unlock themes.  I agree with the more options, though some get a little confusing.  Some existing games can exist with a few different combinations so I'm unsure of which to make in that case.

**Comment by xsellier** [comment]
No activities in a year, closing it.
