### ISSUE TITLE
A little help with the Russian language

### ISSUE THREAD

**Issue by SashaSouer** [binogure-studio/city-game-studio-i18n#141]
LABEL_THEME_MEDIEVAL : Средневековый #It was written with a small letter.
LABEL_THEME_GAMEDEV : Геймдев #So it will be clear for Russia. Than the game devil.
LABEL_THEME_ANIME : Анимэ
LABEL_THEME_CARTOON : Мультфильм #It was written with a small letter.
LABEL_THEME_KAIJU : Монстр 
LABEL_TYPE_RTT : Стратегия в реальном времени
LABEL_TYPE_FPS: Шутер от первого лица
LABEL_TYPE_TPS: Шутер от третьего лица
LABEL_TYPE_EROGE: Хентай

**Comment by xsellier** [comment]
Thank you, I've just added it
