### ISSUE TITLE
Suggestion: Exclusivity

### ISSUE THREAD

**Issue by SashaSouer** [binogure-studio/city-game-studio-i18n#142]
I can explain the whole concept.
With the advent of porting in the game, I want the exclusivity feature to appear as well.
For example, the company "Sony" seeing that the company makes good games for about 5-10 years. Offers you a contract to sell games without taxes (I saw that the complexity of the normal paracents is 25), but without the possibility of porting games to other console fronts.
 Time contracts can I think for a random from 1-5 years.
Example:
We are the representatives of the company "Sony" impressed with your recent success, we offer you a contract for n-years, taking into account the release of games exclusively on our consoles.

**Comment by SashaSouer** [comment]
Also, one of the features of the contract can be made to provide consoles before they are released into wide use; companies need this so that at the start of sales of consoles there are games.

**Comment by xsellier** [comment]
Thank you for the suggestion, it's been implemented in v0.31.0
