### ISSUE TITLE
Suggestion: Systéme de DRM

### ISSUE THREAD

**Issue by inferiacola** [binogure-studio/city-game-studio-i18n#144]
Bonjour j'ai une suggestion d'ajout de système de DRM en gros 

Au début du  Développement du jeux  rajouter une case DRM : avec plusieurs DRM qu'on pourrais choisir avec un délai de crack différent  Un par exemple a 100.000 $ Qui embêtera les crackeur de 3 jour ensuite un a 500.000$ Pour 1 semaine et un a 1.000.000$ pour 3 semaine mais si vous décider de mettre le DRM  sa impactera le Niveau de Fan mais aussi le Niveau de Bénéfice que vous ferrez .

Voila mon idée :)

**Comment by xsellier** [comment]
C'est une bonne idée, mais ce sera un petit peu plus compliqué que ça. Car les DRM devront avoir un impact sur la notation (du au fait qu'ils impactent les performances) en plus du reste

**Comment by inferiacola** [comment]
Oui bien-sur hâte que sa sois rajouter ainsi que les autre Suggestion :)

**Comment by xsellier** [comment]
Closing this one for the new ticket in english
(Je ferme ce tiquet car il existe un autre tiquet rédigé en anglais).

https://github.com/binogure-studio/city-game-studio-i18n/issues/520
