### ISSUE TITLE
Suggestion: Systéme D'interview 

### ISSUE THREAD

**Issue by inferiacola** [binogure-studio/city-game-studio-i18n#145]
Bonsoir j'ai une suggestion a faire , La voici

Un système d'interview comme sa sa rajouterais un autre truc que les convention je m'explique 
rajouter un système d'interview de journaliste de pc gamer tout sa , en gros avoir des question ou on dois répondre et en gros et sa nous donnera de la hype en plus , je sais pas comment expliquer mais un systeme d'interview ou on parle au journaliste et on nous pose des questions sur le jeu et on dois répondre avec des répondes automatique et sa rajoute de la hype a notre projet ,desoler si je me suis répéter 

Voila :)

**Comment by xsellier** [comment]
Translated with deepl.com
> Good evening I have a suggestion to make, here it is
> 
> An interview system like that would add something other than conventions, I explain myself.
add a pc gamer reporter interview system all that, basically have questions where we have to answer and roughly and it will give us more hype, I don't know how to explain but an interview system where we talk to the reporter and we are asked questions about the game and we have to answer with automatic answers and its addition of hype to our project ,desoler if I have repeated myself
> 
> Here it is:)

**Comment by xsellier** [comment]
> Je pense que pour te différencier des autres jeux du même type que City Game Studio, il serait important de développer la partie des interview par les journalistes et tout le système qui entoure les annonces via les conventions (Je peux prendre l'exemple de l'E3) :
> 
> - Recevoir des demandes d'interview pour un projet en développement et choisir d'en parler librement ou de noyer un peu le poisson pour garder le suspens. Le choix des réponses pourrait directement impacter la barre de hype que va générer la sortie du jeu
> 
> - C'est un peu dévié du sujet principal mais le développement d'une feature sur un community manager serait pas mal également. Comment le personnel responsable de la communication envers les joueurs doit se comporter vis à vis de la sortie d'un jeu. S'il fait une boulette, la hype diminue. Au contraire, s'il fait un job de qualité, le jeu prend tout de suite de la valeur... C'est assez vague, dis moi si tu vois où je veux en venir.
>
> -  Pour les conventions, je pense qu'une petite feature d'animation montrant une scène où un présentateur (le joueur donc) se montre devant une foule de spectateur en folie pour annoncer un projet sur lequel le studio de développement bosse (en gros, faire un truc du genre "A World Premiere". Ça donnerait très clairement un énorme plus à la feature des conventions et celle-ci servirait à autres choses que de gagner des abonnés.
> 
> Voilà en gros les idées. J'ai pleins d'autres types d'ajouts que je pourrais te détailler mais je pense que tu dois recevoir pas mal de demande de features à implémenter dans le jeu et ta roadmap n'en finirait jamais donc je m'arrête là ^^

**Comment by xsellier** [comment]
It's been implemented with v1.0
