### ISSUE TITLE
Renommer les employer 

### ISSUE THREAD

**Issue by inferiacola** [binogure-studio/city-game-studio-i18n#147]
Bonjour j'ai u une idée un système pour pouvoir renommer les employer

**Comment by xsellier** [comment]
Peut-être qu'un mod pourrait permettre de faire cela, mais renommer les employés et trop irréaliste pour que je l'implémente.

**Comment by xsellier** [comment]
Peut-être qu'un mod pourrait permettre de faire cela, mais renommer les employés est trop irréaliste pour que je l'implémente.

**Comment by xsellier** [comment]
A moins qu'il y ait une forte demande pour cette feature (je dirai qu moins 20 personnes commentent), sinon je ne l'implementerai pas.

Ceci dit je la laisse ouverte pour que les gens puissent voter.
