### ISSUE TITLE
Suggestion: Bugs and updates

### ISSUE THREAD

**Issue by inferiacola** [binogure-studio/city-game-studio-i18n#148]
Pouvoir faire des mise a jour au jeux comme les jeux qui utilise le multijoueur  .

**Comment by xsellier** [comment]
> Introduce bugs and updates. This can add a new sequence to the end of the development.
> You can have an optional playtest at the end of the development where you hunt down bugs.
> This can also improve staff mechanic, they might introduce bugs during development that can either be found and fixed at the end or after release with patches.

**Comment by xsellier** [comment]
Faire des mises à jour a été introduit avec la v0.29.0.
Game updates are implemented in v0.29.0

~~Regarding bugs, not yet implemented. Keeping this ticket open~~
There is nothing in this ticket about bugs, closing it
