### ISSUE TITLE
Slower time 

### ISSUE THREAD

**Issue by JjustGreg** [binogure-studio/city-game-studio-i18n#152]
Right now we every "day" is a full month.
But what if you can choose a "day" be a week? 
That way you can play in time periods longer and release more games In said periods? 

Different time progression speeds would be nice.
Rn you can play start to finish in 9 hours.
Adding a different time progression can already make start to finish from 9 hours to more than 20 hours.
Just an idea

**Comment by xsellier** [comment]
I have a way to make the game longer.
For example there are 4 weeks per month, If I change it for 8, then you will have 18hours to finish the game.

**Comment by JjustGreg** [comment]
That was actually what I meant 😋
Would be really awesome!

**Comment by xsellier** [comment]
Implemented in version 0.16.2
