### ISSUE TITLE
Chart of marketing on game sell card

### ISSUE THREAD

**Issue by DenKuzn** [binogure-studio/city-game-studio-i18n#158]
I see no difference in marketing costs and profit from sales of games.
In the later stages of sales, it turns out that marketing costs exceed the profit from sales.
It makes me calculate the difference in mind. And you can make a graph (chart) and show that at some point the game has ceased to make a profit, despite the fact that it is still for sale.

In Russian.
Когда игра продается мало, а маркетинг жрет много - это не уловить сходу. Приходится просчитывать суммы маркетинга и соотносить их с прибылями от игр. Иначе, в какой-то момент сумма маркетинга начинает превышать прибыль, и баланс начинает стремительно уходить вниз.
И ничто не сообщает об этом. И нигде нельзя это увидеть. Только догадаться подсчитать траты маркетинга самому.

**Comment by toxyy** [comment]
What score are your games that you market?

**Comment by DenKuzn** [comment]
> What score are your games that you market?

It should not matter.
We are talking about graphs of profit game. The graph shows a profit of 10k (for example in May month).
And marketing for this game costs 15k (May month).
That is, in fact, the game does not make a profit, and even takes away money through marketing.
But this is not understandable, since marketing is taken into account in one place, and the profit of the game is taken in another.

**Comment by xsellier** [comment]
A rework of the marketing feature is incoming.

**Comment by xsellier** [comment]
Implemented on v0.22.1
