### ISSUE TITLE
Game crashes around year 2100 (give or take some years)

### ISSUE THREAD

**Issue by toxyy** [binogure-studio/city-game-studio-i18n#160]
Game window just closes.  Stuff is pretty laggy at this point anyways, you have to wait a while after pressing the new game button, etc.

savegame:
https://www.mediafire.com/file/42fw232bufu2gao/d1545392-7262-420d-9739-29df8287298b.cgs/file

**Comment by xsellier** [comment]
Fixed with vers 0.16.2
