### ISSUE TITLE
Preserving sliders

### ISSUE THREAD

**Issue by SashaSouer** [binogure-studio/city-game-studio-i18n#162]
Another suggestion is to keep the sliders in the same position as in the previous games of the same type. Just knowing exactly what the correct paracents are, but the game doesn’t give as the reports didn’t say yet the perfect position and you have to put everything again for each game. To do this, any button on the type of "As in the previous game." This will make the game easier for those who make games of the same type many times.

**Comment by xsellier** [comment]
While keeping the gauge at the same position might be a good idea, in fact, for someone who uses a cheatsheet it just disables the whole postmortem mechanism.

After several postmortems, the blue gauge are soo tiny that it is almost impossible to move them.
But, you will have to do a large amount of game before having that. So, there is a feature I'm working on, called contracts, that will allow you to improve the gauges while working on contracts.

**Comment by SashaSouer** [comment]
Can you explain the "counterattack" system in more detail?

**Comment by xsellier** [comment]
@SashaSouer Hey, Sorry for the delay. I don't know what is the "counterattack" system. Are you talking about the competitors that will react whenever your are trying to "attack" them?

> Another suggestion is to keep the sliders in the same position as in the previous games of the same type. Just knowing exactly what the correct paracents are, but the game doesn’t give as the reports didn’t say yet the perfect position and you have to put everything again for each game. To do this, any button on the type of "As in the previous game." This will make the game easier for those who make games of the same type many times.

Contract feature has solved this problem.

**Comment by xsellier** [comment]
Implemented as of v0.22.1
