### ISSUE TITLE
Enlever les notif email

### ISSUE THREAD

**Issue by inferiacola** [binogure-studio/city-game-studio-i18n#164]
Pouvoir avoir une option pour enlever les email ou en recevoir pour certaine option car a la long appuyer sur la croix sa deviens vite rageant

**Comment by xsellier** [comment]
Je comprends la frustration que les notifs peuvent engendrées.
Le truc c'est qu'il peut y avoir des informations importantes dans les emails. Donc je me demandais si:
1. Tu as une idée pour une alternative aux notifications
2. Manquer des emails peut mener a une incompréhension de certains évènements dans le jeu.

**Comment by inferiacola** [comment]
Au pire modifier la taille car je trouve que sa prend trop de place et au bout d'un moment on passe plus de temps a enlever l'email que jouer

**Comment by xsellier** [comment]
Je vois, ça peut aussi être une solution.

**Comment by inferiacola** [comment]
Ou alors a l'icone email tu mais des notif 1 , 2 , 3 , 4 ,5 etc

**Comment by xsellier** [comment]
J'ai pensé a ça aussi. Genre, si tu désactives les notifications en bas a droite, tu auras un petit bouton sur les emails en bas.

**Comment by inferiacola** [comment]
Oui est avec un bruit de notification comme sa on reçois les email mais on a plus a les enlever a chaque fois

**Comment by xsellier** [comment]
Bon, à la base c'était fait de cette maniere. Et ça n'a pas plus aux joueurs (vraiment pas du tout). donc je ne vais pas revenir en arrière la dessus, parcontre je vais permettre de switcher entre les deux possibilité. A savoir, la popup en bas a droite ou le petit icone sur la boite mail.
