### ISSUE TITLE
Suggestion: Placer les employer de préférence sur un bureau avec ordinateur

### ISSUE THREAD

**Issue by johan-buret** [binogure-studio/city-game-studio-i18n#168]
Quand on auto-assigne les employés dans un studio, en ce moment, ils sont répartis au hasard dans la pièce, que le bureau soit équipé d'un ordinateur ou non. 

Il faudrait placer les employés sur les postes avec un ordinateur en priorité puis laisser faire le hasard après.

**Comment by xsellier** [comment]
Bonjour Johan,

Avec plus de 3 ans de retard, cette suggestion a été ajoutée au jeu. Alors je ne sais plus quand est-ce que je l'ai mise, je crois en 2021, en tout cas merci de l'avoir faite!
