### ISSUE TITLE
Everything unlocked (without extra money, fans, etc.)

### ISSUE THREAD

**Issue by dastardlee** [binogure-studio/city-game-studio-i18n#174]
I'd love an option to start with all genres and milestones unlocked. I still want to play the game normally, where you start with normal amounts of money and with competition, just without the arbitrary restrictions.

**Comment by xsellier** [comment]
Thank you for creating this ticket.

I have few questions:
- Do you want to be able to do an internet marketing campaign in 1976 or should I keep it locked until it is unlocked normally?
- Does it apply to platforms (ie gaming consoles + PC) ?
- Does it apply to game port?
- For example the game genre Crook-like (ie Rogue-like) has been invented in 1980. So you want it be unlocked right away in 1976?

**Comment by dastardlee** [comment]
I still like the features of time passing, and things (genres, platforms, etc.) releasing the years they should. I mostly mean things that in real life wouldn't have to be "unlocked" like conventions, buying out companies, porting as you said, research, building studios/conference centers, all the starting genres, etc.

Basically all of the milestones like "get X amount of money/fans" or "release X amount of games".

Currently it just feels too linear/like a tutorial to me, doesn't give you the freedom to develop games you want to/do things in general you want to until later in the game.

**Comment by xsellier** [comment]
@dastardlee Ok I get it. I'm going to name this feature: "Advanced start" if it is ok for you.

**Comment by dastardlee** [comment]
Sure, that works. Again thank you for the updates so often, love the game.

**Comment by xsellier** [comment]
Implemented in version v0.19.0.

Steam announcement for more details:
https://steamcommunity.com/games/726840/announcements/detail/1604884597852074995
