### ISSUE TITLE
Display total and occupied studio desks

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#177]
Currently when you watch over your studio lists or manage a single studio, the only way to find out how much desks there are and how much are occupied is to count them, my suggestion is to display both counts on the two following screens: (pardon my horrible image editing)

![image](https://user-images.githubusercontent.com/25114435/55898588-36580800-5bc3-11e9-82ae-6e21b8cb453f.png)

![image](https://user-images.githubusercontent.com/25114435/55898635-538cd680-5bc3-11e9-9893-bd89ef40ab1b.png)

**Comment by xsellier** [comment]
Closing, implemented in version v0.17.0
