### ISSUE TITLE
Rework the fan base screen

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#179]
Currently the fan-base screen isn't helpful when you want to see how much fans you gained with a specific game (including ports) or entire series (original game + sequels), as the screens show each port and sequel as a separate game. 

As a reminder, this is how it looks like at the moment:

![image](https://user-images.githubusercontent.com/25114435/55899967-5e953600-5bc6-11e9-8517-b6e5e4fe1484.png)

My first suggestion is to display *all games*, currently it only shows games that are still on the market (the cancel button would only be on games that are still on the market) 

My second suggestion is to rework it into a two-level accordion, level 0 showing the series, level 1 showing all the games in this series, and level 2 showing the grade and fan base on all platforms the game has been ported on.

I made a practical example as i know my above explanation doesn't really help to visualize:

![image](https://user-images.githubusercontent.com/25114435/55901425-9782da00-5bc9-11e9-9dbd-69dd28fade54.png)

A troublesome thing with that suggestion is what name to use for each series, in my example it shows `Europa Universalis` as the name of the series, this isn't arbitrary but actually based on the name of the original game.

**The following part of this issue is probably too much work for what it's worth, if it was to be added, i think it doesn't need to be a priority at all**

> Though in some cases, you might not want to have a series use the name of the original game; To fix that i think adding the possibility to rename the series would be the best solution.
**Renaming a series wouldn't change anything else, it would only be used for the fan base screen**

**Comment by xsellier** [comment]
Nice one, it is quite easy to fix.

But I won't rework it right now, I've just added the platform (as a quick and dirty fix) for version v0.17.0.
With the rework, I going to add _selectable games_ so their fanbase will be added to the chart dynamically

**Comment by xsellier** [comment]
I've just updated it for v0.17.2, it now has game and gameports grouped

**Comment by xsellier** [comment]
Implemented as of v0.22.1
