### ISSUE TITLE
Cancel making a Game

### ISSUE THREAD

**Issue by ShadowLightDragon** [binogure-studio/city-game-studio-i18n#183]
Would it be possible to add the feature to stop naking a game once you started it. Of course all the money you spend in the time the game was in production is lost. I'm asking if it is possible beacuse it happened multiple times that I pressed the wrong button and started making a game with the wrong settings.

**Comment by xsellier** [comment]
Hey,

It is possible to cancel a game, just click on the trashbin icon
![image](https://user-images.githubusercontent.com/6616005/55981039-dd8c7c00-5c63-11e9-9603-cbc7f201b04c.png)

**Comment by ShadowLightDragon** [comment]
Uh, I feell realy stupid now. I didn't notice it even once, and I spend over 10 minutes looking for a way. I never noticed the trash icon. 
Thank you for the fast answer.
