### ISSUE TITLE
Rajouter le studio  dans la la lettre de démission

### ISSUE THREAD

**Issue by johan-buret** [binogure-studio/city-game-studio-i18n#189]
Quand un employé démissionne, il y a presque toutes les informations utiles, sauf le studio dans lequel il travaillait.

Il faudrait le rajouter 

" Mon départ s'explique par le fait que j'ai trouvé un nouvel emploi plus près de chez moi, et dans une entreprise plus attrayante **que le studio %s** ."

**Comment by PwaPois** [comment]
Hey!

Cela a déjà été proposé dans [cette issue](https://github.com/binogure-studio/city-game-studio-i18n/issues/178) et implémenté, c'est actuellement inclu dans la beta 0.17.4

**Comment by xsellier** [comment]
Effectivement, normalement le nom du studio est dans l'objet du courriel, et les statistiques de l'employé qui démissionne se trouvent dans l'email directement.

Si le nom du studio n'est pas dans le corps du message c'est pour gérer le cas ou un employé n'est passigné a aucun studio. Dans ce cas la, on obtient juste quelque chose dans ce genre la:

```markdown
# Objet
  Démission

# Message

  Bonjour,

  Par la présente lettre, je démissionne de mon poste chez **GAMING STUDIO** dès aujourd'hui.
  Mon départ s'explique par le fait que j'ai trouvé un nouvel emploi plus près de chez moi, et dans une entreprise plus attrayante.

  J'ai beaucoup apprécié les années passées a travailler avec vous, vous me manquerez tous!

  Cordialement
  **Jean seb**
```

**Comment by johan-buret** [comment]
Ça correspond au message que j'ai reçu, mais je n'ai pas compris que c'était  parce que j'avais oublié de placer ces personnes-là.
