### ISSUE TITLE
More Specific Games

### ISSUE THREAD

**Issue by WayneBoi** [binogure-studio/city-game-studio-i18n#194]
I think you should be able to make more specific games like in gdt. I will show you a picture to show you what I mean.
![To_Binogure](https://user-images.githubusercontent.com/50029864/56830469-b38fa800-6866-11e9-89a7-20d6f1c7b909.PNG)

**Comment by xsellier** [comment]
Sounds like having game engine, but without having game engine, it is quite interesting indeed!

**Comment by xsellier** [comment]
Closing it because I will implement it has a game engine.

Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/260
