### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by Tatator01** [binogure-studio/city-game-studio-i18n#207]

**Comment by xsellier** [comment]
Merci pour le retour.
Et j'ai implémenté la partie pour les campagnes marketing. C'est-a-dire que maintenant on peut voir combien coûte une campagne marketing au total. 
Pour le reste çá va venir petit a petit

**Comment by Tatator01** [comment]
super !!!

**Comment by xsellier** [comment]
> 

Bonjour,

Voici mon retour sur le jeu Game City Studio.

Mes remarques ne concenent que moi et ne valent pas criique objective dans l'absolu.

    Sur l'écran 'Nouvelle Partie', ce serait un confort de pouvoir mettre le dernier nom de compagnie utilisée. C'est bête mais ça ajoute un petit plus que j'apprécierais.

    je trouve les couleurs du jeu un peu ternes, ici je te montre en augmentant le contraste sur un personnage :

gcs

Peut être que simplement ajouter une option de contraste dans les paramètres serait suffisant.

    la publicité ne montre qu'un prix, supposé être par mois, mais serait il possible de voire le prix réel calculé en fonction du nombre de mois sélectionnés ?

    des couleurs sur les vignettes représentant les thèmes de jeu possible seraient super ! peut être des variantes pour les styles approchants...le top seraient des animations aléatoires, surtout si elles sont simples...mais bon, depuis que j'ai appris le creaping feature, je n'insiste pas.

    il est assez déroutant de ne pas pouvoir paralleliser les développements quand on a plusieurs développeurs. En fait actuellement, pour developper deux jeux en même temps, il faut deux studios. Je pense à ça car a un moment j'ai voulu sortir un jeu et faire travailler la moitié des développeurs ( 2 / 4 ) sur le portage d'un jeu qui avait marché..et la j'ai pas eu l'effet wahou :)...

    le fait de devoir se replonger dans les mails pour retrouver les posts mortem est assez rédibitoire...car on ne peut pas filtrer les mails. Aussi, au bout d'un moment, quand on tente plusieurs combinaisons de thèmes et types de jeux, on voit bien qu'on a déjà des points de découvertes sur les retours sur expériences, mais il est fastidieux de relire les post mortems correspondant.

    par ailleurs, les post mortems sont trompeurs. J'hésite toujours à bouger un niveau de développement vers les 100%, car je perds souvent beaucoup d'argent en mettant l'accent sur ce qui est sensé être important pour un jeu et cela ne marche pas...mais cela, c'est peut être moi qui n'ai pas saisi le truc.

    le rapport des ventes est assez flou je trouve. Quand il est annoncé 10% d'améliorations, je n'arrive pas à percevoir sur quoi cela porte. Est il possible de mettre sur le graphique les courbes vente prévu / vente réelle à partir du moment où le rapport et reçu ?

    sur la réservation de places pour les salons, il est difficile de comprendre l'impact sur ce qu'on réserve. Quelle est la règle ? Est il possible au moins de savoir combien de jeux sont présentables en fonction de l'espace réservé ?

Voilà mon premier retour...

**Comment by Tatator01** [comment]
Hey connard, quand je supprime mes commentaires te sens pas obligé de les repomper pour ton confort..je ne suis pas ton domestique.

Bien trop prétentieux ce petit bonhomme, roublard....

Ah ah ah ... 

J'ai rectifié mon avis sur steam, je pense être dans le vrai cette fois ci...

Franchement....

**Comment by xsellier** [comment]
Navré je ne voulais pas jeter le travail que tu avais fait.
Je me disais que je pouvais reprendre ces remarques pour faire un meilleur jeu,

Merci quand même

**Comment by Tatator01** [comment]
non, tu es un connard, sournois...

mais t'as le droit, c'est pas grave...tu es...comme ça...dans ton 'drama' pour connard....fiche moi la paix pour de bon, Mr Connard.

En fait ton jeu c'est de la merde de bout en bout, j'ai voulu être sympa, j'y ai joué plus que je ne joue à d'autres jeux, j'ai fait un 'reporting', en bref, j'ai joué le jeu...

Sauf que Twitch c'est un peu comme Firebase, la télémétrie, ça te sers juste pour savoir comment tu peux enculer les gens en direct.

Alors nan, tu es une crapule et je hais ton jeu sur tout les plans, graphismes, le fond etc... rien à branler...

Et maintenant tu te calmes un peu et tu me fous la paix, Binocon...
