### ISSUE TITLE
Suggested Option : Pause Game on New Game/Load

### ISSUE THREAD

**Issue by nekomaster** [binogure-studio/city-game-studio-i18n#208]
One thing I like in Open Transport Tycoon is that theres an option to enable "Pause game on new game/load" so that when you get into a game when its done generating a new map or loading your save it'll pause the game which is nice if you get distracted or just want to look around before doing anything.

It'd be nice if that was possible in City Game Studio since things can change so quickly depending on the game speed selected. ALso might prevent people from accidentally leaving the game going when loading up a game if they get distracted or have to deal with something away from their computer.

**Comment by xsellier** [comment]
What about a welcome back popup when the game is loaded?

**Comment by nekomaster** [comment]
I think it'd be less of a hassle for players if the game just paused on loading (as an option if possible)

This way theres less stuff to click through and allows players to grasp the situation upon loading in case they forgot what was going on with their save, or if a bunch of things suddenly happen after loading.

**Comment by xsellier** [comment]
Implemented in version v0.18.9
