### ISSUE TITLE
 How about adding a game prize of the year?

### ISSUE THREAD

**Issue by mendesjf86** [binogure-studio/city-game-studio-i18n#212]
It would be nice if we had a game awards of the year and the studio that made the game of the year would win a cash bonus or the option to sell the game's year game edition and make more money from it.

It would also be nice to be able to advertise games at conferences,

**Comment by xsellier** [comment]
That is on the roadmap already :+1: 
https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-17207517

**Comment by xsellier** [comment]
And it's been implemented with v0.20.0
