### ISSUE TITLE
Canceling a game

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#213]
When canceling a game it says cancel: "console name" like when publicing on Ulysse it says Ulysse. (i also made an issue on github)

![image](https://user-images.githubusercontent.com/10974607/58695888-bebe8200-8396-11e9-91ba-10a035a16004.png)

**Comment by xsellier** [comment]
Yes it does, because there is only one card game (right column) for a game, even if you have ported the game onto several platforms
