### ISSUE TITLE
Suggestion to allow employees to be trained to ten stars,

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#214]
You would pay for their classes (34k per star) and they would act like they're ZZZ'ing. the process of getting them to ten stars in all categories needs to take a long time (4-8 years). The AI will do this as well at the end of the game, for a easy way to snatch max employees.

**Comment by xsellier** [comment]
I was thinking of a similar feature lately, but it would be available only in custom games.
For example, when you start a game today you can chose between Easy, Normal, Hard and Insane. I will add another choice to create a custom game rules.

**Comment by Hisu0** [comment]
Maybe implement it as a recruitment option? Say, in HR screen, tick a box saying "elite cadre" and afterwards, you'll only get employees with ten star potential (not necessarily skill), but the new lists will be much shorter (only a handful per month), they will always ask for maximum salary and taking them will cost extra depending on how many of ten star potentials are in the industry (as in, hired by everyone, including your competitors).
You can adjust that extra cost and/or its progression for different difficulty levels.

**Comment by xsellier** [comment]
Thank you for the suggestion.
It's been implemented with v1.1
