### ISSUE TITLE
Suggestion for button in game card to cancel game and all ports at the same time,

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#216]
Use would be just to remove the card with two clicks (One click on the button, and another click on the confirm button. This definitely needs a 'ARE YOU SURE?' pop-up). This will save you from having to cancel each port one at a time.

**Comment by xsellier** [comment]
There is no popup at the moment, but you can now already cancel a game completly (including ports)

**Comment by xsellier** [comment]
It tooks a while, but 2 clicks are now needed to cancel a game. Click on the menu, then click on Cancel.


![cancel-game](https://user-images.githubusercontent.com/6616005/70378734-026be880-18f2-11ea-90c2-223985f275b0.gif)
