### ISSUE TITLE
Have studios reoccupied after being sold

### ISSUE THREAD

**Issue by mendesjf86** [binogure-studio/city-game-studio-i18n#217]
I was playing in sandbox mode to perform some tests in the PT-BR translation and noticed something ... When we bought a studio and sold it ... The space where the studio was, is available for rent and no company appears again.

**Comment by xsellier** [comment]
Thank you, I never tested it

**Comment by xsellier** [comment]
So, I've just tested it. There is no worry to have, competitor will buy every single available studio if you gave them enough time.

If you encounter this issue in your game, please, send me a bug report.
