### ISSUE TITLE
Suggestion: Option to turn off yawning when people go on Holiday,

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#219]
With human resources the constant yawning can drive you up the wall. All you can do for now is turn off the sound. A option to turn off just the yawning would prevent mild psychotic episodes.

**Comment by xsellier** [comment]
Indeed. That is a good idea >_<

**Comment by xsellier** [comment]
What about removing completely the yawning?

**Comment by Grover-R** [comment]
Possibly. Some may like it. Some not. This is on you, good sir.
