### ISSUE TITLE
Values don't match (even that is just 1 point...) and cut-off text in the post-mortem screen

### ISSUE THREAD

**Issue by Eduardo-Junior** [binogure-studio/city-game-studio-i18n#22]
![screenshot_4](https://user-images.githubusercontent.com/45540161/49342809-d1a20500-f646-11e8-9b90-250354ad7f7d.png)

**Comment by Eduardo-Junior** [comment]
![screenshot_5](https://user-images.githubusercontent.com/45540161/49342826-162da080-f647-11e8-9b35-9b5d76a76a73.png)

**Comment by xsellier** [comment]
@Kannabian Thank you. Fix issue fixed already. For the second one Im going to change the whole panel to have something more ergonomic :dancer:

**Comment by Kannabian** [comment]
`close#22`
