### ISSUE TITLE
Suggestion: Ability to disable certain email messages & make sure spontaneous applications appear immediately,

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#220]
Ability to turn off pop-up of certain mail (sales report, platform discontinued, etc). Spontaneous application are very important (Especially at the higher levels of difficulty) and should appear immediately, possibly even pausing the game with a middle screen pop-up alert.

This is kinda two suggestions at the same time but since they're both part of mail, then I'll just leave them together.

**Comment by xsellier** [comment]
New notification system fix that bad behavior (v0.20.0)
