### ISSUE TITLE
Suggestion: "Ability to spy on other game companies to gain game research"

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#222]
This option would be expensive (A million a month) but could allow you to unlock a genre and max it's research without ever making a single game of that type. Possibly would require a studio with a certain amount of skilled employees to raise chance of success.

(The below is based of theoretical mechanics not yet in the game)

Penalties would be severe for failure or if you get caught. Massive fines, fans would leave in droves, and employee happiness would tank so hard that many will quit. Customers may not be very willing to buy your games for a couple years, even if they're 100/100.

**Comment by xsellier** [comment]
So, I reworked the _spy feature_. And now it is a mini hacking game. Whenever you are spying on a competitor you will unlock game genres with a lot of tips. Meaning you won't have to do much postmortems if you've unlocked a game genre by spying on a competitor.

This update should be part of update v0.25.0-rc11 (out later today).
Please tell me if it is something like that you wanted.

**Comment by xsellier** [comment]
Closing since you can unlock game genre by spying on competition
