### ISSUE TITLE
Suggestion: Spontaneous employees added to 'Hire their Employee' and possibly removed from mailbox,

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#223]
Would allow you to grab a perfect employee from another company. Their pay requirements should be much higher than a non-perfect employee.
Whether or not the spontaneous employees that appear in contacts continue is up to the developer.

(Ideas below are based on mechanics not yet in the game and are theoretical)

You may encounter a perfect employee that is a 'fan' of the company they're working for. They'll either demand a huge amount to join your company and demand a much higher pay than what they already have. They might also flat out reject your leech attempt and warn their company, who will warn all the others. Leeching will become incredibly difficult for a estimated time afterwards.

**Comment by xsellier** [comment]
For the first part, Poaching employee should be part of the next update (october 2019)
The second part, about removing spontaneous applications emails, it's been implemented.

**Comment by xsellier** [comment]
And yup the update is live!
