### ISSUE TITLE
Suggestion: Post-mortem for ports

### ISSUE THREAD

**Issue by Grover-R** [binogure-studio/city-game-studio-i18n#225]
A post mortem for ports but only will give information about the genre and platform rating per game genre. Adds a reason for making ports other than profit and fans.

I highly recommend this not give research to game development. the player could easily max out the tips in a single game.

**Comment by xsellier** [comment]
I get your point. But I stand with one post-mortem per game. Porting a game is not a new game, it is just the same game on another platform. So you won't get any new information from it, since what you've done is only porting the game without changing the gameplay/story...
