### ISSUE TITLE
Suggestion: Digital Platforms

### ISSUE THREAD

**Issue by SeanKR-IRE** [binogure-studio/city-game-studio-i18n#227]
After 2005 or so maybe allow some form of digital platform sales like Steam. Along with the Digital Platform release then you could design your own competitive platform with passive income as well as server upkeep etc.

**Comment by xsellier** [comment]
Definitively on the roadmap already!

**Comment by xsellier** [comment]
This feature has been implemented in v0.26.0-rc0
