### ISSUE TITLE
Suggestion: Contract Filter/Sorter

### ISSUE THREAD

**Issue by SeanKR-IRE** [binogure-studio/city-game-studio-i18n#228]
An Ability to sort contracts(Dropdown Box):
 
- Design/Development/Polish (By default since currently the contract is not sorted at all [Example](https://imgur.com/a/DbRFw60))
- Highest to Lowest Required Points
- Highest to Lowest Income

A Filter System(New Window with Check Boxes): 

- Hide selected genres like Beat-em-up's, Dungeon etc (If looking for Tips)
- Hide Indie/Normal/Big/AAA
- Hide Design/Development/Polish Contracts (Helpful until training staff is implemented)

**Comment by xsellier** [comment]
I've just implement a quick sort by default. It is better than before but not satisfaying enough

**Comment by SeanKR-IRE** [comment]
It's much nicer than before which is extremely appreciated being a fast patch, Thank you :)

**Comment by xsellier** [comment]
Filtering option implemented:
![image](https://user-images.githubusercontent.com/6616005/65619989-15c41480-df8f-11e9-8c6d-0e2f1045006e.png)
