### ISSUE TITLE
Suggestion: Pause Developement of game.

### ISSUE THREAD

**Issue by SeanKR-IRE** [binogure-studio/city-game-studio-i18n#229]
One issue i've got with the development with AAA games is around the polish stage even with full energy at the start of development my team goes on holiday and then i lose points on the polish section which effects my overall score. 

I was wondering if there is a way to either automatically pause the game when the staff goes on holiday or maybe a button beside the development panel that you can temporarily pause since each stage of development advances at a constant pace even with no one working on it.

**Comment by xsellier** [comment]
Implemented with v1.2.
You can try it already via the unstable Steam branch.
Right click on City Game Studio, select properties then on the Betas tab select Unstable.
