### ISSUE TITLE
Suggestion: Joint project for studios

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#232]
Having several studios working on a single project

**Comment by SeanKR-IRE** [comment]
Possibly have some studios specialize is a stage of development? 

Like one studio full of Designers work on that stage, another studio of Developers work on that stage etc?

That would help with staff also tiring out during development and halting the points developed which ruin the game on reviews

**Comment by xsellier** [comment]
That is how Im thinking it

**Comment by athene-noctua** [comment]
Maybe also allow different studios to join up during one stage? At a reduced efficiency, of course.
Also, there's no indication of whether the points developed are sufficient or not, so when it's a large studio, you have no way of knowing if it performs up to scratch.

**Comment by xsellier** [comment]
This has been implemnted in v0.29.0.
I'm now closing this ticket \o/
