### ISSUE TITLE
Weird but very good feature I think

### ISSUE THREAD

**Issue by WayneFTWGitHUB** [binogure-studio/city-game-studio-i18n#242]
You will never know that was written here.

**Comment by xsellier** [comment]
This feature seems really deep, maybe too deep.
Fact is I like that making a game is complex but not too complex. I mean I want the player to focus on managing its company more than adding in game creation complexity.

However it is a nice suggestion and it might be interesting for people who want to implement it as a mod later.

**Comment by GeneralNW** [comment]
> You will never know that was written here.

Oh but I get email notifications about what was put here heh heh
