### ISSUE TITLE
Suggestion: Staff Scouting

### ISSUE THREAD

**Issue by SeanKR-IRE** [binogure-studio/city-game-studio-i18n#243]
Maybe an option with HR characters unlocked you can pay X amount of money for staff scouting. Doing so would mean more/less specialized staff applications depending on the amount and duration of the scouting.

This could also mean if you pay a lot you can get some staff that are nearly perfect stats but for a large scouting fee. The trade off of doing it this way rather than hiring spontaneous applications and then training them would be the staff you hire after the scouting would have a much higher salary.

**Comment by xsellier** [comment]
Yup, in fact I will replace the _poaching_ feature with something more like that.
![image](https://user-images.githubusercontent.com/6616005/70378896-17e21200-18f4-11ea-8897-51612dceaaf0.png)

**Comment by xsellier** [comment]
Since you will be able to train your staff to reach 10 stars (see https://github.com/binogure-studio/city-game-studio-i18n/issues/214) , and since you can also poach your competitors staff with spending money, Im gonna close this one
