### ISSUE TITLE
Walls and/or interior wall painting

### ISSUE THREAD

**Issue by kechketach** [binogure-studio/city-game-studio-i18n#246]
Double wall and painting inside wall or wall without black strip on the side

I would like if people are interested in the idea, that we can add double walls, what I mean by that is the equivalent of 2 walls in terms of thickness and without any gap between the 2, in order to make it a wide and thick wall or a load-bearing wall effect
The reason? let's say the pillars are nice and I would like to be able to optimize their use a little more
Like on the screen but without the space, not by filling this space between the 2, just that the 2 are closer, such as the extension of the pillar

![mur double](https://user-images.githubusercontent.com/54148190/63110124-04005200-bf8b-11e9-8576-2a1c0bfa585d.png)

As for the painting of the interior walls, I was thinking mainly of the fact that aligning solid walls is a little too much of a screen because of this little black strip between them, nice in some configuration and less so, so the fact of being able to paint them, would allow on the one hand to no longer see this black part between them and to personalize to differentiate the work or rest areas
That said, simply having walls without the black stripe on the side (leave the one above and on the base), but with various colors or patterns (in a style similar to the paintings on the building walls, but slightly different, 1 or 2 patterns would be enough) could make the rooms a little more pleasant 

Then I don't want it to make the game overloaded with stuff that's not very useful, especially since it would be for our personal pleasure, visual since it won't have any impact on the game.
The second proposal is not necessary, it's just an idea because I like to customize the various rooms

Translated with www.DeepL.com/Translator

**Comment by xsellier** [comment]
Implemented in v0.24.0-rc1:
https://partner.steamgames.com/doc/store/application/branches
