### ISSUE TITLE
Suggestion: Some Ideas i have

### ISSUE THREAD

**Issue by StormyHauk** [binogure-studio/city-game-studio-i18n#254]
Hi i have some ideas and i am so sorry if my ideas is already submitted.

1. I dont know if this already is a feature in the game, but i would like to cancel a game when they port it since sometimes i see that i the took wrong team.

2.  I would also like if i could switch wich studio is working on a game or port under the development since the same issue that i said on 1 that i sometimes pick the wrong team

3. This is the last one i promise. I would like to make dlc, expansion pass and game bundles.

I havent finished the game so if some of these is added on later in the game i am so sorry that i wasted your time. I hope that if some of these isnt in the game that you can use this. Thanks for your time

**Comment by xsellier** [comment]
Welcome @StormyHauk 

1. It is already implemented. You can click on the cross to cancel a game port or a game.
![CancelGame](https://user-images.githubusercontent.com/6616005/63650895-a5bb3800-c71d-11e9-8c53-f25961e5232e.png)

2. I'm going to implement a way to have several studios working on a single project. But this idea is really good!

3. Already planned and you are right I should have implemented that sooner (https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-18020128)

Anyway, feel free to send more suggestions

**Comment by StormyHauk** [comment]
should i make a new post or just write them here?

**Comment by xsellier** [comment]
If you have other suggestions you can create a new post because it is easier for me to track them down.

**Comment by xsellier** [comment]
Points 1 and 3 are implemented.

**Comment by xsellier** [comment]
Point 2: You can now have more than 1 studio working on a single project.
Is it ok to close this ticket?

**Comment by StormyHauk** [comment]
Yeah you can close it
