### ISSUE TITLE
Suggestion: multi-studios, prequel, history hype

### ISSUE THREAD

**Issue by StormyHauk** [binogure-studio/city-game-studio-i18n#255]
Its me again. I have some more ideas that i hope will either make it into the game or at least help you.

1. I want to make games with other game companies like starlink with star fox in it on nintendo switch, but you have to make a contract with them that says profit, who does what and who will get the franchise.

2. I dont know if this is worth it, but what if you could create spinn-offs and prequels. I dont know if this is a feature worth having, but still cool.

3. Since you have mail in the game it wouldnt hurt to get fan mail. People talking about their favourite game, what you can do better and stuff like that.

4. When you check game history it should be like a bar with like how much people want a sequel to that game. If you add spinn-offs and prequels it would be like a sequel with the hype on the bar.

**Comment by xsellier** [comment]
Hey,

1. I wonder, have you tried to trade-publish a game. Normally you can work with a competitor on a game. Maybe I missunderstood you suggestion

2. Definitely! And planned!

3. Definitely! And planned!

4. That is an awesome idea! It might be part of the next update (a major update I mean)

**Comment by StormyHauk** [comment]
I meant more like my game company and ea worked together to make a game like we worked on it together, but when i say it out loud it just sounds dumb.

**Comment by xsellier** [comment]
I was thinking about having several studio working together on a single game. It is going to be available only for AAA games. But doing a AAA will require something like having 200 employees. So you need several studios to make just one.

**Comment by xsellier** [comment]
Everything has been implemented in v1.3.0
