### ISSUE TITLE
Suggestion: Dynamic Consoles

### ISSUE THREAD

**Issue by BrunoCarvalhoPaula** [binogure-studio/city-game-studio-i18n#257]
My suggestion is to have console marketshare and shelf life dynamically determined by the actions of both the player and the competitors. It would be something like this:

Console Marketshare: Console Market Presence (**m<sub>n</sub>**)/Total Market Presence (**M**), or **m<sub>n</sub> / M**, where:

Total Market Presence = sum of all consoles ( **M=Σm<sub>n</sub>**)

Console Market Presence for month would be a factor of: 
1. Console Market presence for the previous month (zero if unreleased) = **m<sub>n-1</sub>**
2. "experimentation factor", which would increase Market presence in newer consoles = **e**
3. "games factor", which would increase Market presence based in the number of games released/ported for it = **a * g**, where **a** = constant and **g** = number of games released/ported this month
4. "competition factor", which would increase or decrease Market presence based on the games for it launched by the player and competitors this month =  **c * (r<sub>x</sub> - 40)**, for each game **x**, where **c** = constant, and **r<sub>x</sub>** = game x's rating 
5. "obsolescence factor", which would decrease Market Presence after a newer generation of consoles have been launched = **o * t**, where **t**= number of months since the first console of the next generation has been launched.

To summarize, **m<sub>n</sub> = m<sub>n-1</sub> + e + a * g + c * Σ(r<sub>x</sub> - 40) - o * t** 

The expected result of this formula is to have Market Presence follow a curve, increasing as the number of games for that console increase and as the player and other competitors release games rated 41+, and decreasing as bad games (rated 39 or less) are launched and as newer consoles are released. This way, the Market Share of each console will fluctuate monthly and reflect the actions of the players and its competitors.

And for Shelf Life, each console would have 3 stats. They would be:

1. Minimum shelf life, or the minimum number of months the console will be in the Market
2. Warning Market share threshold
3. Discontinuation Market share threshold

The console would forcibly remain on the market for the minimum shelf life, then check its Market share monthly. Should the Market share be lower than the "warning" threshold, the player would receive a message saying "company is dissatisfied with console". Should the Market share be lower than the Discontinuation threshold, instead, the player would receive the message "console will be discontinued in X months".

**Comment by BrunoCarvalhoPaula** [comment]
An add-on the the idea (and you could use that for any other subsystems): Use the default values for those variables as the "historical" values, and allow the player to randomize some (or all) values (within a set interval, of course) in Advanced Mode to have a fresh experience to increase replayability.

**Comment by xsellier** [comment]
Thank you for that suggestion because I used something based on your idea.
I kept the historical number for every single platform, however I changed the way the game are sold.
Let me explain, before it was based on the score/amount of fans/marketing/hype. Meaning you could release 100 games on a single platform and be rich.

But now, I tweaked the platforms to count the number of published games by the player/competitors to adjust the sales. Meaning, if you are the first who is releasing a game on a specific platform then you will get rich. However as soon as a competitor releases a game on that platform, your sales are going to drop.

I know, it is not the same implementation as youv'e suggested, and I'm going to implement your suggestions for the current generation of platforms (Nintendo Switch, PS4...).

**Comment by BrunoCarvalhoPaula** [comment]
> I know, it is not the same implementation as youv'e suggested, 

I'm happy to be able to inspire you in order to make the game better. Of course I own no rights of the suggestion, you may use it (or not) as you wish :D

**Comment by xsellier** [comment]
In fact, Im gonna use those formula for the Digital store (to compute how many concurrent player you will get on your own digital store).

- CCU<sub>n</sub>: Concurrent user of the digital store at a given time **n**
- CCU<sub>n(p)</sub>: Concurrent user of the digital store for a given platform **p**
- Cat<sub>pn</sub>: Number of games released on platform **p** _available_ on the digital store
- Cat<sub>p</sub>: Number of games released on platform **p** _unavailable_ on the digital store
- Δp: CCU of the current platform (delta between n and n - 1).
- ΔF: Fanbase of the game owner  (delta between n and n - 1). If a bad game is released on the digital store, then the digital store might have a drop in its userbase.

CCU<sub>n</sub> = Σ(CCU<sub>n(p)</sub>)
CCU<sub>n(p)</sub> = CCU<sub>n(p)-1</sub> + (Cat<sub>n</sub> / Cat<sub>p</sub>) * (Δp(<sub>n</sub> - <sub>n - 1</sub>) + ΔF(<sub>n</sub> - <sub>n - 1</sub>))

And this is how it is going to be implemented:
![image](https://user-images.githubusercontent.com/6616005/65985394-b020ce00-e44f-11e9-938d-5ca731e92051.png)

**Comment by xsellier** [comment]
Since I've implemented this for the digital store (v0.26.0), do you mind if I close this suggestion @BrunoCarvalhoPaula ?

**Comment by BrunoCarvalhoPaula** [comment]
Of course I don't mind :D
