### ISSUE TITLE
Suggestion: Develop games for upcoming consoles

### ISSUE THREAD

**Issue by BrunoCarvalhoPaula** [binogure-studio/city-game-studio-i18n#258]
Can we develop games for consoles after they're announced but  before they are released? Of course, you can't actually Market the game before the console is released, but you could start the game dev process before that, and if you finish the game before the consoled is actually on the Market the game would stay on hold and be released as a launch title.

**Comment by xsellier** [comment]
That is a good idea. I will add some requirement tho.
Like if you release a game on an upcoming console it has to be an exclusive game, you won't be able to port it to other platforms. ~~But you will get an extra _hype bonus_. Something like that.~~

**EDIT**
The way the games are sold have evolved a lot. So releasing a game for an upcoming platform is a game breaker. This feature is going to be implemented, but, it needs to be refined before

**Comment by JRC86** [comment]
Great idea. This could work with console bundled with certain games too. 
Maybe a relationship between your company and console makers. The more games you develop for certain consoles the better your relationship and maybe they will offer you to build a game for an upcoming console ?

**Comment by xsellier** [comment]
Thank you for the suggestion, it's been implemented in v0.31.0
