### ISSUE TITLE
Suggestion: Game Engines 

### ISSUE THREAD

**Issue by Sentryxj** [binogure-studio/city-game-studio-i18n#260]
I don't know if you have this planned or not but I think Engines would be a good addition. 

1. They could add an extra level of depth for game creation.
2. Adds another money generator for a studio through licensing the engine out to other devs
3. Forces decisions on what to have in a game

**Comment by GeneralNW** [comment]
I think this is a great idea

**Comment by PwaPois** [comment]
So do i

**Comment by xsellier** [comment]
Im working on it, hsould be available in v0.28.0

https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-27080504

**Comment by xsellier** [comment]
Implemented :)
