### ISSUE TITLE
Suggestion: R&D

### ISSUE THREAD

**Issue by Balthoraz** [binogure-studio/city-game-studio-i18n#261]
Hello!

I was thinking about the way suggestions are received only releasing games. This is too bad because if you are a big studio, in order to know something regarding a genre you have to do several "bad releases" or do contracts.
So I was thinking about an alternative for big studios. What about a R&D department who research and develop in desktops and provides you with those suggestions?

With that you add a new position in a studio to research all best way combinations.

Of course, you can focus in what part of R&D you will send your budget, focus on a prevision of a new platform? Their strong/weak points? Focus on a genre and get more knowledge? This can open new ways.

PS: I seen someone suggested Game Engines, this R&D can be complemented for Game Engines too!

**Comment by xsellier** [comment]
So basically you spend like 50m in R&D and then you can publish a game that will be an outstanding game.
I'm thinking about having an R&D department that:
- Unlock unique furniture (to boost productivity)
- Help you playtesting a game to know if a game is good before you release it
- Of course, the R&D department will be in charge of developing game engines.

**Comment by Balthoraz** [comment]
I think it have to be more than 50m to research game completely by R&D. Have in mind a outstanding game in late game actually are giving me more than 10 Bs. That should break completely the game then.

I Will keep thinking about how to balance R&D and games…

**Comment by JRC86** [comment]
R&D can be used to research game engine capabilities as well as office furniture etc. 
As for the game engine capabilities, maybe making certain tech require less CPU/GPU points.
R&D can maybe even gain "breakthroughs" for current game being developed, causing devs to output more points for a few minutes. As long as it doesn't break game mechanics of course.

**Comment by soldyne** [comment]
R&D is a great idea.  would certainly add more depth to the game.
would it hurt the balance if R&D could research technologies early?

**Comment by xsellier** [comment]
Closing this ticket in favor of this one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/888
