### ISSUE TITLE
Suggestion: In advanced start add starting money

### ISSUE THREAD

**Issue by WayneFTWGitHUB** [binogure-studio/city-game-studio-i18n#264]
I think you understand from the title. The ability to choose the exact money you want to start within an advanced game.

**Comment by xsellier** [comment]
Easy to implement. And seems to be a good idea

**Comment by WayneFTWGitHUB** [comment]
:)

**Comment by xsellier** [comment]
Implemented in v0.29.0
Im now closing this ticket \o/
