### ISSUE TITLE
Suggestion: Free games | Monetization

### ISSUE THREAD

**Issue by JoshTheDeveloperr** [binogure-studio/city-game-studio-i18n#273]
Add an option to create a free game instead of a paid game, and instead, you can choose to monetize it through ads and in-game purchases.

**Comment by Fozehor** [comment]
**Yes! The best! +1**

**Comment by icls1337** [comment]
Yes! The best! +1

**Comment by xsellier** [comment]
Duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/384
(Im closing this one because the other one has a better description)
