### ISSUE TITLE
[Graphique] Image sceindé en 2

### ISSUE THREAD

**Issue by ArthieuCYD** [binogure-studio/city-game-studio-i18n#29]
Lorsqu'on souhaite changer d'une résolution pleine écran à une résolution de fenêtre sans bordures, on arrive sur le résultat avec le screen en dessous : 
![image](https://user-images.githubusercontent.com/38721859/51412263-471c5300-1b6b-11e9-957f-566d6d7423e9.png)

**Comment by bouboo** [comment]
+1

**Comment by xsellier** [comment]
Ok, c'est facile de changer ça :D
