### ISSUE TITLE
Digital store opened before servers (before year 1996)

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#304]
Oke strange so when looking at the digital store and selecting a platform it opened up the store but i can't place servers yet. So now i got players accessing the store but there is nothing on it and no servers so keep getting te message "this is fine"

**Comment by xsellier** [comment]
Thank you for that report.
I've just fixed it, and Im gonna push the fix later today.

**Comment by xsellier** [comment]
Fixed in v0.26.5
