### ISSUE TITLE
Suggestion: Having the option to expand buildings

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#305]
Would it be possible to have the option to expand a building so it has more room.
So for instance if you buy a small studio you can later add more space.

If not expanding it than rebuilding the building would also be an option. Have it have a higher cost for the demolition of the old building.

**Comment by xsellier** [comment]
Im thinking about it. It is a good idea, and the way to do it, is being able to _destroy_ a building, and then build a brand new one in place. Meaning you will lose all the stuff from that studio in order to build a new one.
Is it what you were thinking?

**Comment by JRC86** [comment]
Hello.
Just office expansion would be nice, demo a building could also be nice as a feature for the game (the city is evolving... ).
But for office expansion you don't want to lose what you already have there.

**Comment by icls1337** [comment]
cool

**Comment by xsellier** [comment]
Not implemented yet, but I'm closing it in favor of #645
