### ISSUE TITLE
Suggestion: Change to server buildings. Or rent server space

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#306]
Have the option to place more than 228 servers in a building.
Could it be possible with the autofurniture option to have more than 228 servers.

As in 2011 i have +/- 750 users for the servers and i have like 18 buildings with 228 servers

Alternative would be to be able to pay a company to rent server capacity.

**Comment by xsellier** [comment]
Hey,

You will be able to pay a company to rent server capacity (cf https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-16895549 ). It is not available yet, but it is going to be implemented with version v0.28.0.

**Comment by xsellier** [comment]
Implemented in version v0.27.0
