### ISSUE TITLE
Suggestion: Convention confort

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#309]
- Could we get an option to set what games we're bringing to conventions in advance?
- Also an option to attend all conventions and set the size of the booth automatically would be good.
- Would also be nice if we could set our own convention to repeat automatically on the same month every year

**Comment by xsellier** [comment]
First 2 points are implemented in v0.27.0-rc1

**Comment by ClassicBiz** [comment]
Conventions should have more of an impact on the hype of games you haven't yet released.
To have an unpublished game shown at the convention would increase its hype or start hype for it.
To put a game out early in a convention could lead to a bad hype score.

**Comment by JRC86** [comment]
I'd like to rent out my convention center.

**Comment by xsellier** [comment]
Renting out a convention center is kind of out of topic, sorry I won't implement that one.

**Comment by xsellier** [comment]
> I'd like to rent out my convention center.

Renting out a convention center is kind of out of topic, sorry I won't implement that one.

**Comment by JRC86** [comment]
Do You have any other plans for convention centers other than what exists right now?

**Comment by xsellier** [comment]
Conventions centers are here to compensate the fact that after year 2020 there is no other conventions.
So I added convention centers but it still misses the auto-organize convention feature.

BTW thank you for all the suggestions you are making, it helps me designing more features.

**Comment by JRC86** [comment]
I understand. 
I think there could some interesting things to add for convention centers.
I'll try to be more descriptive in my suggestions when i have some more :)

**Comment by xsellier** [comment]
Auto-organize convention is implemented in v0.29.0
Im now closing this ticket \o/
