### ISSUE TITLE
Suggestion: Remastered game editions

### ISSUE THREAD

**Issue by Kendoslice13** [binogure-studio/city-game-studio-i18n#310]
It would be nice to be able to make remastered versions of our 'classic'  games (games that are old, have a high review score and sold well)

**Comment by xsellier** [comment]
This suggestion is a really good one, and it shoul be part of thie update:
https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-18020128

**Comment by xsellier** [comment]
Implemented, closing
