### ISSUE TITLE
Suggestion: Porting and Multi-Platform development 

### ISSUE THREAD

**Issue by Kendoslice13** [binogure-studio/city-game-studio-i18n#311]
I know there have been requests for multi-platform development and I have a suggestion how to make it work while keeping porting relevant. Multi-Platform would be unlocked later, maybe when the Gstation and Vbox are released. Until then you port. After, you port any remaining games and just do multiplatform going forward. Porting then becomes about bringing games to platforms they weren't originally made for like how companies are now bringing their old games to mobile platforms. This might require having limits/specs on platforms which Binogure was talking about on discord

**Comment by xsellier** [comment]
This will come with the Custom game engine indeed.

**Comment by xsellier** [comment]
> I know there have been requests for multi-platform development and I have a suggestion how to make it work while keeping porting relevant. Multi-Platform would be unlocked later, maybe when the Gstation and Vbox are released. Until then you port. After, you port any remaining games and just do multiplatform going forward. Porting then becomes about bringing games to platforms they weren't originally made for like how companies are now bringing their old games to mobile platforms. This might require having limits/specs on platforms which Binogure was talking about on discord

For the first part, it will always be possible to port a game onto another platform since the Atari 2600 got a lot of games ported onto several platforms. Nintendo introduced platform exclusivity in 1985, before that date, the games were ported on multiple platforms. So I will keep it that way.
About the second part, porting games is going to evolve once the custom game engines are developped. And indeed, you'll have to think about platforms/game engines compatibility.

**Comment by xsellier** [comment]
> Make multiplatform games be available at launch for multiple different versions alongside adding in a bit of management involving marketing pre-release, as you can do it post-release. I also hope they would add platforms based on the next gen systems coming up as well, alongside the ability to buy up smaller subsidiaries for stuff like ports to be handled by them.

**Comment by xsellier** [comment]
Implemented in v0.31.3
