### ISSUE TITLE
Suggestion:  Korean translation

### ISSUE THREAD

**Issue by Icln** [binogure-studio/city-game-studio-i18n#312]
Hello, I'm a Korean developer. After discovering and playing this project,  I have confirmed that there is no translation in Korean yet. Can I translate it into Korean for the convenience of Koreans who want to enjoy your game like me?

**Comment by xsellier** [comment]
Hello and welcome @kangholim 

I wish I can support more languages (Korean and Japanese for example). So if you want to contribute and to translate it, I will add it to the game asap.

Please tell me if you need anything

**Comment by xsellier** [comment]
Result of your work from within the game:
![image](https://user-images.githubusercontent.com/6616005/68612761-469ed100-048b-11ea-9fa1-19f4e8e0b77c.png)

Should be available later today on the `unstable` steam branch

**Comment by xsellier** [comment]
Implemented in v0.27.0
