### ISSUE TITLE
Suggestion: MMO

### ISSUE THREAD

**Issue by StormyHauk** [binogure-studio/city-game-studio-i18n#315]
**Describe the solution you'd like**
I think that MMOs should be apart of the game becasue not all online games have subcriptions and i think that we should be able to have a WoW type of game that can last for years because of the subcription and microtransactions
**Describe alternatives you've considered**
It would work just like Online games, but instead you choose a mmo option. Then you choose a person that have the servers and all of that. When the game is finished it you choose what price the gaem should be and what price the subcription should be. Dlcs are going to be added in the game so that works like any other games. You could also choose to change the subcription on the game any time you want. Microtransactions is of course something you could choose to have in the game and i dont know if you have any plans for them in the future.
**Additional context**
This is of course only my idea of how it would work. If you or anyone have ideas that would be better or make it better then please share.

**Comment by xsellier** [comment]
I keep it for the next update

**Comment by xsellier** [comment]
Implemented in v0.29.0 (DLC and subscription for online games, you can now make MMOs and publish DLC for them!)
Im now closing this ticket \o/
