### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GeneralNW** [binogure-studio/city-game-studio-i18n#316]
Just wondering after full release will you continue to add new features for the years to come or do you have a plan to start another project? Also, will there be a steam workshop? I believe that would be a great feature for people to add things into the game that you don't want in the base game. Thanks and keep up the great work!

**Comment by xsellier** [comment]
Hey,

So, I have plan to start a new project once City Game Studio is fully implemented. I cant share any details about it yet.

Steam workshop is on the roadmap, so you will have it before it leaves EA.

**Comment by GeneralNW** [comment]
Awesome thanks and keep up the fantastic work!
