### ISSUE TITLE
Bug: Publish game offer 

### ISSUE THREAD

**Issue by singniubi** [binogure-studio/city-game-studio-i18n#327]
在Insane难度下，我发现AI不可能完成对高要求(score min)的任务，同时也可以通过这个缺陷轻易获取赔大量偿金（penality）。这个缺陷导致失去了应有的作用。

Under the difficulty of insane, I found that AI could not complete the task of high score min. at the same time, I could easily obtain a large amount of compensation through this defect.The flaw led to a loss of function.

![新建位图图像](https://user-images.githubusercontent.com/58244656/69709210-f6389c00-1137-11ea-93f7-f8b4124af824.png)

**Comment by xsellier** [comment]
Thank you for that report, it's been fixed. I'm gonna publish in in v0.28.0.

![indie-game-fixed](https://user-images.githubusercontent.com/6616005/69747144-c8416080-1113-11ea-9cb3-7ee784289c82.gif)

**Comment by xsellier** [comment]
v0.28.0 has been released, closing it
