### ISSUE TITLE
Spelling Mistake on Workload page

### ISSUE THREAD

**Issue by DrewYomantas** [binogure-studio/city-game-studio-i18n#33]
On the "Design" page, 'Graphics" is spelled wrong

**Comment by xsellier** [comment]
@BeyondDrewTV I want to confirm that is the issue:
https://github.com/binogure-studio/city-game-studio-i18n/blob/master/languages/en.yml#L268

**Comment by DrewYomantas** [comment]
@xsellier Yep that's it!

**Comment by DrewYomantas** [comment]
I also noticed this spelling error after creating your first game

https://imgur.com/tGetpd5

I can open up a new thread if you would like for this if you would like

**Comment by DrewYomantas** [comment]
https://imgur.com/kWm1Wh6

 Small spacing issue cuts off part of the word

**Comment by xsellier** [comment]
Thank you @BeyondDrewTV . I'm going to publish a new version today, it should fix those issues.

**Comment by DrewYomantas** [comment]
Great! Really enjoying the game so far!
