### ISSUE TITLE
Suggestion: Features I'd like to see

### ISSUE THREAD

**Issue by Kloriuwun** [binogure-studio/city-game-studio-i18n#331]
° A feature similar to that of Mad Game Tycoon, where there are more studios or departments where they take care of "refining" the game, after it is finished. For example, before you release it for sale, throw it for more consoles, add more content to it, create scenes, improve sounds, fix bugs, etc.

° The ability to create an R&amp;D studio where you can create table consoles or portable consoles. Research ingesting new pieces of hardware or innovating in the market, where competitors have to ask you for a license

° Be able to buy IP's from other companies or co-create with another company. Being able to buy competing companies while keeping the staff and projects that were being created (it may be a lot to ask and I don't know how much work it costs)

**Comment by xsellier** [comment]
1. I'm glad you are asking for that feature. It is planned for v0.29.0. You can check it out: https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-18020128
2. See this ticket: https://github.com/binogure-studio/city-game-studio-i18n/issues/226
3. You can already create game with other companies, when you do a trade-publishing game or where you publish a game offer. About buying companies' IPs, there is another feature for that one: https://github.com/binogure-studio/city-game-studio-i18n/issues/78

I'm gonna close this ticket for duplicate.
