### ISSUE TITLE
Suggestion: Making a Prequel

### ISSUE THREAD

**Issue by WayneLegolas** [binogure-studio/city-game-studio-i18n#335]
It would be cool if you could make a prequel just like you make a sequel. If you make a prequel it will make MUCH hype when you reveal it and your franchise will have better ratings in general. This includes another suggestion I think I have already seen that you make a gaming franchise.

**Comment by xsellier** [comment]
Nice suggestion however it has already been suggested here (point 2):
https://github.com/binogure-studio/city-game-studio-i18n/issues/255

Im closing this one.
