### ISSUE TITLE
Suggestion: Digital Store Feature

### ISSUE THREAD

**Issue by WayneLegolas** [binogure-studio/city-game-studio-i18n#336]
Maybe this is too much to ask for but it would be cool when you make a new feature for your Digital Store it is kind of like when you make a game like first Design - Development - Polish. And you can customize that feature with some things that are like choices so you could make that feature work a little worse or better. (With that I mean like hype and such things). Kind of like when you make a game with a game engine.

**Comment by xsellier** [comment]
I like the idea, however I'm afraid that players won't enjoy having a non-balanced store.
May you ellaborate please.
- What does it bring to the gameplay?
- What does it cost to the player?
- What do you want to have this feature?

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
