### ISSUE TITLE
Bug: Producers, Accountants and Marketing managers stay busy.

### ISSUE THREAD

**Issue by shaiikhafzal** [binogure-studio/city-game-studio-i18n#338]
Producers, Accountants and Marketing managers stay busy when I cancel a game or when the game gets off the market.

**Comment by xsellier** [comment]
Thank you for that report, I'm gonna have to check this.

**Comment by xsellier** [comment]
I cannot reproduce it

1. Cannot reproduce it by canceling an already released game (it is the same script that cancel a released game that remove a game from the market)
![cannot-reproduce-it](https://user-images.githubusercontent.com/6616005/71484008-47d85300-27d8-11ea-8e76-875f427fe696.gif)

2. Cannot reproduce it by canceling an in-dev game
![cannot-reproduce-it-2](https://user-images.githubusercontent.com/6616005/71484090-9d146480-27d8-11ea-9a66-8bb774776b2c.gif)

**Comment by xsellier** [comment]
Regarding this issue, I'm gonna add a way to attach/detach specialists from already released games (see: https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-30704942)
