### ISSUE TITLE
Suggestion: Show studio that producer is in when assigning to game

### ISSUE THREAD

**Issue by engineer-pearl** [binogure-studio/city-game-studio-i18n#341]
**Is your feature request related to a problem? Please describe.**
I'm trying to have multiple game studios churning out multiple games at a time, which means needing producers for each game. I manage this by keeping a producer in each studio, in case they are automatically assigned to contracts assigned to studios. Because there is nothing preventing producers from working on games not in their studio, it is easy to assign the wrong producer to work on a game, which can be a problem if producers are used for contracts.

**Describe the solution you'd like**
It would help if I could see which studio a producer is located in when assigning them to a game.

**Comment by xsellier** [comment]
Thank you for that suggestion. I've just implemented it, it should be available with v0.28.1
![image](https://user-images.githubusercontent.com/6616005/71740350-f9efca80-2e29-11ea-90e3-d41606148d6d.png)

**Comment by xsellier** [comment]
Implemented with v0.28.1
