### ISSUE TITLE
Suggestion: Gangster and Noire topics

### ISSUE THREAD

**Issue by ColeT2014** [binogure-studio/city-game-studio-i18n#345]
Could we possibly please get two new topics:

**"GANGSTER"** - for games such as GTA (Action Shooter etc)
**"NOIRE"** - for games inspired by Max Payne or LA Noire, working well with Adventure and Action Shooter.

Thank you :)

**Comment by xsellier** [comment]
Fixed in v0.28.1

**Comment by xsellier** [comment]
Created a dedicated issue for themes:
https://github.com/binogure-studio/city-game-studio-i18n/issues/388
