### ISSUE TITLE
Bug: Puzzle Genre unlocked before Classic Puzzle Genre

### ISSUE THREAD

**Issue by soldyne** [binogure-studio/city-game-studio-i18n#346]
**Describe the bug**
When starting a new game and selecting "Puzzle" as the studio specialization it will unlock the "Puzzle" Genre (as expected) but, when the Genre Research tree is unlocked (after 6 games) the Puzzle Genre is a second tier genre and is not in the ring of first tier genres.  Classic Puzzle is in the ring of first tier genres and is not unlocked from the start as one might expect.

**To Reproduce**
Start a new game with Puzzle as the specialization.
Publish 6 games to unlock genre research.

**Expected behavior**
either "Puzzle" needs to be in the first tier of genres and "Classic Puzzle" should be in second tier, or "Classic Puzzle" needs to be available from the start as the chosen specialization, not "Puzzle".

**Logs**
Attach log files to this ticket:
[citygamestudio-0.log](https://github.com/binogure-studio/city-game-studio-i18n/files/4026461/citygamestudio-0.log)

**Screenshots**
![20200106091357_1](https://user-images.githubusercontent.com/59415468/71824460-90f59600-3067-11ea-9bd7-36b5da534b52.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
none to add

**Comment by xsellier** [comment]
Woopsie. thank you for that report.
I've just fixed it, should be out with v0.28.1

**Comment by xsellier** [comment]
Fixed in v0.28.1
