### ISSUE TITLE
Develop Game console

### ISSUE THREAD

**Issue by ramy-tawfik** [binogure-studio/city-game-studio-i18n#349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xsellier** [comment]
Hey,

About the custom consoles, there is another suggestion:
https://github.com/binogure-studio/city-game-studio-i18n/issues/226

That's an outstanding template you sent there.
Closing this one for duplicate.
