### ISSUE TITLE
Problem mise a niveau des ordinateurs 

### ISSUE THREAD

**Issue by bouboo** [binogure-studio/city-game-studio-i18n#35]
Bonjour lorsque j'appuie sur le bouton pour améliorer les ordinateurs (ou en acheter quand j'ai mis de nouveau bureau) je ne peux appuyer qu'une seul fois sur le bouton et je suis obligé de fermer le menu et le réouvrire pour pouvoir appuyer une nouvelle fois sur le bouton, bisous.

**Comment by bouboo** [comment]
PS: je parle de ces bouton https://i.imgur.com/76dltnr.png

**Comment by xsellier** [comment]
@bouboo Jolie trouvaille :dancer:

**Comment by xsellier** [comment]
Si tu cliques sur "Toute la compagnie", ça améliore les PC pour tous tes studios. Donc il te sera impossible de continuer a upgrader les ordinateurs, puisque tu as déjà mis les ordinateurs a jour

Si tu cliques sur "Ce studio", ça améliore les PC que pour ce studio. Donc tu ne pourras plus clicker sur le bouton a nouveau.

De nouveaux ordinateurs sortent, donc i lfaudra revenir sur ce panneu de temps en temps pour pouvoir mettre a jours les PC.

Maintenant je ne suis pas sûr que ce soit un bug

**Comment by bouboo** [comment]
@xsellier Alors oui mais par exemple si tu oublies d’améliorer à la sortie d'un nouvel ordinateur (ce qui étais mon cas) donc que tu dois améliorer 2 fois tu dois appuyer une fois puis fermer et reouvrire le menu et encore une fois appuyé pour améliorer les ordinateurs et donc si tu oublies 4/5 nouvels ordinateurs ça doit-être chiant

**Comment by xsellier** [comment]
1. J'ouvres le panneau
2. Je clique sur upgrade toute la compagnie
3. Ca ameliore une fois
4. Le bouton ne se grise pas mais plus aucun effet quand je clique
5. Je ferme le menu
6. J'ouvre le menu
7. Je clique sur upgrade toute la compagnie et la c'est bon
8. le bouton se grise et c'est fini
