### ISSUE TITLE
Suggestion: Remake & remaster

### ISSUE THREAD

**Issue by StormyHauk** [binogure-studio/city-game-studio-i18n#351]
I would love to make a remake of a game just like Capcom does with Resident evil.

**Comment by xsellier** [comment]
Remake and remaster.

**Comment by Zarys26** [comment]
There's also reboot and spin-off.

**Comment by xsellier** [comment]
> I would love to see a system for these kind of releases being introduced. Here's what I imagine for such system:
> - Remakes would the same work as a brand new game in a franchise.
> - Remasters could be based on the game porting system that already exists; players would be able to focuses on up to three points over a selection of six (graphics, sound, gameplay, extra content, controls, balancing), the points being connected to the game genre (for example, remasters of simulation games would favor improved controls over extra content)
> - Re-releases would allow players to revisit their classic catalog (games released over 20 years ago) and do a cheap release to a single platform for a limited time.

**Comment by xsellier** [comment]
Implemented in v1.3.0
