### ISSUE TITLE
[FR] Texte Early Access Steam

### ISSUE THREAD

**Issue by kiriflo** [binogure-studio/city-game-studio-i18n#355]
**Voilà, j'ai corrigé quelques petites erreurs et j'ai fait quelques modifications mais rien d'extravagant.** 

**Pourquoi l'accès anticipé ?**

“Les idées de features venant de la communauté affluent. C'est encourageant et en même temps difficile à suivre. Je suis l'unique développeur de City Game Studio et implémenter toutes ces fonctionnalités me prend beaucoup de temps. Avec l’avancement du projet, les retours sont de plus en plus précieux. Pouvoir sortir le jeu en accès anticipé va me permettre d'avoir des retours plus tôt et va également me permettre de me consacrer à 100% au développement de City Game Studio.” 

**Pendant environ combien de temps ce jeu sera-t-il en accès anticipé ?**

“City Game Studio restera en accès anticipé jusqu'en automne 2020. Ceci me permettra d'en faire le meilleur jeu possible.” 

**En quoi la version finale prévoit d'être différente de la version en accès anticipé ?**

“J'ai mis en place un projet GitHub listant les fonctionnalités qu'il me reste à implémenter. Évidemment, la liste des features est amenée à évoluer avec le temps :
•	Soldes sur les jeux
•	Workshop de Steam
” 

**Quel est l'état actuel de la version en accès anticipé ?**

“Le jeu possède actuellement une bonne durée de vie et beaucoup de fonctionnalités. Il manque cependant du contenu, contenu qui va être ajouté durant l’early access.
Toutes les fonctionnalités listées dans la section "A propos de ceci" sont déjà implémentées” 

**Le jeu sera-t-il tarifé différemment pendant et après l'accès anticipé ?**

“A mesure que le développement du jeu avance, le coût de développement augmente. C'est pourquoi le prix du jeu est diminué pour l’early access.” 

**Comment comptez-vous impliquer la communauté dans le processus de développement ?**

“J'attends beaucoup de la communauté. Un serveur discord actif est en place, n'hésitez pas à le rejoindre. Nous y partageons nos avis sur City Game Studio ainsi que les idées de features, les retours de bugs et le balancing du jeu. 
Développant le jeu sur Linux, je ne peux pas streamer directement sur Steam. J'ai donc construit une communauté autour des retransmissions sur Twitch. Venez-vous présenter, je suis toujours content de voir de nouvelles têtes.”

**Comment by xsellier** [comment]
Merci énormément, je remplace le texte de ce pas

**Comment by kiriflo** [comment]
Il y a un j' qui n'est pas apparu sur la page Steam dans la section "En quoi la version finale prévoit d'être différente de la version en accès anticipé ?" Ça fait un peu tâche ^^"

**Comment by xsellier** [comment]
Encore merci, cette petite erreur a été corrigée :+1:

**Comment by kiriflo** [comment]
Nickel ! Je clos le ticket, je vais voir s'il y a d'autres sections qui peuvent êtres améliorées.
