### ISSUE TITLE
[FR] Suggestion : Interview/Convention

### ISSUE THREAD

**Issue by kiriflo** [binogure-studio/city-game-studio-i18n#358]
Je t'écris l'idée en français, ça sera plus facile pour moi et je pense que tu comprends la langue de Molière sans problème. Dans le cas contraire, je te ferais le message en anglais 👍 

Je pense que pour te différencier des autres jeux du même type que City Game Studio, il serait important de développer la partie des interview par les journalistes et tout le système qui entoure les annonces via les conventions (Je peux prendre l'exemple de l'E3) : 

- Recevoir des demandes d'interview pour un projet en développement et choisir d'en parler librement ou de noyer un peu le poisson pour garder le suspens. Le choix des réponses pourrait directement impacter la barre de hype que va générer la sortie du jeu

- C'est un peu dévié du sujet principal mais le développement d'une feature sur un community manager serait pas mal également. Comment le personnel responsable de la communication envers les joueurs doit se comporter vis à vis de la sortie d'un jeu. S'il fait une boulette, la hype diminue. Au contraire, s'il fait un job de qualité, le jeu prend tout de suite de la valeur... C'est assez vague, dis moi si tu vois où je veux en venir.

- Pour les conventions, je pense qu'une petite feature d'animation montrant une scène où un présentateur (le joueur donc) se montre devant une foule de spectateur en folie pour annoncer un projet sur lequel le studio de développement bosse (en gros, faire un truc du genre "A World Premiere". Ça donnerait très clairement un énorme plus à la feature des conventions et celle-ci servirait à autres choses que de gagner des abonnés.

Voilà en gros les idées. J'ai pleins d'autres types d'ajouts que je pourrais te détailler mais je pense que tu dois recevoir pas mal de demande de features à implémenter dans le jeu et ta roadmap n'en finirait jamais donc je m'arrête là ^^

J'espère que j'ai été clair ;)

**Comment by xsellier** [comment]
Merci pour la suggestion, je vais la linker avec l'autre suggestion du même genre:
https://github.com/binogure-studio/city-game-studio-i18n/issues/145
