### ISSUE TITLE
Suggestion: Collaborate with multiple studios to create an game

### ISSUE THREAD

**Issue by SkipTheDragon** [binogure-studio/city-game-studio-i18n#360]
A feature that let us combine our studios together and create an better game/or shorten the game development time

Or create an game with other studios 
(Combine multiple studios and then assign which one to take care of Design/Development/Polish)

**Comment by xsellier** [comment]
On the roadmap.
Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/232
