### ISSUE TITLE
Trade IP

### ISSUE THREAD

**Issue by IkhwanKS3** [binogure-studio/city-game-studio-i18n#361]
You can buy and sell IP with other companies. The price of the IP will be based on how successful and the score the IP received in the past 4 years. You will also get a bonus hype if the IP is successful before but get a bad reputation if you cannot deliver enough quality to compete with the use of the IP before.

**Comment by xsellier** [comment]
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/78
