### ISSUE TITLE
Suggestion: DDOS attack

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#377]
With the update of digital stores and improved online games, as well as the release of free games in the future, DDoS attack play method is indispensable, which can increase the playability of the game, and need new occupation: network security personnel, reduce the loss of DDoS attack, and prevent DDoS attack.

**Comment by xsellier** [comment]
Hey,

Thank you for this suggestion. DDoS attacks have been implemented in the v1.5.0.
Closing this.
