### ISSUE TITLE
Suggestion: Another improvement of online games

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#379]
For the network games with unstable branches, there should be no selling price of the game, only the subscription price of the network game should be kept, and the publishing panel of the network game should show the number of online players, the number of increased players, and the number of lost players

**Comment by xsellier** [comment]
1. Selling price can be unchecked. Just click on the checkbox, and the selling price will be 0
2. The network panel  shows the amount of online players if you click on it
3. Not implemented, and it is a good idea.

**Comment by xsellier** [comment]
Thank you for the suggestions, everything has been implemented and is already available!
