### ISSUE TITLE
Suggestion: High frame rate mode

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#381]
With the update of the game, my computer can't run the game smoothly. Can developers develop a high frame rate mode to make the game run more smoothly

**Comment by xsellier** [comment]
Hey,

Please share your computers specifications.
- CPU
- GPU
- Operating System
- Ram capacities
- Screen resolution
- Hard drive (SSD/HDD/Hybrid)

**Comment by xsellier** [comment]
There was a bug in v0.29.0-rc7. It's been fixed in v0.29.0-rc8. It might improve performances overall.

**Comment by xsellier** [comment]
Please tell me if you still have this issue if the v0.29.0 @Th-byte

**Comment by xsellier** [comment]
Closing it, please re-open this ticket if you still have that issue.
