### ISSUE TITLE
Suggestion: Problems in online games

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#382]
I have released a good online game with good evaluation and good network management personnel, but the number of players has not been going up. I have cancelled the selling price of the game, the subscription price of online games is not high, and free updates have been kept, but the number of players has been falling. What's the matter?

**Comment by xsellier** [comment]
Hey,
About game and sales:
- Price of the game matters. If it is too high, then you will sell less
- Subscription price matters matters too (the very same way)
- Running marketing campaigns help you selling your games
- Attending/Organizing conventions help too
- Publishing regular free update
- Making a sale
- Game size matters (retention is higher for AAA games than for Indie games). For an indie game it is 18%, for a AAA game it is 24%.
- Score of the game
- Number of fans (bigger the game is, bigger the fanbase has to be)

If you've done all of these, and you don't make money or if the game does not sell well enough. Then please share your savegame here, and I'm gonna have a look.

**Comment by xsellier** [comment]
There was a bug in the sale computation algorithm.
I've just fixed it.

## Online game
![image](https://user-images.githubusercontent.com/6616005/74857186-52632480-5311-11ea-9a87-2037ea029e2f.png)

## Offline game
![image](https://user-images.githubusercontent.com/6616005/74857148-47a88f80-5311-11ea-9cfe-2dedf883ee22.png)

**Comment by xsellier** [comment]
Thank you for that report.
Fix published in v0.29.0-rc8

**Comment by xsellier** [comment]
Feel free to re-open this issue if it happens again @Th-byte 
Because so far this issue is fixed with v0.29.0
