### ISSUE TITLE
Suggestion: Specific content of free games

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#384]
1. The difference between free games and online games is that the former charges for props, while the latter charges for subscription system (monthly fee / annual fee).

2. Free games use the game ontology update to further improve the quality of the game and the number of players (free games cannot use the paid update). Plus, online games can't use paid updates. Only single game can use free update and paid update (DLC), because the business model of online game and free game is different from that of single game, which is conducive to CGS data balance and greatly improves the playability of the game.

3. Free game business model, pay for props. For example: a free shooting game, players can customize the name of payment items. In this free shooting game, the payment name of props can be made into weapon appearance, there can be multiple custom props payment selection boxes (the income of each selection box is displayed on the game panel), and then pay the price of props (4.99-29.99). The price is freely chosen by the player. The price of each payment box of the props will affect the number of free game players (the evaluation and marketing methods of the game will also affect the number of free players).

4. The game panel shows: the number of free game downloads, the number of existing players, the number of lost players, the number of increased players, and the number of players paying

5. The revenue of free games is settled by days, which is different from that of online games by months

**Comment by xsellier** [comment]
5. it will be computed by month not by day or week in order to be consistent with the rest of the game.

**Comment by xsellier** [comment]
4. The financial tab details
![image](https://user-images.githubusercontent.com/6616005/76023707-a831f200-5ef7-11ea-8ff0-65666b5bb71d.png)

**Comment by xsellier** [comment]
I'm glad to say that feature has been implemented in v0.30.0.
