### ISSUE TITLE
Suggestion: Delay/ Shelve a project

### ISSUE THREAD

**Issue by Strompper** [binogure-studio/city-game-studio-i18n#406]
Let's say you want to make some changes about the game, but you feel like it's not exactly what you had in mind, so you'd like to take a break from the current project and put in on pause while you start thinking about the next or the other one. This could open to ability to work on smth else without sacrificing the current game or restarting some part of it, as well as changing platforms/ publishers/ title.

**Comment by xsellier** [comment]
That is a great suggestion, and Im gonna implement it. However someone else has already suggested it:
https://github.com/binogure-studio/city-game-studio-i18n/issues/406

So I'm closing this ticket, sorry
