### ISSUE TITLE
Suggestion: Auto gen. competition

### ISSUE THREAD

**Issue by Saputo228** [binogure-studio/city-game-studio-i18n#407]
So from my experience buying out all the competition when you start making a lot of money, really kills the game, like it almost is a dead stop and omg the game runs super slow with that many studios lol

Could we maybe have a system that starts making new studio competitions pop up in the mid-2000s for example, have new competitions indie studios start showing up, they are not huge but something. so if you buy out all the comp, you still have some people.

**Comment by xsellier** [comment]
New IT's been implemented with the latest version ie v1.2, not yet on the main steam branch but already available on the untsable Steam branch, Should be released within few days.
