### ISSUE TITLE
Suggestion: optimisations and suggestions

### ISSUE THREAD

**Issue by Hadiudiu** [binogure-studio/city-game-studio-i18n#408]
I bought City Game Studio on February 22, 2019. So far, I have played the game for 2968 hours. I have some suggestions.

* Optimization（I find it hard to play when I had a lot of studios and staff. It's getting slow. CPU utilization 13% , memory usage 25%. My computer is not bad. It's configuration: Intel Core i9-9900K 3.60GHz、64G memory、NVIDIA GeForce RTX 2080 8G、SSD.）

* There is too little content in the game engine. Maybe you can expand the current technology and add the future technology.

* The console will not be updated after 2020. It is boring to play. Maybe improved in v0.31.0？

* The game should be able to start in several game consoles. Now players need to migrate to other consoles one by one. This is so tedious.

* I hope to let players develop and produce game consoles and join the game console industry. This can increase the gameplay and play time of the game.

* I have a lot of studios. It's really annoying for players to operate one by one. Maybe you can add a studio self operation function. Players can set which aspects the studio focuses on. Players can also choose an operation one by one by themselves.

* If I can accept the outsourcing contracts about design or development or polish. Why can't I outsource the design part or development part to another company.

* I think it's OK to rent the server. Because it's not enough to build by myself and slows down the game. You may balance the proportion.

* Now some functions of the digital store are very simple. Maybe you can add the friend system, chat system, voice chat system and store wide discount activities, etc. And games log into the e-store should not be taken off the shelves, like steam. And maybe player‘s e-store can also log in other game consoles. 

* There may be some suggestions that I can't remember for the time being. I'll add suggestions later.

I hope City Game Studio will become more and more perfect. In the future, players can establish their own game empire in the game, including making games, selling games, making consoles, selling consoles, developing game platforms, improving server systems, etc.

**Comment by xsellier** [comment]
I ran several tests and found a way to optimize the game. It might take a couple of weeks to optimize and test everything, but Im gonna publish an update on the _unstable branch_ as soon as the update is available.

For the other suggestions, I have several plans to fix the server loads (for example), but also for porting games to several platforms at once. I think the v0.31.0 will fix most of the issues you encountered

**Comment by xsellier** [comment]
The _unstable_ steam branch has a more optimized version of City Game Studio.

**Comment by xsellier** [comment]
Thank you for those suggestions.

- DONE
- DONE
- DONE
- DONE
- DONE
- DONE You can make games using several studios, so you don't have to manage studios individually
- WON'T FIX - But there's alternative. You can act as a publisher and hire small studios to make games for you.
- DONE
- TODO

Closing this!
