### ISSUE TITLE
Crash en sortie d'application

### ISSUE THREAD

**Issue by NicoMoine** [binogure-studio/city-game-studio-i18n#41]
Quand je quitte le jeu, j'ai un crash systématique.
Je crée une nouvelle partie, et je quitte immédiatement => crash 
Je recharge la partie, je quitte => crash
[CityGameStudio.log](https://github.com/binogure-studio/city-game-studio-i18n/files/2779340/CityGameStudio.log)

**Comment by xsellier** [comment]
Merci @NicoMoine Je corrige ça.
