### ISSUE TITLE
Suggestion: Smartphone platform

### ISSUE THREAD

**Issue by Hadiudiu** [binogure-studio/city-game-studio-i18n#410]
Now more and more game developers are developing mobile games or putting computer games on smartphone platforms. You can log the e-store into the smartphone platform. Players can release games on smartphone platform and transplant Games to mobile platform.

**Comment by xsellier** [comment]
Closing this ticket because of the talk we are having in this one (covering the same feature):
https://github.com/binogure-studio/city-game-studio-i18n/issues/524
