### ISSUE TITLE
Suggestion: Add consoles/Multiplayer/New item to the shop

### ISSUE THREAD

**Issue by Waroxyd** [binogure-studio/city-game-studio-i18n#411]
So for the last 3 days I've just been playing the game, the problem is that I find that the game is over too quickly.

I know it's hard on its own, but why don't you try a few things like:

- **Inventing the next consoles**, to make the games last a little bit longer. Since the game ends in December 2020, why not invent them until 2040 or something like that.

- Are there any plans to **make a multiplayer**? That could bring a plus to the game and set it apart from the competition. Indeed, if you integrate the (real) multiplayer, 2 friends for example can play a game together and try to be stronger than the other.

- Would it be possible to **add elements in the shop**? Such as single office chairs, large meeting tables, to increase the roleplay side of the game as well as the decorative side.

In any case, **the game is very great**! **A big hat for doing it alone**! I hope it will have some surprises in store for us! :) 

Donc, depuis trois jours, je ne fais que jouer au jeu, le problème c'est que je trouve que le jeu se termine trop vite.

Je sais que c'est difficile tout seul, mais pourquoi ne pas essayer quelques trucs comme :

Inventer les prochaines consoles, pour que les parties durent un peu plus longtemps. Puisque le jeu se termine en décembre 2020, pourquoi ne pas les inventer jusqu'en 2040 ou quelque chose comme ça.

Est-il prévu de créer un jeu multijoueur ? Cela pourrait apporter un plus au jeu et le démarquer de la concurrence. En effet, si vous intégrez le (vrai) multijoueur, 2 amis par exemple peuvent jouer ensemble et essayer d'être plus forts que l'autre.

Serait-il possible d'ajouter des éléments dans la boutique ? Comme des chaises de bureau individuelles, de grandes tables de réunion, pour augmenter le côté roleplay du jeu ainsi que le côté décoratif.

En tout cas, le jeu est très bien ! Un grand chapeau de l'avoir fait seul ! J'espère qu'il nous réserve quelques surprises ! :)

Traduit avec www.DeepL.com/Translator (version gratuite)

**Comment by xsellier** [comment]
Thank you for that suggestion.
- **Custom consoles**, [making consoles is planned](https://github.com/binogure-studio/city-game-studio-i18n/issues/403), and [with mod support](https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-17948028) you should be able to add/rename/change everysingle platforms.
- **Multiplayer** it is not part of the plan atm, but there are a lot of [people who are asking](https://github.com/binogure-studio/city-game-studio-i18n/issues/88) for it, so who knows?
- **New items** I might add new items, but you will be able to add new items [via mods](https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-17948028).

Merci pour les messages d'encouragements. Je laisse ce ticket ouvert le temps que la version v0.32.0 soit dispo.

**Comment by 0xAnarz** [comment]
>     * **Multiplayer** it is not part of the plan atm, but there are a lot of [people who are asking](https://github.com/binogure-studio/city-game-studio-i18n/issues/88) for it, so who knows?

I think this is the **best implementation** this game could have among all the other suggestions. As it stands, the content would already allow custom games, it would be great to have **real players as competitors**. I imagine that it is a problem to choose between real time and turn based.. Keeping real time like it is would be nice but maybe that would imply the implementation of a task queue system? At the moment we have to pause right after a task finished to be faster as possible.. It can be efficient if, more, you can vote (with cooldown per player) to change the speed, or even pause, or something like that. If there is a task queue, few players will want to pause.
