### ISSUE TITLE
Suggestion: Evenements de jeu / Gaming events

### ISSUE THREAD

**Issue by Zarys26** [binogure-studio/city-game-studio-i18n#414]
Je propose cette fois de faire des évènements liés aux jeux qu'on créer.
Par exemple je créer un jeu "Tyran Knight", des sociétés externe viendront proposer de créer des :
 

- Figurines
- Arts Books
- Série animé / Film
- CD de musique
etc...

=============================================================
I propose this time to make events related to the games we create.
For example I create a game "Tyran Knight", external companies will come to propose to create :
 

- Figurines
- Arts Books
- Animated series / Film
- Music CD
and so on.

**Comment by xsellier** [comment]
Closing due to duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/399
