### ISSUE TITLE
Suggestion: Set a release date for games

### ISSUE THREAD

**Issue by kingdom77** [binogure-studio/city-game-studio-i18n#419]
Bonsoir, j'aime beaucoup votre jeu mais ce que je n'aime absolument pas c'est que on ne peut pas choisir la date de sortie de nos jeu :'( j'aimerais développer des jeux et les sortires quand je veux comme pour noël mais une fois le développement du jeu fini, il sort automatiquement.
Merci :)

**Comment by Zarys26** [comment]
C'est une idée intéressante de choisir la date de sortie d'un jeu. J'approuve ! ^^

**Comment by kingdom77** [comment]
Franchement c'est LE TRUC que je veux ;) pour sa que je préfère mad game Tycoon à game dev Tycoon, simple mais essentiel pour moi :)

**Comment by kingdom77** [comment]
Ohlala je ne m'étais pas relus, désolé pour les fautes !  

xsellier added the enhancement label avant-hier
merci xsellier !

**Comment by xsellier** [comment]
Thank you for the suggestion, it's been implemented in v0.31.0
