### ISSUE TITLE
Suggestion: Influence platform diffusion with successful games.

### ISSUE THREAD

**Issue by bouc79** [binogure-studio/city-game-studio-i18n#427]
A software company can influence sales of a platform if it produces well-sold games for that platform. If I continue to produce best-selling games for a console that has 0.5% share, this could go up the sales ranking.

**Comment by xsellier** [comment]
This ticket seems to be a duplicated of this other ticket: https://github.com/binogure-studio/city-game-studio-i18n/issues/257
