### ISSUE TITLE
Server overload and suggestions

### ISSUE THREAD

**Issue by Moeg7** [binogure-studio/city-game-studio-i18n#432]
Hi, 
This was the 1st time i reach the servers era. 
More than one thing bugged me:

1- I wasn't able to see the income of each owned game from the store (the income i guess was being merged into one for the current game). A more detailed financial statement is nice.
2- Server overload is a big issue, and renting servers is a big NO NO when you have 2 very successful games, where players can reach 3G and renting for such high player count results in a VERY high cost.

I would suggest giving the servers more power as in to be able to accommodate more players, or add a new server after the year 2008.
3- There is only one upgrade that decreased server load. Maybe add a couple more.

**Comment by xsellier** [comment]
Implemented with v1.1.0
