### ISSUE TITLE
Suggestion: Mixing Genre's

### ISSUE THREAD

**Issue by GeneralNW** [binogure-studio/city-game-studio-i18n#433]
I think it would be a cool idea if we could mix the genres so we can make action adventure games for example and maybe they can have genre matches so if you decide to mix rpg and simulation it might not do as well as the genres don't match.

I just thought about this and I hope I explained it well enough also I had a quick look to see if this had been posted already and I don't think it has. Thanks and keep up the good work!

**Comment by xsellier** [comment]
Hey @GeneralNW 
Thank you for the suggestion, It has already been sent by another user:
https://github.com/binogure-studio/city-game-studio-i18n/issues/202

Im gonna close this one.
