### ISSUE TITLE
Suggestion: Multiple Save games

### ISSUE THREAD

**Issue by ryanbis** [binogure-studio/city-game-studio-i18n#436]
It seems there is only one save game? I can only continue, or start a new game, but I see no way to load older games. I'd like to be able to have multiple different games going at once.

**Comment by ryanbis** [comment]
Sorry, I dont know how I missed the Load Game button in the main menu. 

So I changed the title of this issue to allow for loading a game from within a game.

**Comment by xsellier** [comment]
Hey,

Sorry for the delay, indeed the multiple save is already implemented.
The load button is hidden until you save at least one game.

Im closing this.

**Comment by GeneralNW** [comment]
Alright, thanks anyways!

**Comment by ryanbis** [comment]
What lead me to open this was that I was trying to load a game, when a game was already loaded. There is no load game button while IN a game. You first have to quit to the main menu, THEN load a game, I would like to see a load game button while you are currently in a game (I like to play with a few different saves, and switch between them)
