### ISSUE TITLE
Suggestion: More preset logo's/ Community created logos.

### ISSUE THREAD

**Issue by IGameNoName** [binogure-studio/city-game-studio-i18n#437]

**Comment by xsellier** [comment]
> I'd think it would be cool to have more logo choices to pick from and allowing the community to also add custom logos for everyone else to use. This feature will add 4 new categories when picking a new logo. 1st would be Community created when you click on this it will show 3 other categories which have been approved by the developer. Top rated, Most popular and Recently added.  Not only can you pick more logos but when in-game competitors could also use the community created logos giving the game more variety.

**Comment by xsellier** [comment]
Coming with v1.4
