### ISSUE TITLE
Suggestion: More options for negotiation

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#450]
> I think it would be cool if there were more options for negotiation other than exclusivity contracts, maybe an exclusivity contract for a certain amount of games, a higher amount of money on the cheque or even doing contracts for the company.

**Comment by Saputo228** [comment]
That would be a great idea as well it would make it stand out more, I keep getting stuck in super-long contracts with Nintendo, and by the time other consoles really start to come out, I'm boned.

**Comment by xsellier** [comment]
Implemvent in v0.31.4
