### ISSUE TITLE
Suggestion: Starting in 2000 or 2002 

### ISSUE THREAD

**Issue by Saputo228** [binogure-studio/city-game-studio-i18n#452]
**Is your feature request related to a problem? Please describe.**
I kind of wish I could start in 2002ish when F2P games had just started to really show up and see if I could make a company only making F2P games and see if I can stay afloat.

I think it would be a really fun challenge.

doing this would allow you to expand more on online games, and also allow you to add more function to having an online server system/store.

**Comment by xsellier** [comment]
Implemented in v0.32.0
You can try it out on the unstable steam branch
