### ISSUE TITLE
Suggestion: Sandbox mode/starting with a lot of money should disable achievements

### ISSUE THREAD

**Issue by DerpySnake** [binogure-studio/city-game-studio-i18n#453]
**Is your feature request related to a problem? Please describe.**
Naturally, I like to just sometimes mess around in games and use a few cheats, but sometimes I'm hesitant to do it because even in sandbox or cheating modes, I still get achievements.

**Describe the solution you'd like**
If you start with a massive amount of money or use sandbox mode, achievements should probably be disabled, or maybe even an option to disable them if the former solution isn't wanted?

**Comment by xsellier** [comment]
I get your point, but I won't disable all the achievements. Somes will stay unlockable, thos which are not related to money (even indirectly).
By the way it is already done, Im gonna publish a new RC this afternoon with this change

**Comment by xsellier** [comment]
It is already available with v0.31.3!
