### ISSUE TITLE
Can't release game port

### ISSUE THREAD

**Issue by ryanbis** [binogure-studio/city-game-studio-i18n#458]
**Describe the bug**
Ported a game, and it finished, and shows the Release button, but does nothing when clicked.

**To Reproduce**
Just happened randomly in the middle of a game. This is the first time I've run into this.

**Expected behavior**
The game should get released when you click the release button.

Save file:
[49922448-9020-4080-4060-9ad7ba616b24.zip](https://github.com/binogure-studio/city-game-studio-i18n/files/5046578/49922448-9020-4080-4060-9ad7ba616b24.zip)

**Comment by xsellier** [comment]
Fixed in v0.31.3
