### ISSUE TITLE
Suggestion: Rework staff progression

### ISSUE THREAD

**Issue by rgosik** [binogure-studio/city-game-studio-i18n#460]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when, my staff reach the limit of their potential and I have to fire the ones I have worked with from the begining because they cant progress any further. Hiring anybody that is not maxed on potential in at least 2 fields feels very unsatisfying

**Describe the solution you'd like**
Replace the limit for Design, Development and Polish with the modifier of how fast stuff progresses in each of those 3 fields, for example for a design worker, x1 Design, x0.8 Development, 0.2 Polish, or smth like this, u could balance the numbers better I guess

**Additional context**
This would in my opinion allow players to stay with their original staff and it can be balanced, by them having for example lower modifiers, like x0.8, x0.5, x0.2 etc. It would also bring more depth to decision making while hiring, asking yourself if you want somebody skilled now, or somebody that will learn fast, but most importantly, eliminate this horrible feeling of "Even tho I am developing games and this staff worked great soo far, I now need to fire some of them, cause they will NEVER be even slightly better" cause they would still progress even if it is little. It would kill the feeling of 0% progress, by it being even as low as 1% progress, the feeling would be much different.
I also think it still would allow current system to exist within it, by for example smb having a Polsih multiplier of x0.05, it is as good as 0% progress xd

My glorious visualization:

![Adnotacja 2020-08-13 175227](https://user-images.githubusercontent.com/16776617/90157508-1a074500-dd8e-11ea-97d0-60e3fd075dea.png)

**Comment by xsellier** [comment]
This is an interesting suggestion, but I though it would be better if we can have universities to train our staff. At least one university per map, and each would have their specialty. I can ellaborate because I haven't started working on it.

**Comment by xsellier** [comment]
Regarding that specific suggestion, unversities and training have been implemented lately. It allows you to max out your staff. It is another way to implement that suggestion.
