### ISSUE TITLE
Suggestion: Stop using github

### ISSUE THREAD

**Issue by TheOnlyGaming90** [binogure-studio/city-game-studio-i18n#466]
**Is your feature request related to a problem? Please describe.**
Github is a stupid website that you have to sign up for AND verify your email, if you didn't use github you would get more feature requests therefore you would have a better game.

**Describe the solution you'd like**
Use a different thingy for suggestions

**Describe alternatives you've considered**
You can use discord instead. Like the actual #suggestions channel

**Additional context**
Don't have any.

**Comment by xsellier** [comment]
I'm using github because I want to track down all the suggestions made, and also because github has the following features:
- Flag a suggestion as a bug
- Flag a suggestion as duplicated
- Add screenshot to the suggestion
- List all closed/opened suggestions
- Filter suggestions by type
