### ISSUE TITLE
Suggestion: Genre or theme about wrestling

### ISSUE THREAD

**Issue by DioManquicio** [binogure-studio/city-game-studio-i18n#469]
Google translator:
I just started to think that I could not create a wrestling game, either a simulator and a theme of that or that a simulator sub-branch is specifically about wrestling

**Comment by xsellier** [comment]
Linking this suggestion to the theme suggestion ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/388

And Im closing this one.
