### ISSUE TITLE
Suggestion: Publisher/Buy license/Offers/Suggar Daddys XD

### ISSUE THREAD

**Issue by DioManquicio** [binogure-studio/city-game-studio-i18n#476]
Hello first of all, these suggestions were made with google translator, yes, I hope that google has translated correctly from Spanish to English. Second, thank you very much for making an effort and taking into account our suggestions when creating the game, especially being one person and knowing what an effort it should be, having to develop code, concept art, etc. So now yes, here are my 4 suggestions.

1.- Could you implement more options as a publisher when you have your digital store? something to if like receiving an offer from a small developer where if you want to risk, put money so that the size of the game is big or AAA and see if it was a good investment. Also buy a company and have the option that it is independent, and create games with an IP that you are not interested in working anymore and tell it in which platform it will exclusively work (such as psp and nintendo ds) or simply choose the ones that have the highest profit in the market.

2.- Buy a movie license, an IP from another game (make a spin off, let's say from another Javier Bross company), books, etc. Where you could buy the license for "x" time and then if you want to pay the license again.

3.- Offers from console developers, let's say your company is good at creating first-person shooter games, Microsoft is interested and pays you to create an exclusive IP for them of that genre.

4.- I continue with the previous point, because not an option like startup company does, where you can be a team affiliated with a company (nintendo for example), where they will finance the games but obviously with disadvantages where, nintente could keep a large amount of Gambling money, games only on their platform, I would limit you to what type of game to play, such as repeating the same genre causing displeasure within the development team, suddenly canceling a project or sequel if it does not meet market trends, etc. Obviously also have an option to pay or another way to separate from such company and whether to have independence or start without being affiliated with one. Also that if you started without any affiliated company or after you have already separated from one, that later if you take relevance, that you receive offers from sony, microsfot or nintendo with different contract proposals, that if one would be left with less profit, freedom to create games, etc.

PD: Greetings and good luck from Mexico :D

**Comment by xsellier** [comment]
Hey,

Thank you for that suggestion.
Im gonna link it with the other one which talk about the same topic:
https://github.com/binogure-studio/city-game-studio-i18n/issues/97
https://github.com/binogure-studio/city-game-studio-i18n/issues/403

And close this one since it is a duplicate.
But no owrries, Im gonna keep the link between the two tickes so nothing is lost here.

**Comment by DioManquicio** [comment]
> Hey,
> 
> Thank you for that suggestion.
> Im gonna link it with the other one which talk about the same topic:
> #97
> #403
> 
> And close this one since it is a duplicate.
> But no owrries, Im gonna keep the link between the two tickes so nothing is lost here.

Ok Thank You nwn
