### ISSUE TITLE
Suggestion: Option to edit SaveGame

### ISSUE THREAD

**Issue by LPTR-Pieter** [binogure-studio/city-game-studio-i18n#478]
**Is your feature request related to a problem? Please describe.**
Sometimes i just like to give my company just a bit more money xD Or changing the name. Stuff like that.
I know the save file is encrypted right now, but it would be much nicer to be able to edit it.

**Describe the solution you'd like**
Decrypted Save file, Or some cheating menu for the soon coming Workshop page.

**Describe alternatives you've considered**
Cheat engine. Doesn`t work though, it changes the values back to the original.

**Additional context**

**Comment by xsellier** [comment]
When launching the game, you can press F1 or F5 to start cheating :)
Clsoing this since it's been implemented.
