### ISSUE TITLE
Minor English spelling error

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#48]
LABEL_CONVENTION_PARTICIPATE: >
    You game catalog is worth being seen, participate in conventions may help you improve your visibility.

Should be

  LABEL_CONVENTION_PARTICIPATE: >
    Your game catalog is worth being seen, participate in conventions may help you improve your visibility.

**Comment by xsellier** [comment]
Thank you @koenderey <3
