### ISSUE TITLE
Suggestion: Console Systems and Development for Pre-Consoles

### ISSUE THREAD

**Issue by daniilkas12345** [binogure-studio/city-game-studio-i18n#483]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when there is no system for creating consoles, as well as there is no system for creating games in advance for new consoles that are being developed.

**Describe the solution you'd like**
A clear and concise description of what you want to happen:
- Systems that will allow you to create consoles and develop games for new consoles being developed

**Describe alternatives you've considered**
- No

**Additional context**
- No

**Comment by daniilkas12345** [comment]
If I wrote something wrong, I'm sorry, I know English very badly, I am Russian.

**Comment by GeneralNW** [comment]
I'm pretty sure this stuff has already been suggested but still it's a good idea!

**Comment by xsellier** [comment]
Hello,

thank you for those suggestions!

> no system for creating games in advance for new consoles that are being developed
This is already implemented. You can develop games for upcoming consoles.

> no system for creating consoles
This has already been suggested.

I'm closing this issue and linking it with the create platform one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/403

Regards
