### ISSUE TITLE
Suggestion: MOD Platforms - Treat unlisted/uncoded genres as "poor" match for easier/faster modding/testing

### ISSUE THREAD

**Issue by nekomaster** [binogure-studio/city-game-studio-i18n#486]
I think the title should describe the idea for the most part but heres a bit more to fill out the idea

Theres 63 genres to deal with and for the most part I just want to test out some stuff quickly and its a slight pain in the butt to have to think about all the genres a platform can match up with.

Might just be a better idea that instead of setting stuff by hand as "POOR" match for a platform, just set it up so taht any genres not included in the code are treated as a poor match.

Example, if I don't include Simulation as a Excellent, good or OK match, or the code/genre at all, I should jsut be able to load the mod and the game should treat it as a "poor match".

HOPEFULLY my explination is understandable.

**Comment by xsellier** [comment]
Just updated the validation, so now when you try to load a mod, if it misses a genre, it will show you a list:
![image](https://user-images.githubusercontent.com/6616005/98219580-7cb34b80-1f4d-11eb-908a-c91871e6de43.png)

**Comment by xsellier** [comment]
Im closing this one since now the mod validation catches those errors.
