### ISSUE TITLE
Suggestion: Discount changes

### ISSUE THREAD

**Issue by TheOnlyGaming90** [binogure-studio/city-game-studio-i18n#487]
Make it so that doing a discount improves sales and income. (Not just the fans)

**Comment by xsellier** [comment]
It impacts both already.

**Comment by TheOnlyGaming90** [comment]
does it **increase** **sales and income?**

**Comment by xsellier** [comment]
Yes it does,
The more you keep your game on sale, the less it is efficient.

**Comment by TheOnlyGaming90** [comment]
what do u mean it is less efficient?

**Comment by xsellier** [comment]
For example.
Game 1:
- 05 / 1998: Sale: **25%**, fanbase/income bonus **+50%**
- 08 / 1998: Sale: **25%**, fanbase/income bonus **+25%**
- 11 / 1998: Sale: **25%**, fanbase/income bonus **+13%**

Game 2:
- 05 / 1998: Sale: **25%**, fanbase/income bonus **+50%**
- 01 / 1999: Game update
- 05 / 1999: Sale: **25%**, fanbase/income bonus **+50%**
- 01 / 2000: Game update
- 05 / 2000: Sale: **25%**, fanbase/income bonus **+50%**

**Comment by TheOnlyGaming90** [comment]
thx

**Comment by TheOnlyGaming90** [comment]
do u rememebr me?

**Comment by xsellier** [comment]
I do.

**Comment by TheOnlyGaming90** [comment]
i miss you
