### ISSUE TITLE
[mod] Validation error

### ISSUE THREAD

**Issue by TheOnlyGaming90** [binogure-studio/city-game-studio-i18n#489]
Creating a mod and i get this error

[create_data_validation_failed] File "C:/Users/jgdug/Downloads/mods/mod.json" is not a valid mod (code: 16

**Comment by xsellier** [comment]
Not a suggestion or a bug.

On the mod validation output, the last tells you which file is invalid and the line above whats the problem.

_By the way, you have been unbanned from the discord server_
