### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#49]
LABEL_FURNITURES_SERVERS_BUY: >
    More desk, more chair, more computer, more white board, more more!

Shouldn't it be
LABEL_FURNITURES_SERVERS_BUY: >
    More desks, more chairs, more computers, more white boards, more more!

As in multiple? or was it meant to be single items?

**Comment by xsellier** [comment]
@koenderey Thank you. I've just fixed it!
