### ISSUE TITLE
Change 9th gen consoles marketshare

### ISSUE THREAD

**Issue by TheOnlyGaming90** [binogure-studio/city-game-studio-i18n#490]
When the PS5 and Xbox Series X are actually out, can you update the marketshare to the real ones? Also update it AGAIN (for a 2nd time) after christmas because we both know that is when people buy the most consoles.

**Comment by xsellier** [comment]
Already done in the latest version.
https://store.steampowered.com/newshub/app/726840/view/2935745853101060105

Closing this issue.
