### ISSUE TITLE
Exclusives change marketshare

### ISSUE THREAD

**Issue by TheOnlyGaming90** [binogure-studio/city-game-studio-i18n#492]
Please make it that so if we make exclusive games for consoles; it changes the marketshare of that console to make it higher depending on how good our game is, and if it's not good enough then it does not change the marketshare at all.

**Comment by xsellier** [comment]
This has already been discussed before ( https://github.com/binogure-studio/city-game-studio-i18n/issues/257 ) . The digital store is there for that.
Once the custom platform are going to get implemented, you will see something like that happening.

**Comment by TheOnlyGaming90** [comment]
dont get what u mean
