### ISSUE TITLE
the most annoying bug ever

### ISSUE THREAD

**Issue by TheOnlyGaming90** [binogure-studio/city-game-studio-i18n#494]
Im making a game and the game constantly keeps on automatically switching to the "Which game genres the selected studio likes" bar on the sidebar and its so annoying when im trying to look at my sales. https://prnt.sc/vi95nl

**Comment by xsellier** [comment]
Not a bug but a feature this bar shows you that your studios are bored of making the same genre.
You'd better start making games with a new game genre.
