### ISSUE TITLE
Suggestion:discount menu, etc.

### ISSUE THREAD

**Issue by XHFlamer** [binogure-studio/city-game-studio-i18n#498]
- A separate menu for discounts and game updates :)
- The ability to give several tasks for 1 studio for the future (for example, update all games, etc.)
- Drawing up a plan with which studios will develop games automatically. And we'll just sit and swim in the moneyXD
- More interaction with competitors pliz

**Comment by xsellier** [comment]
- I think this has been done. You can discount and update games
- You can queue game ports, but not game creation.
- This is merely a description for such feature. If you it added to City Game Studio, please open a dedicated ticket for it.
- Oh, new interactions have been added! I hope you'll like them!
