### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#50]
LABEL_FURNITURES_SERVERS_BUY_DESCRIPTION_0: >
    Buy servers will allow you to create online games but also an online portal.

 LABEL_FURNITURES_SERVERS_BUY_DESCRIPTION_0: >
    Buying servers will allow you to create online games but also an online portal.

------------------------------------------------------------
LABEL_GAMEEDITION_SUBMIT_DESCRIPTION_0: >
    You can make offers from publishers, it brings you a lot of money but beware of bad marks.

LABEL_GAMEEDITION_SUBMIT_DESCRIPTION_0: >
    You can make offers from publishers, it brings you a lot of money but beware of bad remarks.

Not sure about this one. But i think remark fits better.

----------------------------

  TOOLTIP_BUILDMOD: Peint and beautify your office

  TOOLTIP_BUILDMOD: Paint and beautify your office

**Comment by xsellier** [comment]
@koenderey Thank you again <3
