### ISSUE TITLE
Bug: difficulty 'wage' modifier not works in unstable branch

### ISSUE THREAD

**Issue by AzelyFox** [binogure-studio/city-game-studio-i18n#522]
**Describe the bug**
Hi, Im using unstable branch,
with my own mod which adds new 'difficulty'.
But in unstable branch, the 'wage' modifier seems not working properly.
In stable branch with my mod(wage=0.01), my employees were happy when i set my company's wage increment 1~2%.
But in unstable branch, they are not happy with that amount, they only happy when wage increment is higher than 16%.
Thank you.

**To Reproduce**
1. use custom difficulty mod (I use [my own difficulty mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2347610138&searchtext=) which makes **'wage' modifier to 0.01**)
2. In stable branch, it works well. employees are happy with 2% wage increment setting.
3. But in unstable branch, they are unhappy with 2% increment setting. higher than 16% wage increment only makes them happy.

**Expected behavior**
Employees are happy with custom difficulty 'wage' modifier.

**Logs**
none.

**Screenshots**
![image](https://user-images.githubusercontent.com/8467374/104015176-97c56480-51f7-11eb-9fd8-9478415695b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v0.34.0-rc16

**Additional context**
I did bug-report with ingame bug report feature.

**Comment by AzelyFox** [comment]
It seems happening only when i load existing savegame.
When i start new game with my mod in unstable branch, the 'wage' modifier seems working fine.

**Comment by xsellier** [comment]
Hey,

Thank you for that report.
I fixed the issue and added a new check. It will be published with v0.34.0-rc17.
