### ISSUE TITLE
Suggestion: Events appear in a pop-up window

### ISSUE THREAD

**Issue by beahlbsmf** [binogure-studio/city-game-studio-i18n#523]
Hello,
I suggest this feature because we (players) recieve so much mails that when we recieve a Event mail, it often gets lost in the ton of emails.

The solution of this will be to make appear events messages with a pop-up just like as conventions used to do before.
I hope it will be possible to make this pop-up appear for randoms and planned events.

I had a discussion with someone who was a bit afraid that the pop-up appear regulary because of randoms events. I am not because I think the probability of randoms events is too low to make that happen but if you think like him, the solution is to keep randoms events in the mailbox but make appear planned events by pop-up.

Thanks for your time :)

**Comment by xsellier** [comment]
Hey,

Thank you for that suggesiton, and I'm glad because it is already implemented (unstable Steam branch).
