### ISSUE TITLE
Stuck at morgage

### ISSUE THREAD

**Issue by quancore** [binogure-studio/city-game-studio-i18n#527]
I have stuck this panel, I could not do anything. What should I do?

**Comment by xsellier** [comment]
If you are stuck on this panel it means you need to borrow money.
To do that, select  the amount of money you want to borrow, the duration then click on Apply.

![how-to-mortgage](https://user-images.githubusercontent.com/6616005/106274845-3102fc00-6235-11eb-9170-582536960090.gif)
