### ISSUE TITLE
Suggestion: Independent Studios

### ISSUE THREAD

**Issue by TheLazyRuler** [binogure-studio/city-game-studio-i18n#528]
Right now you can only buy a whole competitor. But I would love to be able to just buy a single studio.
for example like EA aquired Respawn. So my suggestion is that after a while independent studios rise up on the city map,
and you could aquire them in the competitor tab under a new menu. The aqusition progress should be the same as
for the console manufactures, but just with money you have to pay now.
![city request](https://user-images.githubusercontent.com/78491581/106767530-3ef0bc80-663b-11eb-95c3-056b6bfe8bda.jpg)

**Comment by xsellier** [comment]
Thank you for that suggestion, it's already been suggested.
Closing this one for:
https://github.com/binogure-studio/city-game-studio-i18n/issues/409
