### ISSUE TITLE
Bug: Renaming building doesn't work the first time

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#532]
When renaming buildings from the building management window in the bottom left-hand side of the screen, after typing the name and hitting 'Enter' or clicking away from the box, the name sometimes does not update and requires a second, or even third try, to update correctly

Related Steam post:
https://steamcommunity.com/app/726840/discussions/2/3114771735685243612/

**Comment by proxyspride** [comment]
Awesome, this will be very handy, as I am a heckler for naming each of my buildings for easier assigning of tasks for specific teams.

**Comment by xsellier** [comment]
hey,

Long time no see, fixed in the v1.11.0
