### ISSUE TITLE
Suggestion: Show Donation Amount When Being Asked to Make a Donation

### ISSUE THREAD

**Issue by proxyspride** [binogure-studio/city-game-studio-i18n#536]
**Is your feature request related to a problem? Please describe.**
I just started a new game on a harder difficulty with a larger map, things were going really well and I was profitable from the start. Until I was asked to make a donation.. Thinking I could afford whatever it was, I accepted.. And immediately got a game over. I had more money than when you start, and I hadn't even progressed 7 months into the game when this happened. So my main question is: How much are the donations, and are they based on your current wealth, current year, or what?

**Describe the solution you'd like**
I would like to see the amount I am being asked to donate before I accept or decline, so that way I at least know what I'm working with.

**Describe alternatives you've considered**
Having the donation amount be based on a percentage of your wealth.

**Additional context**
As I mentioned in the problem section, I was only 7 months into the game, and had about 500k in cash, one location, and three employees. Playing on 'Engine Developer' difficulty, and on a huge-size map.

**Comment by xsellier** [comment]
I think it comes from a mod, I don't remember a donation notification made from vanilla-CGS.

**Comment by beahlbsmf** [comment]
> **Is your feature request related to a problem? Please describe.**
> I just started a new game on a harder difficulty with a larger map, things were going really well and I was profitable from the start. Until I was asked to make a donation.. Thinking I could afford whatever it was, I accepted.. And immediately got a game over. I had more money than when you start, and I hadn't even progressed 7 months into the game when this happened. So my main question is: How much are the donations, and are they based on your current wealth, current year, or what?
> 
> **Describe the solution you'd like**
> I would like to see the amount I am being asked to donate before I accept or decline, so that way I at least know what I'm working with.
> 
> **Describe alternatives you've considered**
> Having the donation amount be based on a percentage of your wealth.
> 
> **Additional context**
> As I mentioned in the problem section, I was only 7 months into the game, and had about 500k in cash, one location, and three employees. Playing on 'Engine Developer' difficulty, and on a huge-size map.

Indeed, it is a part of the "Beahl Megapack" mod. I will make an update about it asap (I'll do all i can but don't expect it soon).

**Comment by xsellier** [comment]
Closing since it's been fixed (thanks @beahlbsmf  )
