### ISSUE TITLE
Number of produced points to appear instantly

### ISSUE THREAD

**Issue by PLord84** [binogure-studio/city-game-studio-i18n#537]
Currently, when u finish a game it will take a few seconds for the points to accumulate, i suggest to make it appear instantly/allow us for it to show the overall points instantly everytime you finish a game.

**Comment by xsellier** [comment]
Hey,

You can do that by setting the game on low settings.
![image](https://user-images.githubusercontent.com/6616005/109124229-f5cbee00-774a-11eb-81a8-dadff4b01372.png)
