### ISSUE TITLE
Bug: 'Marketing Campaign' Window Not Updating Properly

### ISSUE THREAD

**Issue by proxyspride** [binogure-studio/city-game-studio-i18n#538]
[**Describe]([url](url)) the bug**
My game has been taken off the market, however it's still selling copies somehow, and is still receiving marketing.
I cannot end the marketing campaign, because it has disappeared from the Marketing Campaign window.

**To Reproduce**
1. Produce a game.
2. Wait for the game to be near being taken off market (leave enough time to port to another console).
3. Port the game to another console.
4. Market the game once it's been ported.
5. See how the game is 'taken off the market', but is still visible in the sale report window. See how the game is taken off 'Marketing Campaign' window.

**Expected behavior**
Marketing would still be available since the game is still selling for a new console.
![Marketing Bug](https://user-images.githubusercontent.com/60828991/108592188-2231d580-7319-11eb-94bb-1b3e9f5a3681.PNG)
![Marketing Bug 2](https://user-images.githubusercontent.com/60828991/108592221-468db200-7319-11eb-866f-30c7e217cd43.PNG)

**Desktop (please complete the following information):**
 - Windows 10
 - Unstable Branch

**Additional context**
Attached screenshots taken at the same frame, in-game.

**Comment by xsellier** [comment]
Im gonna fix this bug for this update:
https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-55424367

**Comment by xsellier** [comment]
Thank you, I've just fixed it this morning.
Will be out for v1.0
