### ISSUE TITLE
Expanded Events

### ISSUE THREAD

**Issue by DeadlyDragoon** [binogure-studio/city-game-studio-i18n#543]
Another idea from working with Beahl.
Events can't have variables. This forces awkward writing.
"One of your games will have increased sales."
Alright, cool... Which game? 
Mods can't tell you. 

What if instead of writing "Hello Boss" we could write "Hello <Player's Name Here>" 

Additionally, more event options would be nice. The ability to modify the rate in which staff need to vacation, increase their development skills directly, and have a gradual percentage of wealth income over a period of time. 

All of these additions could be used in base-game events as well.

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion, this has been implemented in v1.6.0, and is already available on the usntable steam branch.
closing this.
