### ISSUE TITLE
Event Backgrounds

### ISSUE THREAD

**Issue by DeadlyDragoon** [binogure-studio/city-game-studio-i18n#544]
All events in the game, that I have seen, are currently shown on a white background with black text. 
It'd be nice if different colours or designs could be added. 

For example, a red themed background with maybe a non-copyrighted mushroom and coin for Nintendo's console announcements. 

Maybe something blue with some rings for Sega's. 

Negative events, like the market crash, could be portrayed with dark colours. Good events could use bright colours. 

The best example for this is Stardew Valley. Letters from NPCs might have custom graphics on them that look awesome! It gives that letter more personality and individuality when compared to the rest.

**Comment by xsellier** [comment]
Thank yo ufor that suggestion, because the blank background felt empty indeed.
I found a way to fill it up using tilesets. I hope you'll like the result
![image](https://user-images.githubusercontent.com/6616005/183244243-528ceab9-53f5-47e5-b7f6-bc8014012e77.png)
