### ISSUE TITLE
Bug: Porting Games to a New Console Does Not Work

### ISSUE THREAD

**Issue by proxyspride** [binogure-studio/city-game-studio-i18n#546]
**Describe the bug**
Porting a game to a console I just released is not adding games to it's library. I ported 3 games to my new console and none of them actually worked.

**To Reproduce**
1. Release a console.
2. Port a game from a different console to your new console.
3. Check the game library of your new console.
4. See the game library has not changed.

**Expected behavior**
Expected the ported games to be added to my new console's library.

This is on the Early Access Build.

**Comment by xsellier** [comment]
Hey,

Thank you for that report.
I'm not able to reproduce that issue on the unstable Steam branch. So I think I fixed it yesterday while I was fixing tons of bug
You can try out the unstable Steam branch to be sure that it's been fixed.
