### ISSUE TITLE
Suggestion: Language packs 

### ISSUE THREAD

**Issue by cwa-gif** [binogure-studio/city-game-studio-i18n#547]
**Is your feature request related to a problem? Please describe.**
I love this game, but It could always need more stuff this request is for language packs/translations

**Describe the solution you'd like**
* language packs add ons for games, and maybe global marketing/global sales in specific markets. f.i. vikings do well in scandinavia and so on. One could use services for it or use the studios for making versions in other languages/market specific, ad-ons and so per country/censure ie

**Describe alternatives you've considered**
Easiest is to implement which markets/languages the game should be released in
also one can add market specific content per region
one can also do global marketing, and do marketing in a region thge game is thought to do well in

**Additional context**
Players all over the world (like me in Norway) play this game, so cool to have some international content

**Comment by xsellier** [comment]
Closing in favor of: https://github.com/binogure-studio/city-game-studio-i18n/issues/735
