### ISSUE TITLE
Suggestion: New themes for vanilla version (list incl.)

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#549]
Issue - clear game (without workshop mods) have a small number of themes, some themes like 'Arabian night' are specific.
I dont like to use mods because it always a risk of stability issues.

List of themes (many inspired from other tycoons, few unique - just came up with)

- agents
- antiquity (strategy, quests at first)
- astronaut
- airplanes
- aliens
- angels
- apocalypse
- assassins
- barbarians
- baseball
- basketball
- bricks
- bounty hunter
- bunker
- building
- cars (incl. F1, racing, streetracing, etc.)
- casino games
- castles
- colonization
- conquest
- cooking
- crocodiles
- cyborgs
- dance
- demons
- detective
- digging
- dinosaurs
- draw (elves)
- dwarf
- dungeon
- economy
- elves
- farming
- forerunners
- football
- frogs
- guitar
- golf
- goverment
- heaven
- helicopters
- hell
- hunt
- ice age
- ice hockey
- immortal
- insects
- islands
- knights
- martial arts
- mech
- mercenary
- monkeys
- monsters
- mushrooms
- mystic
- necromancy
- orcs
- police
- planets
- prison
- rabbit
- Renaissance (strategy, quests, actiongames (The Order 1889, Dishonored for example)
- revolution
- riot
- robots
- samurai
- ships (sea/space)
- skeletons
- space
- special corps
- steel arms
- stone age
- submarines
- survival
- tanks
- trains
- tropics
- theme parks
- thieves
- treasure
- trolls
- undead
- ufos
- vikings
- werewolves
- wizards
- world war
- worms
- wrestling

probably later add some more :)

**Comment by xsellier** [comment]
Hey,

Thank you for that suggestion, I'm gonna close that issue because there is one dedicated for theme suggestions:
https://github.com/binogure-studio/city-game-studio-i18n/issues/549

**Comment by FolioNov9m** [comment]
> Hey,
> 
> Thank you for that suggestion, I'm gonna close that issue because there is one dedicated for theme suggestions:
> #549

ok, just chekc themes please, few of them could be unique and mb will be interesting 4 you
