### ISSUE TITLE
Suggestion: grouping studios under an umbrella

### ISSUE THREAD

**Issue by max-pete** [binogure-studio/city-game-studio-i18n#550]
it would be cool to be able to group different studios under umbrellas, so it easier to select when choosing what studios work on a project.

it is annoying when having to go through the list of studios to choose which ones i want to work on a project individually, it would be much easier if you could choose a group of studios to be part of one 'umbrella' which can be selected when choosing teams.

these 'umbrellas' would be set up outside of development and can be edited at any time.

**Comment by xsellier** [comment]
Duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/422
