### ISSUE TITLE
Suggestion: Other Publishers publishing games for your consoles

### ISSUE THREAD

**Issue by cwa-gif** [binogure-studio/city-game-studio-i18n#551]
**Is your feature request related to a problem? Please describe.**
When we make our own consoles, time often catches up, so it is hard to make a lot of games for the console before the need arise for a nextgen console. I would love the option for other publishers to publish games for our consoles (like we do ourselves) we do not necessarily need to earn a lot of money from it, but the "games for console: 1-5" irritates me, would love for opportunity to get bigger market share, after all my console is far more powerful thasn many of the others....

**Describe the solution you'd like**
Does not need any events or anything (or maybe they ask us for permission, but not really needed) just that the games for console number explode, and that the market share rise according to this. 

**Describe alternatives you've considered**
One could put more into it f.i. permission evcents, negotiations and so on, but it is not really necessary

**Additional context**
Hope this gets implemented

**Comment by xsellier** [comment]
They already can publish games on your console.
I just need to balance the consoles at the moment.
You might want to try out the unstable steam branch.
