### ISSUE TITLE
Suggestion: Exclusivity contract - counter offer

### ISSUE THREAD

**Issue by ArthieuCYD** [binogure-studio/city-game-studio-i18n#553]
Je propose ici cette modification avec les propositions d'exclusivité de la part des éditeurs sur nos jeux proches de sortir. Quand ils nous proposent une exclusivité, on a malheureusement que 2 choix : refuser ou accepter. J'aimerai proposer le fait de pouvoir négocier en demandant moins d'argent mais par contre en donnant l'exclusivité du jeu sur 6, 12 mois (un peu comme le système de licence déjà présent sur le jeu). Ça permettrait d'éviter de refuser une offre qui pourrait être intéressante et la négocier un peu. 
Je verrai bien un système du type : on reçoit X $ pour une exclusivité totale, uniquement 50% de X pour 1 an, 25 % de X pour 6 mois. 
Si des précisions sont nécessaires n'hésitez pas !

**Comment by GianluPlay** [comment]
Ñ

**Comment by xsellier** [comment]
Closing in favor of this one #772 (because this one is in french)
