### ISSUE TITLE
Suggestion: Name of the Game on Development Menus

### ISSUE THREAD

**Issue by DoltenBolten** [binogure-studio/city-game-studio-i18n#556]
**Is your feature request related to a problem? Please describe.**
Sometimes, when I create multiple games and then the development screen appears, I don't know which game it's for.

**Describe the solution you'd like**
What I suggest is for there to be the name of the game on the development screen between how much the development costs and how long it will take.

**Additional context**
Here's what it could look like:

![desktop](https://user-images.githubusercontent.com/66805168/111502308-208ede00-871c-11eb-8ce4-4eedc2023b43.png)

**Comment by xsellier** [comment]
Indeed, I just added it.
Thank you!
