### ISSUE TITLE
Suggestion: Sell IPs (and Maybe Internal Engines) to Competitors

### ISSUE THREAD

**Issue by ThisNekoGuy** [binogure-studio/city-game-studio-i18n#558]
**Is your feature request related to a problem? Please describe.**
No issue, just thinking of creative ways to make money in the game.
(Perhaps for when the player is striking economic trouble)

**Describe the solution you'd like**
After an IP has been established, the IP gains a net-worth for that which can be leveraged to sell the IP to competitors
(This may perhaps also log the IP title and remind the player not to name the same thing for future titles?)
(Similar for game engines except the benefit for doing so for internal engines is based on how advanced they are)

**Describe alternatives you've considered**
Selling a seperate studio's talent and location to a competitor is another idea I just now thought of on the spot.

**Additional context**
Really, this is just my idea of saving my @$$ when my company is standing with one-foot in the grave

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion. It looks like this other ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/97

I'm gonna close this ticket, because those are going to get linked together.
