### ISSUE TITLE
Bug: (Unstable Version) Distorted / Noise-filled Audio

### ISSUE THREAD

**Issue by ThisNekoGuy** [binogure-studio/city-game-studio-i18n#559]
**Describe the bug**
Not sure why, but now every time I start the game, I can hear the audio but there's also a sort of a loud static noise that goes along with it (with my headset)
And if I play it though my TV speakers, it sounds like that but music is incredibly distorted, so it's quite worse and I can't get it to stop.

**To Reproduce**
1. Run the Unstable Branch Game from Steam
2. Hear wrecked audio

**Expected behavior**

**Logs**
Attach log files to this ticket:

[citygamestudio-2.log](https://github.com/binogure-studio/city-game-studio-i18n/files/6176867/citygamestudio-2.log)

**Screenshots**
(Not applicable)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling release

**Additional context**
This happened once earlier today, when I tried to play the game through my TV speakers, but I switched to my headset and it behaved fine. Then, after I played for a while, my entire desktop froze and I had to reboot. Now, the audio for the game is always like this.

**Comment by xsellier** [comment]
thank you for the report, I published a bugfix, just check out the troubleshooting guide:
https://steamcommunity.com/app/726840/discussions/0/4111168970105560012/
