### ISSUE TITLE
Suggestion: Genres description

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#560]
Problem - genres have no description

Solution - Few words in this window for some genres. Dungeon and Dungeon Crawler - no explained what a difference for example. 
https://i.imgur.com/ZLJYJEh.png

The same exist in Mad Games Tycoon and could be very useful

**Comment by xsellier** [comment]
Hey,

Genres don't have description because I think it is better to leave some blank so you can fill them up.
For example, a Dicey Dungeon is a Rogue-like game as FTL or Rogue Legacy.

**Comment by FolioNov9m** [comment]
` it is better to leave some blank so you can fill them up`

Does this option available in current steam version? O_o

**Comment by xsellier** [comment]
I was saying I'd rather don't add a description so you can fill them up with your imagination.
But do you want to fill up the game genre description?
