### ISSUE TITLE
Suggestion: Game Boy Color is Absent Between GB and GBA

### ISSUE THREAD

**Issue by ThisNekoGuy** [binogure-studio/city-game-studio-i18n#561]
**Is your feature request related to a problem? Please describe.**
Just noticed the absence of a handheld and felt strange, considering that it was the first console I ever owned IRL

**Describe the solution you'd like**
Implement the GBC?

**Describe alternatives you've considered**
None, I was addicted to the GBC for a long time :joy: 

**Additional context**
N/A

**Comment by xsellier** [comment]
Just added to the game with v1.9.0.

**Comment by GianluPlay** [comment]
Finally, after asking for it a lot of times
