### ISSUE TITLE
@Binogure I have idea. Create and sell hardware.

### ISSUE THREAD

**Issue by brokker11** [binogure-studio/city-game-studio-i18n#566]
Create CPU, GPU, OS. Work with Asus, Msi, TSMC and others. And research hardware

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion but this game is about making games/consoles.
Regarding hardware stuff, I suggest you to try out Computer Tycoon
https://store.steampowered.com/app/686680/Computer_Tycoon/
