### ISSUE TITLE
Suggestion: Port game feature rethink (Game re-development)

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#570]
**Is your feature request related to a problem? Please describe.**
For now feature of game port is useless. I have a good game, by Sega Platform for example. I want to port this game in NES.
Compatibility is 62% or something else.

**Describe the solution you'd like**
Low Compatibility meaning that it needs advanced time, money and development. Game will be good too, but after advanced polishing.
This is something like game re-development. Faster than classic development, but pretty long procedure, no just few seconds right now.

**Additional context**
Very interesting case.
Game created by Sega, which more technological than NES. So player need to choose features of Engine, which will be disable in lower platform.

Vice versa, if my game released in low platform and I will port this game in better platform, I can to add advanced options, just like new game creating functions I mean. For advanced price and time forsure.

I guess it will be better port system in CGS, for now I just have no reason to use ports - game just a crap after this.
IRL some ports are terrible too, but some of them are good and exactly good ports re-developed just as my suggestion.

**Comment by FolioNov9m** [comment]
Any prediction about this feature in v1.00 ? 
Cheers!

**Comment by xsellier** [comment]
Are you using the steam unstable branch?

**Comment by FolioNov9m** [comment]
> Are you using the steam unstable branch?

After few years of Alpha testing in different projects, I enjoy of stable release version ^_^
Your answer is meaning that this feature already integrated isn't ? 👍

**Comment by FolioNov9m** [comment]
@xsellier ok, I checked unstable version and game still losing rating after port as I can see o_O

**Comment by xsellier** [comment]
It depends on the game now. You can get a better rating with a gameport.

**Comment by FolioNov9m** [comment]
> It depends on the game now. You can get a better rating with a gameport.

Ok thanks!
Will check this after release v1.00. For now I just create random indie game and port it.

Is it clear rating system or player couldn't to predict ?

**Comment by xsellier** [comment]
It is predictable

**Comment by FolioNov9m** [comment]
> It is predictable

Amazing, thank you very much!
