### ISSUE TITLE
Suggestion: Controller Vibration as a Game Engine Feature

### ISSUE THREAD

**Issue by DoltenBolten** [binogure-studio/city-game-studio-i18n#572]
I suggest for Controller Vibration/Haptic Touch as a new Game Engine Feature that you can implement in a Game Engine

**Comment by GGplays** [comment]
Mod Engine Features add that!

**Comment by xsellier** [comment]
Hey,

Since City Game Studio supports mods, and as GGPlays suggested it, you can add it via mods.
You can use that website to make one: https://modmaker.city-game-studio.com/
Then launch City Game Studio, click on Mods, then Create.

Cheers.
