### ISSUE TITLE
Dutch Translations

### ISSUE THREAD

**Issue by koenderey** [binogure-studio/city-game-studio-i18n#58]
Sandbox mode in dutch is just "sandbox modus".

We don't really have a correct translation for it.

**Comment by koenderey** [comment]
Also in the language dropdown.
Dutch = Nederlands

**Comment by xsellier** [comment]
Thank you again for your contributions

I wonder, do you want "Nederlands" or "Dutch" in the language dropdown?

**Comment by koenderey** [comment]
Either is fine for me. But let's use Nederlands for the people who don't speak much english ;)
