### ISSUE TITLE
Suggestion: Allow a studio to join a project that it isn't a part of and vice versa

### ISSUE THREAD

**Issue by PLord84** [binogure-studio/city-game-studio-i18n#582]
In the game when you make a new studio and there's already an ongoing project it can't join it, i think that shoudn't be a thing.

**Comment by DoltenBolten** [comment]
Oh, I was just about to suggest this!

**Comment by xsellier** [comment]
It is already on my TODO list

**Comment by ghost** [comment]
Would like to bump this, it can be quite annoying :)

**Comment by DoltenBolten** [comment]
@Yardanico He hasn't forgotten https://github.com/binogure-studio/city-game-studio-i18n/projects/2#card-58952237

**Comment by xsellier** [comment]
Implemented with the latest unstable version. Should be out within few fays on the main steam branch.
