### ISSUE TITLE
Suggestion: When one competitor disappears (competitor went bankrupt or competitor was sold) newone will appear after half year

### ISSUE THREAD

**Issue by Boris911** [binogure-studio/city-game-studio-i18n#584]
Because is in the game low limit for maximal competitors up to 25 competitors. Mod can't exceed this low limit of maximal 25 competitors. 

I suggest add feature to the game that when player or other AI will buy competitor, the number of will decrease (from 25 to 24). New one competitor will appear after half year to increase number back to game fixed limit 25 competitors.

E.g. when you and 4 AIs will buy one competitors for each in the future will appears in the game 5 new competitors (back to maximum 25 competitors).

Of course much more better will be break that fixed limits up to 25 competitors via mod settings. However, when the author of the game grumbles, it is necessary to look for an alternative way to buy several competitors so that the game does not end in a monopoly.

**Comment by xsellier** [comment]
Thanks for the suggestion!
It's now part of City Game Studio. New competitors will spawn!
