### ISSUE TITLE
Suggestion: suggestions,feature request,fixations

### ISSUE THREAD

**Issue by ea76** [binogure-studio/city-game-studio-i18n#587]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

1-Is it possible to add "Filter by name" or Search button in sales report right hand side menu?
When you have so many games it takes too much time to find the game that you want and apply discount or update.**_
2-The bottom panels is too small now while the older version was better; but the left and right hand side panels are okey now because in older version they cover too much space.
3-The fans evolving threshold may perhaps be revised.Of course reality is important but in fact this is a game.When you open lots of studios and produce thousand of games you obviously reach limits quicker than it was foreseen,and it is not pleasant to see losing fans at this point while doing very good games...
4-The auto-furnish option's desk efficiency is very low: in 750m2 studio it places max 47 desks while you can manually place 70 desks easily with 100% happiness.In auto furnish mode you have to make adjustments as well because 100% happiness is not guaranteed.
5-The latest consoles of the game(each material latest technology) can have a cost greater than 1K $ while the game limits the selling price to 1K $ so it's a deficit in debut.

**Describe alternatives you've considered**

**Additional context**

**Comment by ea76** [comment]
6-When doing some project in left hand side panel.the studio's flexibility is low,we can not add or remove studios on current projects to another which is contrary to real life as you can bring practical solutions to unexpected situations,wrong decisions etc...

**Comment by ea76** [comment]
7-the available studios in town always stabile;it may change every month or year;also the  rents or selling price of the existing used studios should change over time
8-the other buildings dont have any role in the game,may be they can have some role
9-i didnt realize yet whether marketing is worth or not,the benefits are not very understandable right now;also there is a negative event when doing marketing campaign to increase hype that even at the end you produce a superb game the reviews are very bad,for this reason i am not doing marketing campaigns when producing games ...

**Comment by ea76** [comment]
i am not sure whether i posted my first comments to the right place so i re post them :

1-Is it possible to add "Filter by name" or Search button in sales report right hand side menu?
When you have so many games it takes too much time to find the game that you want and apply discount or update.**_
2-The bottom panels is too small now while the older version was better; but the left and right hand side panels are okey now because in older version they cover too much space.
3-The fans evolving threshold may perhaps be revised.Of course reality is important but in fact this is a game.When you open lots of studios and produce thousand of games you obviously reach limits quicker than it was foreseen,and it is not pleasant to see losing fans at this point while doing very good games...
4-The auto-furnish option's desk efficiency is very low: in 750m2 studio it places max 47 desks while you can manually place 70 desks easily with 100% happiness.In auto furnish mode you have to make adjustments as well because 100% happiness is not guaranteed.
5-The latest consoles of the game(each material latest technology) can have a cost greater than 1K $ while the game limits the selling price to 1K $ so it's a deficit in debut.

**Comment by ea76** [comment]
10-Is the star rating of the company working correctly? (right hand panel-list of companies section)
My average game rating is 86.5% and my company rating is 5 star over 8 star ? 
I remember that it was 10 star before this version and was working correctly..

**Comment by ea76** [comment]
sorry for this request but my eyes are really bad when reading and now i have difficulties to read the tooltips,the new font is very small at least for me (it was the case after today's update )...Is it possible to make it  a little bigger?

**Comment by ea76** [comment]
11-the devs that you hire from staff menu are making very little progress in terms of training,if they have good design level they progress and make their level 99 quickly but their development and polishing levels barely advance,you play the game 45 years and studio average training remains around 65-70%.While the devs that you acquire from the job application mail quickly advance and reach 99/99/99. I dont know right now whether training level of the studio affects the game scores ? I assume that you receive good game scores usually,so the training level dont affect the scores too much like the game difficulty...

**Comment by xsellier** [comment]
Hey,

Thank you for all those suggestions. I'm gonna keep an eye on those.
It is better to split your suggestions in order to have one suggestion per issue. I need to split it that way because it is easier to produce a changelog, for example:
## v1.2.5 includes
- issue #9876
- issue #9765
- issue #1269

For example, I implemented your request ie this comment https://github.com/binogure-studio/city-game-studio-i18n/issues/587#issuecomment-819647849 . I cannot put a link like that in the roadmap: https://github.com/binogure-studio/city-game-studio-i18n/projects/2 because if the ticket contains more than one suggestion and I implemented only one _comment_ then I cannot close the issue and I cannot publish a new version without breaking everything.
So I'm gonna lock this issue, because I won't be able to track it correctly.
