### ISSUE TITLE
Suggestion: Add cheatcode

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#588]
Add cheatcode

**Comment by Andulak** [comment]
The best implementation of cheats in a game like this would be a cheat menu which could be brought up at any time by pressing a button in-game or a hotkey, the game would be paused while the cheat menu is up (like it is with any other menu). This cheat menu would be enabled by a checkbox option in the setting under "Misc settings" so it can be enabled while playing any save/session, unlike sandbox mode which can be enabled only during the "New Game" screen.

The cheat menu would have basic and an advanced mode:
The basic mode would cover the most basic cheats:
Separate buttons for money, fans, genre points amounts: 
Add 1 mil. 
Add 10 mil.
Add 100 mil.
Add 1 bil.
Add *Custom player amount*

Checkbox cheats:
Max. Hints
Max. Hired Staff Design
Max. Hired Staff Development
Max. Hired Staff Polish
Max. Hired Staff Happiness and won't drop
Max. Hired Staff Energy and won't drop
Hired Staff Never Quit
Hired Staff Zero Salary
Always Max. Review Score
Always Max. Hype and won't drop
Zero Expenses (substractions from money won't count)
Platform/Target Audience always excellent match
Theme/Game genre always excellent match
Equipment won't break
Max. Compatibility between consoles
Negotiations Always Successful (regardless of the amount of money offered by player)

Multiplier sliders x2, x4, x8, x16, x32, and/or user-defined:
Money Income
Fans Gain
Genre Points Gain
Server Capacity
Development Speed of Games, Consoles, Updates, Ports, Online Store, etc...
Design, Dev., and Polish generated points during development per employee
Market Share of Player-owned consoles
Productivity of hired staff
Productivity bonus and game capacity of hired Producers
Happiness bonus and number of studios of hired Human Resources
Taxes Reduction and game capacity of hired Accountants
Hype Bonus and game capacity of hired Marketing Managers
Server Load Bonus and game capacity of hired Network Administrators

Advanced mode:
This mode would expose all variables that can be changed while playing the game.
The list of variables would contain among other things(also mentioned above):
Graphic, Compute capabilities, and market share of all consoles
All themes
Budget and Fan Base of competitors

The idea behind advanced mode is that the user would be able to lock/unlock, freeze/unfreeze, change, multiply any value that can be edited during game-play which may include game speed, hidden difficulty values, capabilities of consoles, happiness and productivity values of desks, and trending status of themes.

Inspired by:
CheatMod Revived for GDT https://steamcommunity.com/sharedfiles/filedetails/?id=713207155
Trainer v4 for Alpha 11 Software Inc. https://steamcommunity.com/sharedfiles/filedetails/?id=1884023959
Fling Trainers (bannerlord trainer is a great example of multipliers and player edited values) https://flingtrainer.com/trainer/mount-blade-ii-bannerlord-trainer/
gideon25 cheat table for MGT 2 https://fearlessrevolution.com/viewtopic.php?f=4&t=15183

Hope at least something will make it to the game. I May edit a thing or two but it should be a complete list.
Thanks for reading this.

**Comment by FolioNov9m** [comment]
@xsellier 
One cheat code which I really want is opportunity to choose overall gamerating before release. Where set price window I mean. It will be great, because as I told I play CGS more like roleplay game and have frustration when my minor projects have super ratings and super profits, but my paramount franchise is failed despite sliders are good.

With cheat I could feel more freedom and creativity in settings and manipulate ratings (not only increase, but also decrease) which give a lot a fun personally to me

Simplified version - permanent rating for all released games (was the same in Game Dev Tycoon). This is not much interesting like choose manually, but better than nothing. 

What do you think about this?

Cheers

**Comment by FolioNov9m** [comment]
> @xsellier
> One cheat code which I really want is opportunity to choose overall gamerating before release. Where set price window I mean. It will be great, because as I told I play CGS more like roleplay game and have frustration when my minor projects have super ratings and super profits, but my paramount franchise is failed despite sliders are good.
> 
> With cheat I could feel more freedom and creativity in settings and manipulate ratings (not only increase, but also decrease) which give a lot a fun personally to me
> 
> Simplified version - permanent rating for all released games (was the same in Game Dev Tycoon). This is not much interesting like choose manually, but better than nothing.
> 
> What do you think about this?
> 
> Cheers

The same cheat (fixed rating or manual editing of rating) for all ports if it possible please.

**Comment by FolioNov9m** [comment]
Hi Bino!

Is it difficult to add ~ command to manipulate console/platform units sold ?
Or market share directly? I want to increase market share by cheat

Cheers!

**Comment by icls1337** [comment]
+1

**Comment by xsellier** [comment]
Press F5 to activate Cheatcodes.

**Comment by xsellier** [comment]
Closing since it's been added to the game.
