### ISSUE TITLE
Suggestion: Game Remakes

### ISSUE THREAD

**Issue by KillerWraithGamingUK** [binogure-studio/city-game-studio-i18n#591]
I think it would be cool to remake the games you release earlier in the game so if you release a game in 1996 and you want to remake it in 2016 or 2026, you should be able to click "Remake Game" and pick an old game you made to remake it with newer tools and such. Seeing as we are getting into the times where Old games from the 90s are being remade in new engines with new graphical fidelities.

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion. It has already been submitted so I'm closing this one and linking it with the other one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/351
