### ISSUE TITLE
Bug: Skylight 8 wrong servicelife, popularity and capabilities

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#592]
Windows 8 supported from August 2012 to Jan 2016.
Skylight 8 existing in 2020 yet in CGS
If it 8.1 but I guess it needs smaller CC and GC, because 103/78 is pretty much for touchscreen hardware.

More. Skylight 8 is the most popular platform in 2020 :
![image](https://user-images.githubusercontent.com/80094976/115725895-e653d480-a38a-11eb-8283-4a090f328995.png)

And in 2021 too
![image](https://user-images.githubusercontent.com/80094976/115726478-6f6b0b80-a38b-11eb-9f75-9fd66f1ab23e.png)

**Comment by FolioNov9m** [comment]
The same for vanilla CGS
![image](https://user-images.githubusercontent.com/80094976/115728953-a3473080-a38d-11eb-9791-e31cfa8e0c22.png)

**Comment by xsellier** [comment]
Thank you for the report.

**Comment by xsellier** [comment]
Windows 8.1 end of support january 2023.
( https://www.support.com/how-to/when-is-windows-8-and-81-end-of-support-13095 )

Skylight 8 contains Windows 8 and Windows 8.1.
Market shares have been balanced.
Thank you for the report.
