### ISSUE TITLE
Bug: Port a game

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#594]
Very strange bug.

Starting Screen:
![image](https://user-images.githubusercontent.com/80094976/115884199-4e6fec80-a457-11eb-8816-f29c99c133cc.png)

As you can see, default platform is PC 8002. But this is not released yet and I dont want to port game to this. I can't disable. But if I choose another, PC8002 still in list:

![image](https://user-images.githubusercontent.com/80094976/115884329-795a4080-a457-11eb-9a0d-a63cb411ab48.png)

1/3 but I choose only 2
![image](https://user-images.githubusercontent.com/80094976/115884408-8c6d1080-a457-11eb-8633-78bbf198033c.png)

If you explain where is save folder I will attach savegame. Didn't find saves in steamapps\common\City Game Studio

**Comment by FolioNov9m** [comment]
I remembered you wrote route in SteamComm. :)
I can't upload direct file or .rar so
https://drive.google.com/file/d/1FndR0ZJOReksY_UtQE5q2Y9OolSjolA0/view?usp=sharing

**Comment by xsellier** [comment]
Not a bug. You can start working on a game even if the paltform is not yet released.

**Comment by FolioNov9m** [comment]
You dont understand a point. I dont want to use this platform and I can't disable this choice, it always is active...

**Comment by xsellier** [comment]
My bad, you're right! Thanks for the report

**Comment by FolioNov9m** [comment]
> My bad, you're right! Thanks for the report

Good 👍 
I see the same today with Kernel 2, so this is no linked for specific platform

**Comment by xsellier** [comment]
Problem fixed!
