### ISSUE TITLE
Bug: my save game is locked 

### ISSUE THREAD

**Issue by ea76** [binogure-studio/city-game-studio-i18n#598]
hi,
my save is locked at the end of the month and dont proceed,i spent many times for this game,could you do anything to make it work again? I reported also as a bug within game menu.Thanks

**Comment by ea76** [comment]
Hi,

I opened another previously saved game(which i saved in January 2005) and played totally different but at the same time that is the end of May 2006 the game is stopping again,the application is not responding.
For this game i spent more than 1 months,is possible for you to do something??

**Comment by ea76** [comment]
note : i opened again the save game that i saved in January 2005 and this time fast forwarded by doing nothing until May 2006 and the game didnt stop this time at the end of May 2006 !! So what may cause this problem? May it be related with the size of the save game ?

**Comment by xsellier** [comment]
N idea since I haven't your savegame and the description is really not clear at all.
I cannot help you if you don't describe the problem you encounter.

**Comment by ea76** [comment]
I reported bug for the save files so you can see them.
the game stops working at the end of May 2006.I started playing as usual from January 2005,produce games,did contracts etc... and then it stops at the end of May 2006,the application is not responding then.
but i started again the save game again that is from January 2005 and did nothing just fast forwarded to see whether it will stop again at the end of May 2006 and it didnt stop and continued to the next month.

**Comment by xsellier** [comment]
Hey,

I received your bug reports indeed! Thank you for the report.
I'm gonna try to reproduce your issue, however 55Mb, that is a HUGE savegame!

**Comment by ea76** [comment]
it was a usual game which started at 1976,you many times helped me in this game,did you remember the game making menu was opening very late and you corrected...

**Comment by ea76** [comment]
yes because there is near 3000 games produced inside

**Comment by xsellier** [comment]
I do remember! Oh god, that savegame is reallllllly huge. I dont know how to handle a save that is that big!

**Comment by ea76** [comment]
it will be a huge disappointment for me to see that i couldnt finish this game but i know that you always helped me and did your best thank you indeed.It was the fault of me may be,because i see that one person scored more than 3M points,so decided to break the record but ....

**Comment by xsellier** [comment]
One good news for you.
I know why the game freezes, and I know how to fix that.

The bad news, it is gonna take me a while to fix it

**Comment by ea76** [comment]
I am really sorry of disturbing you in your too much crowded working schedule indeed...

**Comment by xsellier** [comment]
No worries, thank you for that report, you impressed me really. That savegame is huge!

**Comment by ea76** [comment]
thank you for you 2 for creating this beautiful game...

**Comment by ea76** [comment]
many times i changed my tactics of playing this last game as i was on the verge of leaving it in the late middle ::)
the change that you made with publishing limitless game,gave me the force to continue...

**Comment by xsellier** [comment]
Im publishing a hotfix on the usntable steam branch. Just tested it, you can go past May 2006 without any issue.
But, regarding your savegame I have to say I need to implement paginations on several panels (in-dev and released-game panel).
Otherwise the game is so laggy that it is barely playable.

**Comment by ea76** [comment]
thank you very very much, but according to you shall i wait some time to play it? Do you think those paginations will take too much time? SORRY !!!

**Comment by xsellier** [comment]
It is going to tkae a while to implement indeed. ETA mid-may

**Comment by xsellier** [comment]
Update released, yo ucan start playing again ;)

**Comment by ea76** [comment]
i see, thank you for all your efforts; one more time sorry for all the burden that i gave you...
will i heard from you when those implementations are ready?

**Comment by xsellier** [comment]
Im gonna update this ticket as soon as the update is ready.

**Comment by ea76** [comment]
okey, take care yourself, nice to meet you...

**Comment by xsellier** [comment]
Patched part of the game already. So if you load the latest version you should get few extra FPS.
But the pagination hasn't been implemented yet.

**Comment by ea76** [comment]
thank you indeed really appreciated...

**Comment by ea76** [comment]
after our conversation i updated the game 2 times with short breaks;then i played 2 months without problem,after the 3rd month the game freezed again
i reported as bug so you can check last situation
in terms of speed right now the game is in the same speed(waiting time) as before this problem...

**Comment by xsellier** [comment]
Found out the root cause and fixed it! Sorry for the delay!

**Comment by ea76** [comment]
hi,
no problem for the delay,does this mean that i can play right now?

**Comment by xsellier** [comment]
Not yet, I double checking the fix before publishing the update.

**Comment by ea76** [comment]
ok thanks, i will wait news from you to play again...

**Comment by xsellier** [comment]
Update published!

**Comment by ea76** [comment]
thanks indeed,you mentioned about  implementing paginatations with ETA mid May;may i ask does this process continue or you managed to fix completely and it is ready?

**Comment by xsellier** [comment]
I still have some work to do

**Comment by ea76** [comment]
okey,thanks in advance for your efforts...

**Comment by ea76** [comment]
hi,hope you re well
i am really sorry to disturb you again but the game freezed one more time;after you fixed last time i managed to play from 2006 to February 2014 but now  it doesnt proceed further.It remained less than 7 years to finish the game,i hope i can see the end;
i reported the save game as bug so you can check the last situation..

**Comment by xsellier** [comment]
Hey,

I'm really sorry about that bug. Thank you for the new bug report,Im gonna chekc it ASAP.

**Comment by ea76** [comment]
hi,thanks no problem
The game saving style is not old-fashioned,we are saving over and over until quitting;do you think that this may inflate the size of the save game much more than it is expected?

**Comment by xsellier** [comment]
Saving again and again doesn't inflate the size of the save game much more than expected since it only saved what's needed.
But the more you play, the bigger the save game size is.

**Comment by xsellier** [comment]
Hey,

Sorry for the delay and thank you for your patience. A fix is available, I tested the whole 2014 year and everyhing seems to run smoothly. Please tell me if everything is fine for you too.

**Comment by ea76** [comment]
hi,
thank you very much,i will try at the weekend...

**Comment by ea76** [comment]
i am really sorry to inform you but nothing changed,it freezes the same place and dont proceed to the next month as i tried 3 times,i reported as bug report so you can check further.

**Comment by ea76** [comment]
i have only 2 save files,one is saved in beginning February 2014 and the other at the 3rd stop time of the same February 2014(i made the copy of first save file and started playing with this save file),i tried with both,they are freezing

**Comment by xsellier** [comment]
They are going to freeze, but it should work after 2 or 3 minutes. Because of your savegame I have to add an algorithm that dynamically allocate memory to the signal array. Since your savegame needs ~128Mo of memory, it has to realloc memory from 16Mo to 32Mo, then to 64Mo then to 128Mo. After those transitions your game shouldn't freeze anymore. But it means, everytime you load your savegame it is going to do that (I'm really sorry, the other solution would have been to allocate 128Mo by default, but it means the game won't work on toaster computers).

I will add a launch option to let you allocate more memory by default.

**Comment by ea76** [comment]
i understand the explanation and i thank you for developing for me the algorithm but may be my computer is bad and for this reason it is not working as i waited 10 minutes after freezing(2 times)
what happens is following:
1-the music stops and freezing starts
2-there is not any movement(the application is not responding)
3- i press ctrl+alt+del then i see a message on another window that "godot engine" stopped working

**Comment by xsellier** [comment]
I see. Let me try another thing. I think the game feezes because it has crashed (just dumping a big memory takes time)

**Comment by ea76** [comment]
i agree with you that it freezes because it has already crashed

**Comment by xsellier** [comment]
Ok, so I patched my previous code, and it should work better(it is also more optimized). May you please try it again?

**Comment by ea76** [comment]
here are my comments :  
1-i tried the new patch,it is similar,it crashes and freezes
2-due to fan evolving treschold,a game of 99 score easily loses more than 600K fans while a score of +105 hardly gains 500K fans;this give me the idea so i decided to delete from right panel all games with negative fans(it is barely scrolling with mouse wheel because there are enormous games on sales market) I think that every month i am adding max 10 games and if i remove 20 from right side may be something change;the result is SUCCESS i proceed to next month :)
3-i have to admit the game is really slow now,not the same level before i contacted to you for this problem;although the size of the save game didnt change yet as i didnt play
4-to tell you the truth we can not name this issue as bug,this is my stupidity to believe that making tons of games will help me to make the high score;maximum 1 or 2 person can contact you over 1000 person for such case,so you can remove bug label from it at least,but i am really grateful that you are helping me,otherwise this game have no chance at all to see the end...

**Comment by ea76** [comment]
5- of course i am not sure with this strategy of removing from market some games i can pass all the months remaining...

**Comment by xsellier** [comment]
I'm really sorry about that issue.
I mean you are the only player who has a savegame over 20 Mb. Good news is you helped me fixing  a lot of issues, and Im really thankful for that!
I tried your savegame and it seems to run fine on my computer, I haven't tried on windows yet (just moved into a new home, so I haven't setup everything yet). I'm gonna try it out as soon as I receive a new desk. I can tell that on OSX and Linux it works just fine.

**Comment by ea76** [comment]
hi,
i am glad that i forced the limits of the game so that you fixed those issues.
according to what you said then, either the problem still continue with windows or this game needs a little better computer than mine at least,
meanwhile i wish you a new good life in your new home !

**Comment by ea76** [comment]
by the way after our last contact  i managed to play 1 year more with my strategy until i sleep :)

**Comment by ea76** [comment]
hi again,
good news is that i finished the game,however bad news is that after seeing how it calculated the score,i wish i didnt play the game at all,this is the worst gaming experience in my life,,what happened to sore calculation of this game ???

1-whatever you produce in one month it only calculates 5 thing per month,for example if competitors used your engine that month 5 times that's all you get as score,no points for all the games,contracts you did in that month,max 5 items per month
2-per indie game may be less than 50 points,normal game less than 150 points,AAAgame less than 500 points(of course it only computes 5 item per month so the remaining produced games dont receive even those scores)
3-no points for numberless contracts that i finished,no points for engines done,no points for consoles made;no points for more than 30T$ money,no points for number of studios,workers, nothing nothing nothing
4-i waited till end scoring it computed laughable 1,5M points and it didnt even pass this score to the leaderboard
5-i played in easy mode (not choosed the sandbox mode,thereis a small box there i didnt choose it) but this doesnt explain why it didnt give scores to all my games,contracts etc...I played in my early games also in easy mose similar options and the calculation was not like this that time ??
Shokingly A game of 4369 games,thousands of contracts,7 consoles,30T$ money, barely pass my old score of 1,28M which was accumulated by doing max only 150 games and not even contracts.This is not my 1st game if it computed the score like it did in my previous games then this last game should acquire more than at least 5M points that i was quite sure.
SORRY but i am really very very disappointed,i think that this shouldnt be the result of near 2 months invested game
I am sending you the save file as bug report may be you can check...

**Comment by xsellier** [comment]
Hey you again :)

I'm glad you finished the game, but Im sorry you didn't like the score computation.

1) It shows only the first 5 items, but it computes all the game published in a month, no worries about that.
2) This can be adjusted.
3) So, there are points for engines, contracts and consoles but becausse you have published a lot of games you dont see them (the game shows only 5 items per month otherwise it is too laggy and unreadable).
4) The score is adjusted regarding the difficulty, the harder the better score. I'm sorry for you.
5) See above. There is a new leaderboard: https://steamcommunity.com/stats/726840/leaderboards/5924638 . The other leaderboard is a legacy leaderboard, it will be deleted later.

**Comment by xsellier** [comment]
I'm also surprised you didn't get more than 1.5m

**Comment by ea76** [comment]
you know better of course but i am sure there is somthing wrong with this calculation,i watched month by month it gave me such little points that i am pretty sure it didnt calculate all my games etc...,also if i knew about the difficulty difference when scoring, i of course play it in hardest mode because after 1000 hours i think i am expert unluckily(my previous 1,28M score was from hardest mode)
finally where is my score for this game? 1,28 is my pevious game score  ??

**Comment by ea76** [comment]
for example near the end of 2019 i produced 170 games in 1 month in order to score more as after this date no game will be able to finish the right time for scoring but nothing changed in calculation a similar little point again like each month

**Comment by xsellier** [comment]
I'm looking at the score computation algorithm at the moment.
- Indie game: 50 points * score / 100.0
- Normal game: 100 points * score / 100.0
- Big game: 200 points * score / 100.0
- AAA game: 500 points * score / 100.0
- Game genre unlocked: 5 points (per genre unlocked)
- Platform unlocked: 15 points * platform generation
- Game engine: 3 points * (CPU capacities + GPU capacities)
- Digital store (per feature): 0.1 * number of required point to implement the feature
- Game port: 150 points * score / 100.0
- Contract indie: 5 points
- Contract normal: 10 points
- Contract big: 20 points
- Contract AAA: 50 points
- Convention: Number of visitors * 0.01 points
- Custom platform: 15 points * (CPU power + GPU power)

**Comment by xsellier** [comment]
I think that your score is way above 2 147 483 648, and that is why it hasn't been uploaded on Steam. I mean Steam compute only scores on (2 ^ 32 bits signed).

**Comment by ea76** [comment]
there is 3M the leader

**Comment by xsellier** [comment]
3 millions, but I think you went over 2.1 billions

**Comment by ea76** [comment]
you mean billion ???

**Comment by xsellier** [comment]
I mean you scored over 2 billions yes, but because of that issue https://github.com/binogure-studio/city-game-studio-i18n/issues/68 your score hasn't been uploaded.

**Comment by ea76** [comment]
i expext max 5M hahaha

**Comment by ea76** [comment]
is it possibile to see this somehere or fix???

**Comment by ea76** [comment]
but when i see the end of computing after game it only wrote 1,5M

**Comment by ea76** [comment]
first i didnt realize,i am really shocked that you mentioned billion,i couldnt believe

**Comment by xsellier** [comment]
I testing your savegame to see your score, but it takes a while to end one year >_<

**Comment by ea76** [comment]
yes it takes too much time sorry the inconvenience that i caused you :(

**Comment by xsellier** [comment]
So I tested your savegame and you are right. You made only 1.28 million points, not 2.1 billions.
Regarding your savegame, you mostly made indie and normal games, a lot of contracts.

To optimize your game score you should:
- Make more AAA games with bigger team and port them to compatible platforms. Since a gameport score is based on its required points, you will make tons of points with a single AAA than with 100 indie games.
- Organize more conventions (ou got only 2 convention center, you can make more)

On the bright side:
- You unlocked all the game genre
- You implemented all the digital store features

**Comment by ea76** [comment]
are you looking right game? 1.28 is my previous game not this game

**Comment by ea76** [comment]
how many person should be in AAA team ideally ? is 200 person not sufficient for a single AAAgame?

**Comment by xsellier** [comment]
100 employees are required, but if you assign more they will produce more points, then you port them to other platforms and that is how you achieve 3M + scores

**Comment by ea76** [comment]
ok you are the boss,if scoring is computed like this i cannot say anthing
but i honestly think that this game deserves more point; and i am confused because this latest game score cant be the same as previous game: 1,28M
