### ISSUE TITLE
Suggestion: Pay competitors for exclusivity contracts for consoles. 

### ISSUE THREAD

**Issue by Shadowstitcher11** [binogure-studio/city-game-studio-i18n#603]
Summary - The ability to pay competitors an amount of money so they will upload games on your console for X amount of time.

Detailed Description / Reasoning - I noticed that console owners can contact you from time to time and ask for an exsluvivity deal between you and their console for X amount of it. I think it would be cool if you could negotiate price and for how long similar to how they can do it.

How to balance it (BELOW)

Have a limit on how long you can propose, and a limit for how much money you can offer (mostly like how it works when you ask console owners for permission to make games on their platform)

Overall I think it would be very nice if I could pay competitors to focus on making games on my Console.

**Comment by GGplays** [comment]
VERY GOOD IDEA

**Comment by xsellier** [comment]
I'm working on it, should be out for v1.4.0. You can already try it out on the unstable Steam branch.
