### ISSUE TITLE
Suggestion: Higher buildings

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#606]
The highest skyline able to build = **750m**. Autofurnish create **47** workplaces in this height.
Problem that we need **100** workplaces to create **AAA** game.
So even if administrative staff like producer placed in separate building, we need 3 buildings at least (47+47= 94 + any building 6+ developers)

At the same time, I see buildings higher 750m few times. Not often but it exists on game map

So, my request - please able to build 800m skylines to have 50 workplaces by autofurnish to able have just 2 buildings 50 devs + 50 devs.

750m = 47 wp
650m = 40 wp
600m = 37 wp
500m = 32 wp
450m = 28 wp
400m = 25 wp

**Comment by GGplays** [comment]
Signed

**Comment by xsellier** [comment]
This limitation was due to poor optimization. Since I optimized it lately, I can change that. It might be aprt of the v1.1.0

**Comment by FolioNov9m** [comment]
It's great news! Many thanks!

Yeah for now I see building 900m+ even! 👀

**Comment by FolioNov9m** [comment]
is it possible to type a number manually?

![image](https://user-images.githubusercontent.com/80094976/122682475-34a61800-d202-11eb-83e3-50131138c2cc.png)

**Comment by xsellier** [comment]
You cannot but you can use your keyboard to move it (right/left arrow)

**Comment by FolioNov9m** [comment]
> You cannot but you can use your keyboard to move it (right/left arrow)

oh thx its useful too!

Arrows don't working, but mouse scroll is
