### ISSUE TITLE
Suggestion: More End-Game Content

### ISSUE THREAD

**Issue by Killerjosiah908** [binogure-studio/city-game-studio-i18n#607]
**Is your feature request related to a problem? Please describe.**
I think you should add a scale for how long you want the game to go,(e.g. 30 years, 40 years, etc.)
I think you should add hardware feature like: 
2017: Buggy Ray Tracing. Cost: 1,000,000, Cost Per Unit (CPU): $100.  
If you are the first to release a console and implement ray tracing in a game, you get more customers even if the price is a little high.
2019: Ray Tracing: Cost: 2,000,000, CPU: $85
Basically the same as buggy Ray Tracing but Cheaper.
2021: High Quality Ray Tracing: Cost: 5,000,000. CPU: $95
Even though it is more expensive, it will sell relatively good due to it being the only console with good ray tracing but will make it harder to develop for.
2021: Low Quality Ray Tracing: Cost: 1,000,000, CPU: $35
This is the cheaper model, this will sell a lot of units but only if you sell at a loss, developers will be happy but games market will be flooded with low quality games.

2025: Auto Ray Tracing: Cost: 100,000,000, CPU: $50
Every game made will automatically have Ray Tracing, so developers will find it very easy to work with.

2030: Cheap Auto Ray Tracing: Cost: 50,000,000, CPU: $10
This is the exact same as Auto Ray Tracing just cheaper.

Feature: Make it so games have a storage cost, so for instance if you want to make a AAA game on the Atari, you have to pay more for special cartilages. So for instance: 10kb: free 20kb: $1 per copy, 35kb: $2 per copy, 50kb $3 per copy. Etc.
The basic of this feature, is the more stuff you add to a game and the bigger the game the more storage it takes, so if I make a game for the Atari, in 1976 and it has 2 features and is an indie game, it will take 3kb of storage, the default storage is 5-10kb so I don't pay anything per copy.

Sorry if that would be too hard to implement but I feel it would extend the game.

Other Hardware: 1976-1980
Storage types:
 5-10kb: free, 20kb: $1 per copy, 40kb: $2 per copy, 100kb: $4 per copy, 150kb $5 per copy, 1mb $35 per copy. also may add 1kb of ram to any of these to add 1 point to the consoles max, feature base.
 
Software: 
1980: Basic shadows
1984: Basic Sunbake. (doesn't replace shadows)
1988: Complex shadows
1988: Complex Sunbake
1994: Very Basic Fake Ray tracing (replaces both shadows and sunbake but takes longer)
1994: Semi-Realistic shadows
1994: Semi-Realistic Sunbake
2000: Realistic shadows
2000: Realistic Sunbake
2000: Basic Moonbake
2000: Basic Fake Ray tracing (also replaces moonbake)
2006: Realistic shadows
2006: Realistic sunbake
2006: Complex Moonbake
2006: Complex fake Ray Tracing
2008: Semi Realistic fake Ray Tracing
2009: Semi Realistic Moonbake
2010: Very realistic shadows
2010: Very realistic Sunbake
2010: Realistic Moonbake
2011: Realistic fake ray tracing
2013: Very realistic moonbake
2015: Ray Tracing Cutscenes (non fake)
2017: real time Raytracing
2019: Easier real time ray tracing
2021: High Quality Ray tracing, 
2021: Low Quality ray tracing
2025: auto raytracing (adds no time)

**Describe alternatives you've considered**
If this stuff is too complex to add to the game consider changing the names and years to make it less complex. I think a storage system at least for beginning content would be awesome.

I want to thank everyone who took the time to read my suggestion, I love the community because you are the reason consoles are added and such, I also love the developer for being so active with the community.

**Additional context**
I think you should be able to make multiple consoles at once, with different specs and make the same game on both (kinda like the xbox series S and X.)

Suggestion by, HardSoft Animation Studios.

**Comment by xsellier** [comment]
Thanks for the suggestion. Just added procedurally generated conventions for post 2020.

**Comment by xsellier** [comment]
A lot items have been added post 2020. Closing this ticket, thank yo ufor the suggestion!
