### ISSUE TITLE
Suggestion: Game Engine New Feature

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#608]
I mean this features:

![image](https://user-images.githubusercontent.com/80094976/117978335-6cd05600-b33a-11eb-8a4b-40e0bd3029c6.png)

- **customizable weapons** - 1999 (not sure about year), Compute capabilties: 4 Graphic capabilties: 1 (or something like this / your opinion)
- **visual weapon changes** - 2003 (or different), Compute 2 (4 - ?) Graphic - 4 (or different)

These features by hierarchy, like

![image](https://user-images.githubusercontent.com/80094976/117979452-963db180-b33b-11eb-95e5-8c42ac979f42.png)

Feel free to change everything in this 'conception'

Cheers!

**Comment by FolioNov9m** [comment]
More Features:

- **alternate ending** (compute cap. 4 ? ) >>> **alternate story** (compute cap. 8 ? ) >>> **interactive story** (compute cap 10 ? )

_Alternate ending - a small difference like ending of Jedi Academy, Far Cry 4-5, Prey, etc._
_Alternate story - bigger case like Witcher 3 factors or Until Dawn_
_Interactive story (not sure about name) - huge case like Detroit or Baldur's gate, etc._

_If you don't choose anything, it will be classic line story with no alternative_ 👍

- **Button Cheats >>> Console Cheats**
- **AI partner(s)** - like Sam in Uncharted 4, few chars in Last of Us, etc.
- **Side quests**
- **Active Pause**
- **Craft System**
- **Random generated levels (environment)**
- **Interactive environment** _(AI could use tables and other as cover (F.E.A.R.) , Player could use objects to kill (Hitman, Dark Messiah of M&M), Global map is not a 'table' but have rivers, mountians as real objects, etc_
- **Enemies legion** - _a lot of enemies like Left 4 Dead, Serious Sam, Painkiller. This is a specific feature which need a focus by devs_
- **digitized actors** _(L.A. Noire and later). I mean a real focus for actors, facial expressions, famous faces. etc.
But many games dont use this feature still and many genres never will_
- **New Game +**

**Comment by GGplays** [comment]
Its a good suggestion

Atte: Engine Features (mod) Creator

**Comment by FolioNov9m** [comment]
- 2.5d feature
- 2d isometric feature
;)

**Comment by xsellier** [comment]
Nice suggestion,
You can already implement them by using the modmaker:
https://modmaker.city-game-studio.com/

This part:
![image](https://user-images.githubusercontent.com/6616005/118444823-efb43080-b6ed-11eb-9120-7bc478f11039.png)

**Comment by FolioNov9m** [comment]
thanks, I missed this case

**Comment by FolioNov9m** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2490100031
