### ISSUE TITLE
Suggestion: An option to disable a rather long mail animation

### ISSUE THREAD

**Issue by ghost** [binogure-studio/city-game-studio-i18n#609]
**Is your feature request related to a problem? Please describe.**
It can be annoying to have to wait for new mails to appear in the upper right corner after hearing the notification sound.

**Describe the solution you'd like**
An option in the game settings to turn off animation for mails, or maybe just generally make it faster.

**Describe alternatives you've considered**
I haven't thought of any alternatives.

**Comment by ghost** [comment]
Same goes for animation when discarding a mail (right click for example) - other mails "bounce" so you can't right click a few times to discard all mails without having to wait

**Comment by xsellier** [comment]
I'm here, it is going to be implemented no worries!

**Comment by xsellier** [comment]
So I reworked those, and it should be part of the net major update, ie within few days.
