### ISSUE TITLE
Bug: Features generation

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#613]
Are you sure that limitation of Features generation is active?

Consoles like Handboy (1989) 
![image](https://user-images.githubusercontent.com/80094976/118467966-f30ae480-b70c-11eb-8c57-bf4b569b685d.png)

and Neo-Ceo (1990)
![image](https://user-images.githubusercontent.com/80094976/118468028-01f19700-b70d-11eb-9bec-48b6c9069f69.png)

supporting 3d 32 bit graphics which able in 2001 only. 
Also I test new engine features from mod and they available for all consoles too, despite I set high generations

**Comment by xsellier** [comment]
feature generation is not a limitation. It helps the game to compute the game score.
Let's say you've made an engine with a gen 9 feature in 1990, then it is going to expect you to make a 9th generation game (meaning you'd better don't do that unless you want the game to become harder).

But there is a way to make the game easier, make a 1st generation feature that cost pretty much nothing to dev but uses enough CPU/GPU, then the game is going to get a bit easier.
