### ISSUE TITLE
Suggestion: List your studios - CANCEL ALL

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#615]
I used button to 'select all' when created an AAA games.
I need to choose one studio only. Could you make please something like

If all studios are selected already, 'select all' = cancel all?
I play by many studios and the easiest way to cancel all before new selection

![image](https://user-images.githubusercontent.com/80094976/119509255-27b81500-bd79-11eb-95bd-a25579478f5f.png)

**Comment by xsellier** [comment]
Implemented on my machine, might be available later today or this week

**Comment by FolioNov9m** [comment]
perfect! The ticket can be closed :)
