### ISSUE TITLE
Suggestion: Allow research of engine technologies and console components

### ISSUE THREAD

**Issue by GodOf1ce** [binogure-studio/city-game-studio-i18n#618]
Instead of simply unlocking components as years pass, allow studios to research components and technologies at any time in the game as long as the previous tech has already been unlocked. Also adjust ratings to account for advanced tech and allow players to buy/sell component research to other companies. This would add a new element to the game and reward players for investing time into developing their own technologies in advance.

**Comment by xsellier** [comment]
Hey

Thank you for the suggestion but it's been made like that by choice, it is a design choice, and I'm not willing to change that.
Closing.
