### ISSUE TITLE
Suggestion: Conventions after endgame

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#622]
I like CGS and play even in 2030s. There are no many new activities, so could you please return generate conventions after game is over? Just the same, which existing in final year?

**Comment by xsellier** [comment]
Thank you for the suggestion.
It looks like this one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/583

It's about procedurally generating new conventions and platforms for after year 2020.
Closig this ticket since it's attached to the other one.
