### ISSUE TITLE
Suggestion: Rework competitor (let them grow faster too)

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#626]
Don't found any mentions of - Rework competitor (let them grow faster too) in Github, only TODO list in Discord.

Feedback about competitors.
the obvious disadvantage is bad games. I shared in May screenshot of my console, where ~10 games of score 90-100+ of my studios and one game score ~65 of competitor. I would like to see more activity, especially when playing with mods, when competitors are 30+

Interrelated issues:
- poor staff. I bought studios for expansion. And I waited that after integration I will have many new employees from competitor, which ready to work. But they so poor that I fired them all.
**Needs - increase competitor staff quality and number of. I bought competitors after 20-30 ingame years and there are just 15-20 persons then I have 200 without any problems.**

- Competitor don't buy buildings. It's logical continuation of issue - no games, no staff, no money - no buildings. Competitors using small offices. Takeover of competitors is started in 2010s or later only.

- Competitors don't poaching my employees (is it possible? Player could do this, vice versa?)

More rival, more strong competitors, more activity please :) 

I have few ideas for competitors but probably keep them for CGS2 :)

Advanced question of rework this part. Competitors added by mod maker automatically improved too after rework will be released?

**Comment by GGplays** [comment]
Cgs 2?

**Comment by xsellier** [comment]
It is done!
