### ISSUE TITLE
Suggestion: Yearly financial overview

### ISSUE THREAD

**Issue by Le-Captain** [binogure-studio/city-game-studio-i18n#632]
This would provide you with just a little bit more financial insight (which isn't necessary, but always fun in a simulation game).

Example: https://imgur.com/a/adXeBjC

And when selecting years, the months would instead be the numbers for each year.

**Comment by xsellier** [comment]
Something like that?
![image](https://user-images.githubusercontent.com/6616005/152515474-906240bf-04a2-470c-be72-1878dc52579c.png)

It's going to be part of the v1.6.0 update ;)

**Comment by Le-Captain** [comment]
Awesome man! You just giving with this game!
