### ISSUE TITLE
Suggestion: Console marketing campaign

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#634]
Add a specific marketing campaigns for consoles to send devkits to ompetitors so they *might* release games on your console.
This suggestion might come with the v1.2.0 (or 1.3.0 no sure yet).

**Comment by xsellier** [comment]
Implemented in v1.4.0

**Comment by GianluPlay** [comment]
1.4

**Comment by xsellier** [comment]
You can try it out already if you switch to unstable Steam branch.
