### ISSUE TITLE
Suggestion: Remakes of Older Games

### ISSUE THREAD

**Issue by Saputo228** [binogure-studio/city-game-studio-i18n#635]
Can you make it so if you have a much older game that was a hit and you have made sequels of or have not made sequels of, Make it so you can go back to it and make a Remake or Remaster of the game. for the fans who loved it all those years ago.

Like for Example Diablo 2. 
Now it is 2021 and we have Diablo 2 Remastered.

I think it would be a nice feature to have, instead of making a sequel and haveing it be like it was the same tech as before so it is not as good kind of thing.

**Comment by xsellier** [comment]
Thank you for the suggestion. Since it has already been made, Im linking the original ticket and closing this one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/351
