### ISSUE TITLE
Suggestion: Tooltips for the Advanced Start options

### ISSUE THREAD

**Issue by Manello** [binogure-studio/city-game-studio-i18n#639]

**Comment by xsellier** [comment]
May you add some description please?

**Comment by Yorunetsu** [comment]
> May you add some description please?

I think it's about mouseover tooltips so that you can hover over menu items like "Keep hints" and see what they mean.

**Comment by xsellier** [comment]
It's been added o the game in v1.7.0 I think:
![image](https://user-images.githubusercontent.com/6616005/176127423-0b233521-272f-45d5-a3f2-67b5a62614b7.png)
