### ISSUE TITLE
Bug: PT-BR Translation with a mixed word from PT-PT translation.

### ISSUE THREAD

**Issue by Eduardo-Junior** [binogure-studio/city-game-studio-i18n#641]
I was digging through the PT-BR translation file to correct some errors I found and realized that even though the translation inside the file is correct, the game displays the translation from the PT-PT file for this specific word.

"Consola" should be displayed as "Console".

This extends to the following labels as far as I can tell (Better make sure it's not happening to every "Console" mention though):

LABEL_CUSTOM_CONSOLE
LABEL_PLATFORM_HANDLED
 LABEL_PLATFORM_CONSOLE

![image](https://user-images.githubusercontent.com/45540161/130338849-3abf0957-2f95-4458-bc87-107a4255a410.png)

![image](https://user-images.githubusercontent.com/45540161/130338857-2c361dfd-4e3e-4e8c-a30a-2eb6e7d02645.png)

![image](https://user-images.githubusercontent.com/45540161/130338896-21818e68-3756-4f5a-8672-cceb5f447a2a.png)

Although both could be considered right for portuguese speakers, brazilians rarely or never use the word "Consola" when talking about a console. It's a really small issue, but there's a difference when comparing the two languages :sweat_smile:

**Comment by xsellier** [comment]
Submitted an update just now, should fix everything thanks to your PR. Thank you!
