### ISSUE TITLE
Suggestion: Dark Mode for bright UI

### ISSUE THREAD

**Issue by ghost** [binogure-studio/city-game-studio-i18n#642]
**Describe the solution you'd like**
A button that you can toggle so the UI becomes dark and doesn't blind you.

**Comment by xsellier** [comment]
Nice suggestion already been made (I mean it is not called dark mode but it is really close to what you describe).
So I add a link and close this ticket for duplication:
https://github.com/binogure-studio/city-game-studio-i18n/issues/544
