### ISSUE TITLE
Games whose main platform has been discontinued cannot be released even after port

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#653]
**Describe the bug**
Once you've finished developing a game, if the platform the game was originally developed on gets discontinued, you cannot release the game anymore even if you ported it to other platforms.

**Additional context**
In one of my games, I started making a console in 1998, by the time I had finished developing enough games for it, in 2000, I realized I poorly timed this new console, as between 1998 and 2000, a series of powerful new components became available.

As I wanted a console I could make games on for the next 6 years or so, I judged the best course of action at that point was to abandon my already outdated console project and make a new 2000 era console on which I would port all the games I made for the obsolete console and then release. 

So I did just that. However, halfway through 2000, as my new console was ready and all my games had been ported to it, and as I was getting ready to release everything, everything fell apart. Naturally, I needed to halt the production of the previous obsolete console (that had not even been released) before releasing the new one, so I did just that. However, when doing so, all ported games became un-releasable, saying that the obsolete console was not available and thus I could not release the game, despite it having been ported. 

This resulted in, of course, a huge money loss, but most importantly a heavy hit to my motivation, as I had worked hard to make such a large console launch.

**Comment by xsellier** [comment]
Hey,

Sorry for the late answer. That's not a bug but a design choice.
Otherwise you could simply port games fro 1976 on playstation in 1998 for example.
So, once the main platform is discontinued, you cannot port the game on any other platform. On t he bright side tho, you can make a remake of your old games.
