### ISSUE TITLE
Backwards compatibility on platforms

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#659]
In real life, we have the wonderful thing that is backwards compatibility, I realize you already have some sort of compatibility system between platforms when porting, however, I think it's just not deep enough.

# Backwards compatibility for custom consoles

![backward-compatibility-on-custom-consoles](https://user-images.githubusercontent.com/25114435/131826099-54e79d1d-038b-4b16-ae7f-fa4272f881ed.png)

For your own consoles, you can enable backwards compatibility, at the cost of greatly extending the console's development duration. It would also only work with consoles of the same type, thus you cannot make a home console that is backwards compatible with your handheld console.

# Backwards compatibility for regular consoles

Backwards compatibility on regular consoles should only exist where their real counterparts had them, like the PS5 with PS4 games and such.

# Bonuses

I first thought that backwards compatibility should make all the games you made on the previous console automatically available to the new one, but that might just become too powerful and hard to implement as it'd skip the porting process. 

Instead, I think it should give a massive porting speed bonus to games from the previous console to the next console, reducing the porting time to 1-2 weeks at most. 

On top of that, it would make competitors more likely to make games for your console knowing they might also work on the next generation you will do. 

# Restrictions

To prevent it from getting out of hand, backwards compatibility should only work with games of the previous generation, thus while games made for Windows 7 will work on Windows 8, and games for Windows 8 will work on Windows 10, games for Windows 7 will *not* work on Windows 10. Perhaps you could still get a porting speed bonus, but a much smaller one.

**Comment by xsellier** [comment]
Let's work on that feature
![image](https://user-images.githubusercontent.com/6616005/213443931-d9d315a2-351c-40b9-8114-6d9adfe08691.png)

**Comment by xsellier** [comment]
This's been implemented.
