### ISSUE TITLE
Suggestion: Publish AAA/Big game offers

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#663]
Avoir la possibilité de modifier la taille du jeux en indie ou AAA ou gros sur les offre d’édition.
Have the option to change the size of the game to indie or AAA or big on the edition offers.

**Comment by xsellier** [comment]
Duplicate of this ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/215
