### ISSUE TITLE
Suggestion: Known developpers

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#664]
Pouvoir engager des développeurs connu qui nous donne un boost sur les ventes de jeux ou autre.
To be able to hire known developers who give us a boost on sales of games or other.

**Comment by xsellier** [comment]
Thank you for this suggestion.
It's going to be aprt of the v1.6.0 which is already available on the Unstable Steam branch. Closing it.
