### ISSUE TITLE
Suggestion: Subscription for Digital store

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#666]
Pouvoir mettre en place un abonnement sur le magasin dématérialiser et mettre des jeux dedans.
Be able to set up a subscription on the dematerialize store and put games in it.

**Comment by GianluPlay** [comment]
It would be cool

**Comment by xsellier** [comment]
Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/531
