### ISSUE TITLE
idée et suggestion pour le jeux - idea and suggestion for the game

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#667]
Avoir la possibilité d'acheter partiellement un entreprise concurrente.
Have the option of partially purchasing a competitor's business.

**Comment by PwaPois** [comment]
Cela est déjà dans la roadmap pour la mise à jour 1.4.0 https://github.com/binogure-studio/city-game-studio-i18n/projects/2#card-59015559
