### ISSUE TITLE
Suggestion: Studios become off-shoot

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#668]
Avoir la possibilité d'engager un directeur pour un de nos bâtiment pour qu'il soit auto gérer, et qui nous face gagner de l'argent ou en perdre en fonction des publications de jeux qu'il font.
Having the possibility of hiring a director for one of our buildings so that it is self-managed, and who we face to earn money or lose it depending on the game publications they make.

**Comment by xsellier** [comment]
Duplciate of this ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/409
