### ISSUE TITLE
Suggestion: Pay competitor to publish games on your console

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#669]
Payer des concurrent pour qu’il publie des jeux en exclusivité sur notre console et avoir la possibilité de vendre et négocier la licence sur la console.
Pay competitors to publish games exclusively on our console and be able to sell and negotiate the license on the console.

**Comment by xsellier** [comment]
This should be part of this ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/634

Closing tagging as duplicate.
