### ISSUE TITLE
Suggestion: Change last year of CGS (2020) for 2025

### ISSUE THREAD

**Issue by II-Hitman-47-II** [binogure-studio/city-game-studio-i18n#670]
Augmenter la date de fin du jeux car si on ajouter en mod exemple une console en 2025 elle n'apparait pas.
Increase the end date of the game because if we add a console as an example in 2025 it does not appear.

**Comment by xsellier** [comment]
En fait no peut ajouter des consoles après 2020 sans probleme, ceci n'a pas besoin d'être implémenté.

**Comment by xsellier** [comment]
en fait, je viens de le faire. L'année de fin sera en 2025, applicable a partir de la v1.9.0 qui devrait sortir dans quelques semaines normalement.
