### ISSUE TITLE
Bug: Score over 2 000 000 000 are not stored onto Steam leaderboard

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#68]
Score over 2 000 000 000 are not stored onto Steam leaderboard

**Comment by johan-buret** [comment]
What's not to love about 32-bits signed integers ?

**Comment by xsellier** [comment]
I wish steam leaderboards handle 64bits integer

**Comment by xsellier** [comment]
Finally fixed with v0.34.0
