### ISSUE TITLE
Suggestion: Creating Launch Titles for Custom Consoles

### ISSUE THREAD

**Issue by outlawtorn316** [binogure-studio/city-game-studio-i18n#680]
My suggestion is a simple one really, much like how we can create games for consoles that have not launched yet, I find it odd that we cannot do the same with consoles that we ourselves are developing.  It's a bummer that for the first year or two of my console's life it's sales are stagnate as I rush to release and produce titles to give consumers a reason to buy my console.  

It would be really handy to have several titles in development as my R&D office works and finalizes the console, and just how it works for other consoles, as soon as it's launch day, the option to release the games would unlock.

**Comment by PwaPois** [comment]
You can do the same. Once you've finished developing your console, you can start developing games for it. You do not have to release your finished console right away.

**Comment by xsellier** [comment]
Implemented in the latest version.
