### ISSUE TITLE
Suggestion: An "are you sure" prompt when cancelling a game. :(

### ISSUE THREAD

**Issue by XViper123** [binogure-studio/city-game-studio-i18n#682]
**Is your feature request related to a problem? Please describe.**
I just accidentally cancelled my first AAA game, when it was about 90% complete, because I wanted to reassign an idle studio to help complete. *poof* it's gone.

**Describe the solution you'd like**
For there to be a prompt of "are you sure"? when choosing to cancel a game. I expect it doesn't happen too often, so I don't think it would be particularly annoying. (in contrast to what just happened to me) :(

**Additional context**
I thought maybe the "auto-save" would help me. So I went to quit the game, so I could reload the last save.... and it saved the game! NOOOOOOOOoooooooooooooo!!

**Comment by xsellier** [comment]
Hey,

it's there now (3 years later but...)

**Comment by XViper123** [comment]
Wow, I had forgotten I even raised this! Amazing never the less. Huge respect! Might reinstall this and give it another whirl 😁👍Get Outlook for AndroidFrom: Xavier Sellier ***@***.***>Sent: Wednesday, October 9, 2024 9:48:59 pmTo: binogure-studio/city-game-studio-i18n ***@***.***>Cc: XViper123 ***@***.***>; Author ***@***.***>Subject: Re: [binogure-studio/city-game-studio-i18n] Suggestion: An "are you sure" prompt when cancelling a game. :( (#682)
Hey,
it's there now (3 years later but...)
