### ISSUE TITLE
Bug: Studio Value is Higher than Competitor Buyout Price

### ISSUE THREAD

**Issue by PinkGeeRough** [binogure-studio/city-game-studio-i18n#685]
**Describe the bug**
When buying out competitors, you gain a large portion of fans as well as their studios. If you sell the studios you just earned, you make more money than you spent in purchasing the competitors. Income/Expense graph attached as screenshot.

**To Reproduce**
1. Check Buy Price of Competitor
2. Buy out the competitor
3. See value of new studios
4. Sell Studios
5. Be Richer?

**Expected behavior**
Gained studios should be either rented (and therefore no profit made from selling them), or alternatively, the buyout price needs to include the studio value for balancing purposes.

**Logs**
[citygamestudio-5.log](https://github.com/binogure-studio/city-game-studio-i18n/files/7247401/citygamestudio-5.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/91364041/135168294-6d308c39-0b61-4c13-8fca-419c00a96df3.png)

**Comment by xsellier** [comment]
Hey thank you, just added it, it will be part of the next major update ETA end of october.
