### ISSUE TITLE
Suggestion: Improve or make MMOs

### ISSUE THREAD

**Issue by AmateurMoth** [binogure-studio/city-game-studio-i18n#686]
I wish you could add a MMO slider next to the Online Multiplayer to be able to pick between the two, and also be able to expand on it , with the MMO slider on, instead of what Online Multiplayer has, it could have unique features for example a MMORPG can have new classes or a MMO Drive is able to get new customizations and cars, be able to schedule when content or big patches come out for the base game and expansion packs

And also maybe add a bit of an event where, depend on how good the devs are, there can be a chance that some kind of content fails or succeeds and maybe be able to fix that or just let it go

These are just examples but I would love that there was an MMO section and be able to expand on it and same with making Expansion Packs for that MMO instead of what we can do after a game releases with Online Multiplayer and what it can only do as well

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestions. Regarding MMO you can already make them in City Game Studio. When you make an online game, you need servers, then it is up to you to make it an MMO. As soon as you make a game online, you can think as it is an MMO.

Regarding expansions packs, you can publish DLCs and/or Free updates.

Regarding your suggestion, I have a couple of questions:
- What does it bring to the gameplay?
- How would you like to implement MMOs?

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
