### ISSUE TITLE
(cosmetic suggestion)Adding images to personalize a game

### ISSUE THREAD

**Issue by khorneflakez** [binogure-studio/city-game-studio-i18n#687]
This is something Mad Games Tycoon *kinda did. Based on how advanced your game was, it would assign you a relevant image... Problem was though, every new game would eventually have the same image.

So here's my suggestion: Please let us import images that we can assign to our game, so we can further personalize them.

**Comment by xsellier** [comment]
Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/515
