### ISSUE TITLE
Suggestion: Dark Mode Option for CGS UI

### ISSUE THREAD

**Issue by ThisNekoGuy** [binogure-studio/city-game-studio-i18n#688]
**Is your feature request related to a problem? Please describe.**
This isn't a particularly serious issue but a Dark Mode UI for the game would be greatly appreciated to avoid eye strain when playing for extended periods; it's one of the main reasons why I don't return to the game too often - most of the UI is pretty bright

**Describe the solution you'd like**
An optional Dark Mode for CGS's UI

**Describe alternatives you've considered**
There isn't an alternative solution to the issue that I've been able to come up with

**Additional context**
The majority of the UI is bright white and, while not necessarily bad in design, isn't (personally) preferable when a lot of play time is in these bright UI screens

**Comment by xsellier** [comment]
Added to the usntable Steam branch, should be out on Steam the 21st February 2022.
