### ISSUE TITLE
Suggestion: Consoles HAVE to use a certain engine / certain part of an engine.

### ISSUE THREAD

**Issue by FoaxZed** [binogure-studio/city-game-studio-i18n#689]
I'm making a mod which has a VR headset in it and I've noticed that it would work better if it required you to use an engine and / or engine components. For example, if you wanted to use this VR headset, you'd either need to use its original engine or incorporate features, e.g VR Graphics. It would be required for the headset and would be automatically enabled. I feel that this would make it feel a bit more immersive.
This could also work with consoles, e.g if a company wanted to make it that you HAVE to use their engine or make it that your engine has compatibility for the console.

**Comment by xsellier** [comment]
Hey,

Thank you for that suggestion.
I'm gonna have to tell you that a console implements API such as OpenGL ou Vulkan, or DirectX, but a console doesn't deliver/use any engine at all. 
For exemple, when you make a game using godot Engine,unreal Engine or Unity3D, you can publish those games on any console (Ps4/PS5/XBoX or PC...).

Closing this ticket.
