### ISSUE TITLE
If you click on the finances page right as a game releases you cannot get out of it.

### ISSUE THREAD

**Issue by dillyo09** [binogure-studio/city-game-studio-i18n#69]
I click on the page that shows the fiances(it has the bankrupt button on it), and I couldn't get out of it because a game released.

**Comment by xsellier** [comment]
Hey @dillyo09 ,

I spend the last 15 minutes trying to reproduce the issue, may you please send a screenshot?
Because, if you don't have enough money, you'll have only the "bankrupt" button and nothing else. Unless you sign a mortgage contract (right part of the screen).

**Comment by dillyo09** [comment]
I think I said about I was trying to say wrong, If you open the screen that those are on while a the reviews popup you cannot close that screen.

**Comment by xsellier** [comment]
Sorry, I cannot reproduce that behavior, I tried a lot of time.
Is it possible for you to record it please? (just to be sure that I d othe right thing)

**Comment by xsellier** [comment]
Financial panel has been reworked, this should not happen anymore
