### ISSUE TITLE
Bug: Ad popup and Ad Banner activate the wrong revenue stream

### ISSUE THREAD

**Issue by PinkGeeRough** [binogure-studio/city-game-studio-i18n#690]
**Describe the bug**
I published a game with just "Ad Banner", but I get revenue stream for "Ad popups only"

**To Reproduce**
1. Finish Creating a Game
2. Tick "Ad Banner"
3. Keep "Ad Popup" unticked
4. Release
5. View Financial Tab

**Expected behavior**

**Logs**
Attach log files to this ticket:
[citygamestudio-9.log](https://github.com/binogure-studio/city-game-studio-i18n/files/7271656/citygamestudio-9.log)

**Screenshots**
Screenshot 1: Financial Tab (Ad popup revenue)
![image](https://user-images.githubusercontent.com/91364041/135721497-f93ae801-f3ae-485f-8df3-79121ba40bab.png)

Screenshot 2: Game Details (Ad popup disabled, Ad banner enabled)
![image](https://user-images.githubusercontent.com/91364041/135721553-6b04fd5c-94e9-4dce-9aa0-14c70c4384cb.png)

**Comment by xsellier** [comment]
Thank you for the report. Just fixed it in the unstable steam branch
