### ISSUE TITLE
Mod Maker Suggestion: Minus CPU/GPU and Generation 8

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#694]
Example: DiretcV 14 8 Generation -20 CPU -5 CPU

**Comment by xsellier** [comment]
Let's be honest a technology won't _give_ more power, but will use less power/capacity.
I mean you cannot download any RAM can you?

**Comment by GianluPlay** [comment]
Atleast can we have a generation 8 in mod maker?
