### ISSUE TITLE
Seasons and Battle Passes

### ISSUE THREAD

**Issue by IraqLobster34** [binogure-studio/city-game-studio-i18n#696]
I think adding season mechanics would be a good idea. We can choose the length of the season and the number of levels in the battle pass. For example, a season lasts 2 months and there will be 100 levels in the battle pass. We can also change the price of the Battle Pass and the value of the rewards in it. I think that would greatly diversify the game.

**Comment by xsellier** [comment]
Closing in favor of this ticket (duplicate of):
https://github.com/binogure-studio/city-game-studio-i18n/issues/531
