### ISSUE TITLE
Suggestion: City Game Studio port to a mobile

### ISSUE THREAD

**Issue by Zahamare** [binogure-studio/city-game-studio-i18n#698]
I was playing City Game Studio on my PC, when I started to think. The interface is not so hard to understand and the game itself would be cool to see on the phone, like Game Dev Tycoon. 
I hope this idea will be done, I really want to see the game on mobile and I really enjoy playing in it

**Comment by xsellier** [comment]
Thank you for the suggestion, it is a duplicate of : https://github.com/binogure-studio/city-game-studio-i18n/issues/604
