### ISSUE TITLE
Suggestion: Ability to add custom consoles for a game.

### ISSUE THREAD

**Issue by FoaxZed** [binogure-studio/city-game-studio-i18n#699]
When making a game, just before you release it, you can add a custom component. This would work well for rhythm games and could potentially help with money and fans. You could also release a console with a component, so you could make your own Kinect. You can also make custom looking components in the mod maker, so that users can get more choices.

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion.
However I need to understand, what does it bring to the gameplay exactly? Cant you already do something similar in CGS?

**Comment by FoaxZed** [comment]
It can potentially bring in more income and allows for more engine features. If it's constant, you might lose fans. This is basically suggesting you can do something like make the Wii Mario Kart Wheel. It will also add some new engine features.

**Comment by FoaxZed** [comment]
Also I think it's a good idea to mention that this isn't like the controller you can choose for consoles, just a controller for games / series of games.

**Comment by PinkGeeRough** [comment]
I think instead of just adding consoles, you add accessories, like the Mario Kart Wheel, or like Pokemon do with pokeball throwing sensors. However they seem to be more console add-ons rather than just game.

Edit: Like an exclusive game/series add-on to a console

**Comment by FoaxZed** [comment]
> I think instead of just adding consoles, you add accessories, like the Mario Kart Wheel, or like Pokemon do with pokeball throwing sensors. However they seem to be more console add-ons rather than just game.

Yea, that's what I meant. Accessories for your game.

**Comment by FoaxZed** [comment]
I'm just going to close this an explain this in another suggestion.
