### ISSUE TITLE
Suggestion:  Add Japanese

### ISSUE THREAD

**Issue by shimenawa** [binogure-studio/city-game-studio-i18n#706]
Greetings.

I'm not a game developer, but I'm developing software in Japan.
I've seen this game on a game article site before, and I'm enjoying it in English, but can I help translate it into Japanese so that Japanese people can enjoy it?

**Comment by PwaPois** [comment]
This repository is specifically for this purpose, you can find the instructions on how to translate at https://github.com/binogure-studio/city-game-studio-i18n#readme 

The developer will add your translations to the game once you're done and have sent a pull request with the new .yaml files.

**Comment by xsellier** [comment]
Hey,

Welcome, and thank you for the suggestion.
So far there are 2 ways to add new languages.
1. Via the modmaker ( https://modmaker.city-game-studio.com ).
2. By forking this git repository and publishing a `jp.yml` file.

In both cases, you need to first duplicate this file:
https://github.com/binogure-studio/city-game-studio-i18n/blob/master/languages/en.yml

Then using this tool:
https://pikock.github.io/pollly/#!/
You can start translating it into japanese. Once done, download the file and either fork this github repository and publish a Pull Request, or send it via discord or send it via email to this email address: contact@binogure-studio.com

Regards

**Comment by xsellier** [comment]
Traduction will be available with v1.4, ETA end of october.

**Comment by xsellier** [comment]
Added
