### ISSUE TITLE
Suggestion: Can choose how much months a game is on market

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#708]
Can make a game that is gonna be on the market but that create a price for every game created (minus if its published on digital store) for example can make a game that is gonna be for 4 years on market, also can make updates that gives the game more time of live, and can make a game for predeterminates months or years.

**Comment by xsellier** [comment]
Hey,

I dont think I'm gonna implement such feature. I mean you can take off a game from the market anytime you want. So this feature won't add anything to the gameplay.
