### ISSUE TITLE
Suggestion: Is there any way to shorten the game development time?

### ISSUE THREAD

**Issue by tomas966** [binogure-studio/city-game-studio-i18n#711]
Is there any way to shorten the game development time?

I hope that the game development time will be reduced in proportion to the employee's satisfaction or proficiency.

**Comment by GianluPlay** [comment]
If you put the slider settings to minimum you will make a game in a month or two

**Comment by tomas966** [comment]
That way, the quality and scale of the game are lowered.

**Comment by FoaxZed** [comment]
> That way, the quality and scale of the game are lowered.

I think that’s the point. Making development time lower will cause a drop in quality. That’s how it works in the real world, so I think the game wants to mimic that.

**Comment by tomas966** [comment]
In reality, the quality of the product does not depend on the product development period.

A: A product developed and made by geniuses for 3 years.
B: A product developed and made by idiots for 5 years.

Which product would be good?

I think product A will be excellent.

**Comment by xsellier** [comment]
> In reality, the quality of the product does not depend on the product development period.
> 
> A: A product developed and made by geniuses for 3 years. B: A product developed and made by idiots for 5 years.
> 
> Which product would be good?
> 
> I think product A will be excellent.

Sorry to say that but you're wrong. The development time impacts the game's quality by a lot.
There is a very famous quote about a very talented game designer:
http://www.knowyourquotes.com/A-Delayed-Game-Is-Eventually-Good-But-A-Rushed-Game-Is-Forever-Bad-Shigeru-Miyamoto.html

however a development that lasts forver will also make a bad game, if we look at you Duke.

**Comment by tomas966** [comment]
I think your opinion is also right.

However, considering the factor of productivity, wouldn't the same 10 employees have different speeds of completing the development?

**Comment by xsellier** [comment]
if you take 9 women to make one baby, would you be able to make one in a month? (that's an image)

**Comment by tomas966** [comment]
If 10 to 100 people work with the same goal, will it take the same amount of time to achieve the goal?

The duration of pregnancy can also increase or decrease depending on various environmental factors.

**Comment by GianluPlay** [comment]
> > In reality, the quality of the product does not depend on the product development period.
> > 
> > A: A product developed and made by geniuses for 3 years. B: A product developed and made by idiots for 5 years.
> > 
> > Which product would be good?
> > 
> > I think product A will be excellent.
> 
> Sorry to say that but you're wrong. The development time impacts the game's quality by a lot.
> There is a very famous quote about a very talented game designer:
> http://www.knowyourquotes.com/A-Delayed-Game-Is-Eventually-Good-But-A-Rushed-Game-Is-Forever-Bad-Shigeru-Miyamoto.html
> 
> however a development that lasts forver will also make a bad game, if we look at you Duke.

Eventually, a virus is going to enter my PC due to that link
