### ISSUE TITLE
More mod makers Suggestions and Others Suggestions

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#712]
1. A decision of a event can cause the resign of 1 or more employees (Mod Maker)
2. A event that have decisions is obligatory to response (Mod Maker)
3. Deluxes/Definitives/Special Editions for games (Like the mad games system of special, definitive etc etc edition, Game Suggestion)
4. New random event: Rats (Game suggestion)
5. New awards: Best indie game, Best medium game, Best big game, Best AAA Game and Better soundtrack (Game suggestion)

**Comment by xsellier** [comment]
2. The player has 1 month to take a decision, if he doesn't the first action will be choosen by default


For the other suggestions, please create one ticket per suggestion, and explain what it brings to the gameplay.
