### ISSUE TITLE
Suggestion: Fill all empty seats

### ISSUE THREAD

**Issue by FoaxZed** [binogure-studio/city-game-studio-i18n#714]
Just an idea for a cheat code in which if there is a desk that is unoccupied, it will hire a staff member (it will randomly choose what type) and the staff member would go there. I never really play this game with out using cheats so it would be quite helpful as constantly having to employ people is mildly annoying.

**Comment by xsellier** [comment]
A command such like:
`employee autofill`

**Comment by FoaxZed** [comment]
Staff autofill might work better as staff is already part of the command models.

**Comment by xsellier** [comment]
Closing this since it is already available in the upcoming v1.6.0 (unstable steam branch)
