### ISSUE TITLE
Suggestion: Special/Deluxe/Definitive/Collectors Edition

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#715]
Suggestion:
Can make different editions for games, Like The Sins Special Edition cost more (because there is a cost for every copy maked) but have the Original game, DLC's and a guide (For example) or just the game and a DLC, the player choose what contains x edition like Mad Games Tycoon.
What does it bring to Gameplay:
More realism.

**Comment by xsellier** [comment]
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/363
