### ISSUE TITLE
Suggestion: New Awards (revamp GOTY system)

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#716]
New Awards like Best Indie, Medium, Big and AAA Game, this will boost the sales and give you some fans

**Comment by xsellier** [comment]
Hey,

* Does this feature request related to a specific problem?
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
* Please describe all the alternatives you've considered for that specific problem.

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
