### ISSUE TITLE
NICE IDEA

### ISSUE THREAD

**Issue by VelTraher** [binogure-studio/city-game-studio-i18n#72]
- Add the ability to buy shares of a competitor's company. 
- Add the ability to sell their shares to competitors. 
- Add the ability to sell your Games to a competitor. 
- Add the ability to buy games from competitors. 
- Add the ability to sell studios and see what your Studio has done with the game. 
- Add a game sales chart. 
- Add a chart of companies that are on the map, and a chart of small developer studios that you can buy.

1. Fix counting the number of games sold.
2. Correct the marketing company's count when when copies sold on all platforms do not add up.

**Comment by xsellier** [comment]
Let me split those into individual suggestions.

**Comment by xsellier** [comment]
>    * Add the ability to sell studios and see what your Studio has done with the game.
>    * Add a chart of companies that are on the map, and a chart of small developer studios that you can buy.

May you ellaborate?

>     * Add a game sales chart.

There is already one in the game, I don't get it

>     1. Fix counting the number of games sold.

You need to take into account VAT, so revenue does not match with unit sold * price

>     2. Correct the marketing company's count when when copies sold on all platforms do not add up.

It matches with the original game indeed.
