### ISSUE TITLE
Suggestion: Make a DRM-Free version of City Game Studio

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#721]
Get the game on GOG, and as soon as it gets a GO, publish a DRM-Free version on both GOG and Itch.

Requirement:
- Get accepted on GOG first.
https://www.gog.com/wishlist/games/city_game_studio_from_binogure_studio

**Comment by EngineFeaturesOfficial** [comment]
> Get the game on GOG, and as soon as it gets a GO, publish a DRM-Free version on both GOG and Itch.
> 
> Requirement:
> 
> * Get accepted on GOG first.

And a demo on steam?

**Comment by xsellier** [comment]
This version is already available:
https://www.gog.com/game/city_game_studio_a_tycoon_about_game_dev
