### ISSUE TITLE
Suggestion: AAAA games

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#723]
AAAA games, take from 3 to 8 years to develop
Requirements: 150 Employees, 1 Producer, 1 Marketing manager and 35000 fans
Boost of sales requirements: 120000

**Comment by xsellier** [comment]
Such things don't exist IRL.

**Comment by GianluPlay** [comment]
> Such things don't exist IRL.

But if i invent AAAA games, maybe there can be a new type of building to research things like AAAA games
