### ISSUE TITLE
Suggestion: Fan Mades

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#725]
Fans can make Fan Made games inspired in a Game that you launched, demand Fan Mades Games or just leave to them make what they want

**Comment by xsellier** [comment]
Kind of duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/238
This needs to be ellaorated, a single sentence isn't a new feature by itself. There is a template for suggestion please use it.
