### ISSUE TITLE
Suggestion: Employees renounce later years of working

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#727]
How a employee that i bu... hired in 1977 is still alive in 2040

**Comment by xsellier** [comment]
Hey,

* Does this feature request related to a specific problem?
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
* Please describe all the alternatives you've considered for that specific problem.

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
