### ISSUE TITLE
Suggestion: regions

### ISSUE THREAD

**Issue by cwa-gif** [binogure-studio/city-game-studio-i18n#735]
**Describe the solution you'd like**
Would be cool if we had different regions where different genres were popular, and the option to release/make games only for one region/country

**Comment by xsellier** [comment]
Does it differ a lot from your other suggestion?
https://github.com/binogure-studio/city-game-studio-i18n/issues/547

**Comment by cwa-gif** [comment]
no, the old one was marked as incomplete/need to saplit up, so i took what i thought was most important from it and reposted :)

**Comment by xsellier** [comment]
Since this new ticket is cleaner, I'm clsoing this one in favor of: #853
