### ISSUE TITLE
Suggestion: Level of Piracy

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#737]
Every platform has a Level of Piracy from 1 to 5

First Level: This Platform has no piracy, it gonna have 0 impact on the Sales, Example: PS3
Second Level: This Platform has piracy, -1% of sales, Example: PS4
Third Level: This Platform Has Piracy, -3% of sales, Example: Super Nes
Fourth Level: This Platform Has Pîracy, -5% of sales, Example: PS2
Fifth Level: This Platform Has Piracy, -10% of sales, Example: PC

Also there is a new Engine Feature that combat Piracy

This also affect the Development Cost

**Comment by xsellier** [comment]
Hey,

* Does this feature request related to a specific problem?
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
* Please describe all the alternatives you've considered for that specific problem.

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
