### ISSUE TITLE
Suggestion: New Type Of Component

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#740]
Storage Component

Power:
GPU Power, 0
CPU Power, 1 - 10
Storage, 0 - 10 TB

Cost:
Price, 4 - 15
Research Cost, 450 - 8500

**Comment by xsellier** [comment]
Thank you for this suggestion.
It's going to be aprt of the v1.6.0 which is already available on the Unstable Steam branch. Closing it.
