### ISSUE TITLE
Suggestion: Add trends to the main UI

### ISSUE THREAD

**Issue by rzki** [binogure-studio/city-game-studio-i18n#741]
**Is your feature request related to a problem? Please describe.**
It's kinda frustrating to check on game development tab just to check what theme is trending right now.

**Describe the solution you'd like**
Add what theme is trending on right top of the screen

**Describe alternatives you've considered**
Checking what's trending on game development tab, but it's not effective

**Additional context**

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion, this is now part of City Game Studio.
