### ISSUE TITLE
Suggestion: Research Department

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#750]
Function: Research Special Engine Features, Research Genre/Topic Combinations, Research Sliders Combinations, Platform Combinations

Mod Maker: Can unlock Engine Features that requires  the Research Department

Cost:
Special Engine Features: Cost 10.000 - 500.000
Genre/Topic Combinations: Cost 15.000 - 500.000
Sliders: Cost 9.500 - 60.000
Platform Combinations: Cost 10.000 - 100.000
Research Department: 2.500.000

**Comment by xsellier** [comment]
Closing in favor of: https://github.com/binogure-studio/city-game-studio-i18n/issues/261

**Comment by GianluPlay** [comment]
> Closing in favor of: #750

What does mean that

**Comment by xsellier** [comment]
Those tickets are talking about the very same feature, you can click on the link:
https://github.com/binogure-studio/city-game-studio-i18n/issues/261
