### ISSUE TITLE
Suggestion: Console Features, R&D Department and Reviews for Custom Platforms

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#754]
(This can be a replacement for the OS Suggestion)

Console Features, R&D Department and Reviews for Custom Consoles

The Console Features are Researched in the R&D Department, this affects the Reviews for the Console

Example of Console Features: 2 Controllers Support ( X + Cost per Unit, Unlocked at 1982, Basic Feature), 4 Controllers Support ( XX + Cost per Unit, Unlocked at 1990, Basic Features), 2 Fans ( X + Cost per Unit, 0.X + Quality, Unlocked at 1998, Semi-Advanced Feature)

R&D Deparment

Allows you to Research Console Features, Genre/Topic Combinations, Sliders Combinations

Prices Console Features: Basic Features $35.000, Semi-Advanced Features $75.000, Advanced Features $225.000, Super Advanced Features $2.000.000
Prices Genre/Topic Combinations: $50.000
Prices Sliders Combinations: $75.000

Reviews for Custom Platforms

This affect your sales

10-19/100 = -80% Sales
20-29/100 = -60% Sales
30-39/100 = -50% Sales
40-49/100 = -40% Sales
50-59/100 = -30% Sales
60-69/100 = -10% Sales
70-79/100 = -0% Sales
80-89/100 = +10% Sales
90-95/100 = +20% Sales
96-99/100 = +30% Sales
100/100 = +40% Sales

**Comment by xsellier** [comment]
R&D: https://github.com/binogure-studio/city-game-studio-i18n/issues/261
