### ISSUE TITLE
Suggestion: Countries Update (Alternative 2)

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#757]
Can build Studios in different countries, every country and in some cases states has its own taxes, also you can choose for what countries is published your game (there is the option all countries too) and (maybe) every country has a modifier to the game sells (a game priced in 60 dollars are not gonna have to much units sold in venezuela), taxes and game/custom platform modifiers can be only in hard and/or very hard difficulty, or it can be added in medium, hard and very hard difficulty.

**Comment by xsellier** [comment]
Looks like a duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/735
Closing

**Comment by GianluPlay** [comment]
> Looks like a duplicate of: #735 Closing

I dont see the taxes or game sold units modifier in the #735 "Issue"
