### ISSUE TITLE
Suggestion: Mod maker: Edit platform and component

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#760]
Suggestion: Edit Engine Feature, Edit Platform, Edit Component

**Comment by xsellier** [comment]
Thank you for the suggestion, this should be part of the v1.7.0

**Comment by xsellier** [comment]
Only remains the edit engine feature, you can edit platforms and components.

**Comment by xsellier** [comment]
Closing this one in favor of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/804
