### ISSUE TITLE
Suggestion: Game Editions (Rework)

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#773]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can launch a Definitive/Legendary/Special/Standard Edition for a Game

**Describe alternatives you've considered**
Can Launch a Definitive and Standard Edition

**Additional context**
A Definitive/Legendary/Special Edition does not have the same price of the Standard Edition, you can choose the price of the Definitive Or/And Legendary/Special edition, you can also choose if you launch a Definitive/Legendary or Special Edition

**Comment by xsellier** [comment]
Duplicate of #363
Closing
