### ISSUE TITLE
Suggestion: Competitors Games

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#774]
**Is your feature request related to a problem? Please describe.**
Yes, The mod maker should able the modders add IPs to Competitors

**Describe the solution you'd like**
Can "add" games to competitors, like "Game Name GTA, ID of company that will release game 75b5ad7d-cce0-4ca0-acdb-565fc36c0d52, Year 1997, Sales 3.000.000, Platform/s Playstation and PC, Able to port the game to other consoles Yes, Theme GrandTheft, Genre (List of Genres), Score 79"

> > **Describe alternatives you've considered**
Can add games like "Game Name Watch Cats, Year 2010"

**Additional context**
Can add Games to the Game, like add GTA to the Game, or Assassins Creed to the Game

**Comment by xsellier** [comment]
This suggestion is quite neat. And I think I'm gonna implement it.
But I don't think it's gonna be part of the next update tho, I'll try to make it for the next update, but I cannot promise it.

**Comment by xsellier** [comment]
Closing since it's part of the game now.

**Comment by GianluPlay** [comment]
> Closing since it's part of the game now.

What?

**Comment by xsellier** [comment]
O closed the wrong one. I'm glad this one is still open, it'll be aprt of the next update :D

**Comment by GianluPlay** [comment]
> O closed the wrong one. I'm glad this one is still open, it'll be aprt of the next update :D

Oh ok, and thanks for taking the suggestion

**Comment by xsellier** [comment]
And this time, I'm cloding it, since it's part of the game now :)
