### ISSUE TITLE
Suggestion: Can add famous Developers in mod maker

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#779]
**Is your feature request related to a problem? Please describe.**
Yes, The mod maker should able the modders to add famous developers

**Describe the solution you'd like**
Can add Famous Developers, Example: Name Hideo Kojima, Design 50/100, Development 50/100, Polish 75/100

> > **Describe alternatives you've considered**
Can Rename Famous Developers

**Additional context**
Can add famous developers to the game

**Comment by xsellier** [comment]
Should be part of the next update, should be available later today with v1.9.0-rc3, closing.
