### ISSUE TITLE
Suggestion:  Esports for your games

### ISSUE THREAD

**Issue by qwertydelle** [binogure-studio/city-game-studio-i18n#792]
A cool feature for the game you could add is Esports for the games you create it. Something like how Valorant , CSGO, Fortnite and etc. It would be cool to see your games go from a small player base to a huge one with organizations competing with each other. This feature could also increase the life span of your game and if you dont update it once in a while it might die.

**Comment by GianluPlay** [comment]
Fine suggestion

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion. This one has already been made:
https://github.com/binogure-studio/city-game-studio-i18n/issues/319

Closing this one.
