### ISSUE TITLE
Suggestion: In-Game Achievments

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#797]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In-Game Achievements, the Steam achievements but In-Game, also mods can add In-Game Achievements like "Launch a Game with Name: X" or "Launch a Game with Score: X"

**Describe alternatives you've considered**
First alternative: Mods can add In-Game Achievements but there is no "Vanilla" In-Game Achievements.
Second alternative: Mods cannot add In-Game Achievements but there are vanilla achievements

**Additional context**
Just to be able to Add In-Game Achievements in the Mod Maker and to have In-Game Achievements

**Comment by xsellier** [comment]
So, such achievements has to be first validated by steam and require a steam partner account, so it cannot be added to the game.

**Comment by GianluPlay** [comment]
> So, such achievements has to be first validated by steam and require a steam partner account, so it cannot be added to the game.

I said INGAME achievments, not STEAM achievments
