### ISSUE TITLE
Suggestion: Theme panel to the main screen

### ISSUE THREAD

**Issue by Urokuconi** [binogure-studio/city-game-studio-i18n#801]
**Is your feature request related to a problem? Please describe.**

It is frustrating that i have to go in "develop a game" section to have access to theme's tendency

**Describe the solution you'd like**

We could have the same tendency list that we have when we have to choose a theme on the main page or above the sales graphics or every where else on the "main screen !

**Describe alternatives you've considered**

I did not found alternatives

**Additional context**
 I would like that :
![Feature](https://user-images.githubusercontent.com/107409452/173352695-8e5b1633-6272-44f8-b9d9-56f76f835f34.png)
 somewhere we can have constant access to it

PS : I would like to know the sell price and the amount of sales of competitor's games.

**Comment by xsellier** [comment]
Thank you for the suggestion.
It has been implemented and is already available on the unstable steam branch.
Should be released later with the v1.9.0. Closing this ticket.

![image](https://user-images.githubusercontent.com/6616005/176125857-257be83f-20f7-4739-85bb-e61e1eac0c16.png)
