### ISSUE TITLE
Suggestion: Server

### ISSUE THREAD

**Issue by JPITH** [binogure-studio/city-game-studio-i18n#802]
Can we have a type of server like peer to peer server and normal server

**Comment by xsellier** [comment]
Peer to peer doesn't require a server, but for NATing, and normal servers are already available in game.

But adding peer-to-peer games is an interesting idea tho

**Comment by JPITH** [comment]
it will be cool to add peer to peer games

**Comment by JPITH** [comment]
and can't we add game logo or image

**Comment by xsellier** [comment]
It's one suggestion per ticket, and it's alwaysbetter to use the feature template if you want anything to get added to the game:
```
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```
