### ISSUE TITLE
Suggestion: please add complete instant build game in console cheat

### ISSUE THREAD

**Issue by donimuzur** [binogure-studio/city-game-studio-i18n#805]
**Is your feature request related to a problem? Please describe.**
yes, when making a new AAA game with max slider it needed a long time to finish.

**Describe the solution you'd like**
add console cheat to finish in instant

**Additional context**
just add cheat in a console to finish the game making in an instant just like "game-engine complete" in console

**Comment by xsellier** [comment]
Neat suggestion. Should be part of the next update.

**Comment by donimuzur** [comment]
nice.. cant wait

**Comment by xsellier** [comment]
Closing since it should be available later today with v1.9.0-rc3 on the usntable steam branch:
![image](https://user-images.githubusercontent.com/6616005/176125018-0e5a9ac7-77a4-4588-9e13-593523725d1a.png)
