### ISSUE TITLE
Suggestion: Apply Devkits to all competitors

### ISSUE THREAD

**Issue by zhyted** [binogure-studio/city-game-studio-i18n#806]
**Is your feature request related to a problem? Please describe.**
It takes a long time especially with mods to apply devkits to all the competitors when making a console.

**Describe the solution you'd like**
add a button that says "apply devkits to all concurrents"

**Describe alternatives you've considered**
not really anything else. just add a button that applies the devkits to all the competitors

**Additional context**

**Comment by xsellier** [comment]
Closing since it's part of the game now.
