### ISSUE TITLE
Suggestion: GOTY

### ISSUE THREAD

**Issue by JPITH** [binogure-studio/city-game-studio-i18n#808]
**Is your feature request related to a problem? Please describe.**
So is about the game after playing the version 1.8.2 and finish the game i notice that  the game of the year is choose between march of two years

**Describe the solution you'd like**
but in real life it's between November of two years

**Describe alternatives you've considered**
maybe i think if you want includes categories of game of the year

**Additional context**

**Comment by xsellier** [comment]
This has been fixed with v1.14.0
