### ISSUE TITLE
Suggestion: In-Game Achievements

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#809]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Same as #797

**Describe alternatives you've considered**
Same as #797

**Additional context**
In-Game achievments are not Steam achievments, so there is a achievments list in the pause menu, mods can also add **IN-GAME ACHIEVMENTS**, not steam achievments

**Comment by xsellier** [comment]
Yup, there is no other achievement than steam/gog achievement. There are goals to unlock the tutoriels, but there is no other achievement than steam achievement. 

I'm on adding new content, but it has to worth the time spent. And I don't think this would worth it, but I might be wrong and you can prove me so by gathering legit upvotes, so I'll come back and implement this feature.

If you want to speed up the implementation of this feature, you can make an animation by yourself of the in-game achievement animation, so I have less work to spend on this feature.

**Comment by GianluPlay** [comment]
An In-Game achievments list works per save, so you can have the achievment "Perfect Game" on steam but not in a new save

An ingame achievments list like the Hoi4 one ![20190316002629_1.jpg](https://user-images.githubusercontent.com/91916681/177079914-690ea144-9dbc-40e5-968a-868fa73109f5.jpg)

Or like the mad games tycoon 2 achievments list that works per save

**Comment by GianluPlay** [comment]
> Yup, there is no other achievement than steam/gog achievement. There are goals to unlock the tutoriels, but there is no other achievement than steam achievement.
> 
> I'm on adding new content, but it has to worth the time spent. And I don't think this would worth it, but I might be wrong and you can prove me so by gathering legit upvotes, so I'll come back and implement this feature.
> 
> If you want to speed up the implementation of this feature, you can make an animation by yourself of the in-game achievement animation, so I have less work to spend on this feature.

Simplified:
Main menu > Achievements tab
Achievement: Mistakes are made
Requirements: Make a 96 months long exclusivity contract with Sega

Save N°1: Achievement completed
Save N°2: Achievement not completed
Steam: Achievement completed

Steam is not related to the in-game achievements.
You can have a million saves, and half of them have all achievements, and the other half doesnt.

**Comment by xsellier** [comment]
As discussed on the discord server, player don't want mods to add new achievement. So this won't be added.
Meanwhile, achievement ain't linked to Steam/GOG anymore, so you can unlock achievement when you start a new game. It is also optional so you can disable it via the option panel.
