### ISSUE TITLE
Additional themes

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#81]
Cyberpunk:
RPG ARPG TRPG
ADV VNovel
Action/FPS

War/Military:
ADV VNovel
Strat/TurnB/RTS
Action/FPS
Simul/Vehicle/Sub

Industrialization:
Strat/TurnB/RTS
Simul/Vehicle/Train/Management/Economy/Government/City-Builder

Everyday life:
Simul
Adv/V-Novel/Interact-Mov/Open-World/Interaction-fic/Chat

Evolution:
Simul/Living-Org/God-Game

Monsters:
RPG/ARPG/TRPG/Dungeon/D-Crawler/HnS/Bea
Casual/Clicker
Living-Org/God-Game

Steampunk:
RPG ARPG TRPG
ADV VNovel
Action/FPS

Transportation:
Simul/Vehicle/Train/Fly/Management/Economy/Government/City-Builder

Cars/Sportscars/Tuning:
Simul/Vehicle/Racing/Driver/Management/Economy

Modern history/Present/Current Time:
ADV
Strat/TurnB/RTS
Action/FPS
Simul/Management/Economy/Government/City-Builder

Extreme Sports:
Simul/Sport/Cars/Driver/Racing

Pets:
Simul/Animals/God-Game/
Casual/Clicker
CPuzzle/Puzzle/HiddenOb

Music:
Casual/Rhythm
Economy

Martial Arts:
Action/Versus-fight/Infiltr
Bea

Made some theme pictures use them if you like em ;)

WAR/MILITARY
![war-mili](https://user-images.githubusercontent.com/48098478/53581245-8338cf80-3b7d-11e9-8714-f57332eef760.jpg)

CYBERPUNK
![cyberp](https://user-images.githubusercontent.com/48098478/53581246-8338cf80-3b7d-11e9-9f69-f9adb0330b91.jpg)

EVERYDAY-LIFE
![everydaylife](https://user-images.githubusercontent.com/48098478/53581247-83d16600-3b7d-11e9-9a2e-09232944ec17.jpg)

EVOLUTION
![evolution](https://user-images.githubusercontent.com/48098478/53581249-83d16600-3b7d-11e9-8449-b484ef4d379b.jpg)

INDUSTRY
![indust](https://user-images.githubusercontent.com/48098478/53581250-83d16600-3b7d-11e9-936d-e7bd72c18c16.jpg)

MONSTER
![monster](https://user-images.githubusercontent.com/48098478/53581251-83d16600-3b7d-11e9-849f-d946d3fb2864.jpg)

**Comment by Typhmus** [comment]
Very nice pictures!

**Comment by Tesba** [comment]
a few bonus pictures ;)

Car-tuning-sportcar
![car-tuning-sportcar](https://user-images.githubusercontent.com/48098478/53682656-23b2ff00-3cf8-11e9-8172-6666276a5b8b.jpg)

Everydaylife/the life
![everydaylife](https://user-images.githubusercontent.com/48098478/53682657-26155900-3cf8-11e9-8c50-bcb36eea4c2c.jpg)

Evolution
![evolution](https://user-images.githubusercontent.com/48098478/53682660-2877b300-3cf8-11e9-93a2-a9b073d89f0e.jpg)

Extremesports
![extremesport](https://user-images.githubusercontent.com/48098478/53682661-2a417680-3cf8-11e9-95be-c31fea258ad5.jpg)

Martial-arts
![martialart](https://user-images.githubusercontent.com/48098478/53682662-2c0b3a00-3cf8-11e9-916d-7a09187a4179.jpg)

Modern/current History/time
![modern-current-time](https://user-images.githubusercontent.com/48098478/53682663-2dd4fd80-3cf8-11e9-9023-7294b93a8c8b.jpg)

Monster
![monsters](https://user-images.githubusercontent.com/48098478/53682664-30cfee00-3cf8-11e9-9359-aa7a74d2a52d.jpg)

Music
![music](https://user-images.githubusercontent.com/48098478/53682672-39c0bf80-3cf8-11e9-8aba-45389c62dc3e.jpg)

Pets
![pets](https://user-images.githubusercontent.com/48098478/53682673-3cbbb000-3cf8-11e9-9f03-9226ee285b8c.jpg)

Steampunk
![steampunk](https://user-images.githubusercontent.com/48098478/53682675-3e857380-3cf8-11e9-9b2c-c73ebe99d210.jpg)

Transport
![transport](https://user-images.githubusercontent.com/48098478/53682676-404f3700-3cf8-11e9-8082-28613a1a2c00.jpg)

**Comment by WayneLegolas** [comment]
That's pretty good.

**Comment by xsellier** [comment]
Some have been added to the theme list:
- Urban
- Military
- Evolution
- Pets

**Comment by xsellier** [comment]
New themes have been added:
- Cyberpunk
- Steampunk
- Transportation
- Music
