### ISSUE TITLE
Suggestion : Add game-port,remake,GOTY  complete in console cheat

### ISSUE THREAD

**Issue by donimuzur** [binogure-studio/city-game-studio-i18n#812]
**Is your feature request related to a problem? Please describe.**
yes, need a shortcut to finish game faster

**Describe the solution you'd like**
add console game-port complete in console cheat

**Describe alternatives you've considered**

**Additional context**

**Comment by xsellier** [comment]
Thanks for the suggestion.
It been implemented and already available on the unstable steam branch:

**__How to switch to the `unstable` Steam branch?__**
> **Open Steam**, **right click** on **City Game Studio**, select **Properties**, select the **Betas tab** and select the `unstable` option from the list.
