### ISSUE TITLE
Suggestion: Add option "Select Studio"

### ISSUE THREAD

**Issue by donimuzur** [binogure-studio/city-game-studio-i18n#813]
**Is your feature request related to a problem? Please describe.**
yes, there is no option to add studio when porting game to other consoles

**Describe the solution you'd like**
add  option "select studio" just like when making a new game

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/20512309/178500396-f7d2a28f-9e73-467b-ab22-5c76f18cc4e6.png)

**Comment by xsellier** [comment]
Included with v1.10.0
