### ISSUE TITLE
Suggestion: Being able to choose the style of a building

### ISSUE THREAD

**Issue by lopesvaz3u** [binogure-studio/city-game-studio-i18n#817]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/82098184/180713441-584a7cdc-3af7-4e36-9448-ca0960b8dd69.png)

When you want to build a new studio you can only choose its name and its surface.

![image](https://user-images.githubusercontent.com/82098184/180714658-26aeccac-6212-41f7-915d-ac9192b6c734.png) 
![image](https://user-images.githubusercontent.com/82098184/180714676-08e4c93e-d47d-415f-84b9-1a99f9bb5017.png)

But others offices exist with several models of size in the city.

**Describe the solution you'd like**

So it would be good to choose the style of the building we want to build.

I know that there are not necessarily all the sizes already in the game and that it would involve some work.

Besides the aesthetic aspect, the player could use it to easily differentiate his different types of buildings if it works like that (dev studio, server room, administration offices).

**Additional context**

We can imagine that modders will add mods with new buildings more or less serious.

**Comment by GianluPlay** [comment]
Great idea

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion. It's been implemented with v1.10.0.
Should be release by August 22nd, 2022.
