### ISSUE TITLE
Name of the game can be blank in LABEL_SALES_HITS_3 in some cases

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#819]
Another bug in the localization, this time one I cannot just make a pull request for: The name of the game is missing for LABEL_SALES_HITS_3; Possibly for the 5 other variations as well. For further context, this game in particular was a third-party one I merely published, and I suspect that may be where the problem is coming from. LABEL_SALES_HITS_DESCRIPTION shows the name properly though.

![image](https://user-images.githubusercontent.com/25114435/181358403-34b05715-ab57-4031-b86f-105bf397f175.png)

**Comment by xsellier** [comment]
Fixed with v1.10.0-rc10
