### ISSUE TITLE
Carry over name to sequel name

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#82]
Quality of life feature:
If you make a sequel of a game, the name should carry over to the name of the sequel you are doing.

E.g.:
Released game: Settlers 1
If you do a sequel of it, the new name should be named Settlers 1, so you only have to change the number and dont have to rename the whole game. Because every sequel has nearly the same name as its predecessor.

**Comment by xsellier** [comment]
Implemented in version v0.17.1
