### ISSUE TITLE
Suggestion: Can select studio when updating a game

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#820]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes i want to freeze an update without cabcelling the update

**Describe the solution you'd like**
Be able to select the studios updating a game

**Describe alternatives you've considered**
I havent cosidered any alternative

**Additional context**
Be able to select which studios are updating a game (for free update and dlc)

**Comment by xsellier** [comment]
haven't though about this one, I'll try to make it happen by next week if I can.

**Comment by xsellier** [comment]
Implemented since v1.10.0
