### ISSUE TITLE
Suggestion: Rework DLCs

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#821]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A rework to DLCs, can select Engine Features when creating a DLC (you can select any engine features except graphical engine features), can select a size Small to Big.

**Describe alternatives you've considered**
Huh... x

**Additional context**
Rework DLCs so they are similar to Remakes and Remasters.
Can select any Engine Feature for the DLC except Graphics Engine Features.
Can select the size of a DLC from Small to Big.
A DLC needs Design, Development and Polish points, the bigger DLC the more points you need.
DLCs can now earn a lot of money, intead of just earning 6k with a 93 score DLC.
You can now make a marketing campaign for a DLC.
DLCs are a Game Seller, meaning that if you release too much quality DLCs for a game, the sales for that game and dlc is going to increase.

**Comment by xsellier** [comment]
Linking this ticket with an already existing one #593
Closing this one tho.
