### ISSUE TITLE
Suggestion: Game Pass

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#822]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A game pass, you need servers to make a service like the Xbox Game Pass or PS Plus, you can offer games for a monthly subscription, you can make offers to your competitors so they increase the catalog of your Game Pass, Game Pass is unlocked in the same year as the digital store.

**Describe alternatives you've considered**
None.

**Additional context**
You can add your own games to your game pass.
You can offer competitors so they put some of their games in your Game Pass.
The price can be from 1 dollar to 120 dollars monthly.
If you have a custom platform you have to option to make online gaming exclusive for the Game Pass users.
Game Pass is a new window in the Dematerialized store/Console Creation menu.
You can research Multi-Platform for Game Pass, which allows you to put your service in more than 1 platform.

**Comment by xsellier** [comment]
Thank yo ufor the suggestion, however this one has already been made.
To keep a track of your suggestion I link it to this one: #531

Closing
