### ISSUE TITLE
Suggestion: Can make Bundles

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#823]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Can make Bundles for games, example: Metal Gear Solid: The Legacy Edition.

**Describe alternatives you've considered**
None.

**Additional context**
You can select Remasters and Remakes for the Bundle. Example: Metal Gear Solid HD Collection.

You can put from 2 to 10 games on a Bundle.

You can choose the price between 1 dollar to 1000 dollars.

Bundles are unlocked in the year 1980.

**Comment by xsellier** [comment]
Duplciate of: #421
Closing

**Comment by GianluPlay** [comment]
> Duplciate of: #421
> Closing

?

I didnt said console + game, i meant **2 or more games in one disc/cartdridge (2 or more games in 1)

**Comment by xsellier** [comment]
Overall idea is to make bundles, including consoles or not. That's why I put those together.
