### ISSUE TITLE
Suggestion: Engine Features can free CPU/GPU Power

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#824]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Engine Features can free CPU/GPU Power, and yes, this is possible.

**Describe alternatives you've considered**
None

**Additional context**
Engine Features can free some CPU/GPU Power when used, example: Occlusiong Culling

**Comment by xsellier** [comment]
Sorry, it is not possible. It will make the game crash.
