### ISSUE TITLE
Suggestion: Mobile Platforms

### ISSUE THREAD

**Issue by ghost** [binogure-studio/city-game-studio-i18n#829]
**Is your feature request related to a problem? Please describe.**
Being able to make a port to mobile platforms is a great boost to some of the franchises that we have done on platforms such as Skylight 10 for example and being able to transfer them to a mobile store.

**Describe the solution you'd like**
Add Mobile Platforms

**Describe alternatives you've considered**
A small update that contains mobile platforms that are cheaper to develop games or port them

**Additional context**
More platforms, more fun,
more money,
cheaper to start

**Comment by xsellier** [comment]
Heym,

Thank you for the suggestion, I'll add it to the other already existing regarding mobile platforms:
https://github.com/binogure-studio/city-game-studio-i18n/issues/524

Closing this one as duplicate.
