### ISSUE TITLE
Better Readability for the financial result page

### ISSUE THREAD

**Issue by RedditCaptain** [binogure-studio/city-game-studio-i18n#83]
Really liking the new financial page. It's something I really appreciate in games like this and like to look at a lot. I'm thinking the readability could be improved. 

For example: 

![Example financial page](https://i.imgur.com/ZkQicwA.jpg)

**Comment by xsellier** [comment]
Made that
![image](https://user-images.githubusercontent.com/6616005/53605329-2b05cb80-3b85-11e9-82b0-5fb7bae43015.png)
