### ISSUE TITLE
Invalid - the effects of piracy

### ISSUE THREAD

**Issue by mcdbergh** [binogure-studio/city-game-studio-i18n#830]
Maybe it is a option to have the effects on piracy in the game market. 

To see the sales renevue show the leakage of the piracy.

And that when a game is cracked you can exclude the cracked games of the network features or in-game store.

Maybe also that a game studio will be hacked and data will be leaked to the internet.

**Comment by xsellier** [comment]
Hey,

Please use the issue template:
```
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```
