### ISSUE TITLE
Invalid: Invisible elements in a dark theme.

### ISSUE THREAD

**Issue by olsza** [binogure-studio/city-game-studio-i18n#840]
**Describe the bug**
With the dark theme on, several things are not visible.

**Expected behavior**
Texts should be a different color than the background or more contrasting

**Logs**
Attach log files to this ticket:
[citygamestudio-9.log](https://github.com/binogure-studio/city-game-studio-i18n/files/9965840/citygamestudio-9.log)

**Screenshots**

Current version - Light theme
![Zrzut ekranu z 2022-11-08 22-16-16](https://user-images.githubusercontent.com/12556170/200692838-1b6f42cd-ef15-4860-a89f-7bf457d80a45.png)

Current version - Dark theme
![Zrzut ekranu z 2022-11-08 22-15-35](https://user-images.githubusercontent.com/12556170/200692844-acc9a101-a9b3-4b78-83cc-8690045b9a70.png)

Current version - Light theme
![Zrzut ekranu z 2022-11-08 21-55-20](https://user-images.githubusercontent.com/12556170/200692848-208445e2-19d6-42e5-b1c8-6866875b42bb.png)

Current version - Dark theme
![Zrzut ekranu z 2022-11-08 21-54-46](https://user-images.githubusercontent.com/12556170/200692851-e9087303-69d4-4a46-8a5e-b8249c664d17.png)

Previous version - Dark theme - as it was
![Zrzut ekranu z 2022-10-31 14-44-42](https://user-images.githubusercontent.com/12556170/200692854-cf4aa8c2-6148-4240-a09e-1ece4718eeeb.png)

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu
 - Version 22.04.1 LTS

**Additional context**
(Yellow color in the screenshot) In the previous version it was visible
(blue color in the screenshot) Neither was visible in previous versions
(purple color in the screenshot) suggestion for change to make it more visible

**Comment by xsellier** [comment]
Thanks for that!

**Comment by xsellier** [comment]
I'm publishing a patch to fix those elements atm.
Everything should be back to normal within 10 to 15 minutes!

**Comment by xsellier** [comment]
Done, everything should be back to normal.

Regadings some bugs, be sure to restart the game after switching between dark/light themes.

**Comment by olsza** [comment]
> Regadings some bugs, be sure to restart the game after switching between dark/light themes.

I know, I know, it's even written ;)
tip: to quickly reload the game dark<->light theme, instead of starting the game from the beginning, just save and the game will refresh itself ;)

**Comment by olsza** [comment]
Wow, quick reaction and quick change.... confirm is good :)
Thx @xsellier
