### ISSUE TITLE
Suggestion: Demolish Studio

### ISSUE THREAD

**Issue by cr4t3** [binogure-studio/city-game-studio-i18n#845]
**Describe the solution you'd like**
I would like that if you buy an studio, you can demolish it. This could be for the next things:
* Changing the type of build (Could be from Studio into University or Exhibition center)
* Making bigger the Studio/University/Exhibition Center.

**Describe alternatives you've considered**
Adding a "upgrade" option that make the change insted of the demolishion

**Comment by xsellier** [comment]
Thanks, this has been implemented and is now available.
