### ISSUE TITLE
Bug: Cannot release games for my own console

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#855]
**Describe the bug**
I made a console, made a game for the console, actually two games, but after i released the console i cant release them

**To Reproduce**
1. Make a console 
2. Cancel the console 
3. Make another console 
4. Cancel that console 
5. Make another console 
6. Make a game for that console 
7. Finish the development of the game 
8. Release the console 
9. Congrats, you found the bug, or maybe it's just me 

**Expected behavior**
A clear and concise description of what yo

**Logs**
Can't do that 

**Screenshots**
Can't do that 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: KB5025239

**Additional context**
X

**Comment by xsellier** [comment]
Hey,

Thank you for that wonderful report.
I'm gonna work on it ASAP.

**Comment by xsellier** [comment]
Hey,

Sorry for the delay, I've been trying to reproduce the bug:
I made 3 consoles, canceled 2 and released one, meanwhile I made 2 games and released them successfully.

Do you mind, sharing at least one screenshot or your savegame please. Or at least more informations:
- Was the release button greyed out?
- Was it visible?
- Was the game paused?
- Was it clickable but nothing happen
