### ISSUE TITLE
Random change competitor has balanced employee

### ISSUE THREAD

**Issue by RedditCaptain** [binogure-studio/city-game-studio-i18n#86]
Random change competitor has balanced employee for a much higher salary than the other employees. Could also cost you a sum of money upfront to hire them, because someone with those kind of skills is obviously wanted by most companies :)

**Comment by xsellier** [comment]
Poaching competitor's employee is risky. So the price is, whenever it fails, you have to pay the price. But i it succeed, it is a reward.

I think I can improve that, by removing the randomness, and setting a panel where you can setup an offer. What do you think?

**Comment by RedditCaptain** [comment]
Sounds good to me!

**Comment by xsellier** [comment]
With almost 6 month delay, Im working on it atm

**Comment by xsellier** [comment]
And it's been implemented with v0.25.0. You have to pay a specific amount of cash to poach an employee. And it can be quite expensive!
