### ISSUE TITLE
Suggestion: Upping the character limit for Microtransaction names

### ISSUE THREAD

**Issue by ZephyyKylin** [binogure-studio/city-game-studio-i18n#862]
**Is your feature request related to a problem? Please describe.**
I use free micro transactions to keep track of roleplaying named updates. Such as "The Ocean Update" or "Shadows over Elden", or whatever. The current limit frustrates me, because a lot of the time, I have to abbreviate the update name

**Describe the solution you'd like**
a longer character limit for microtransactions. 

**Describe alternatives you've considered**
The ability to like... Have named updates in the update section? That would be rad and wouldn't even require upping the micro character limit. But it would be a lot more work.

**Additional context**

**Comment by xsellier** [comment]
Thank you, I'm adding it to the next update.

**Comment by xsellier** [comment]
In fact, I just made a very tiny tiny update to make it to 64 characters.
I hope you'll like it.

Cheers!

**Comment by ZephyyKylin** [comment]
Oh sick that's awesome! I would've replied sooner but I didn't see the the first two emails for some reason. 
Thanks so much! You're always on top of these! You rock! 

Sent from Yahoo Mail on Android 
 
  On Wed, Jul 26, 2023 at 9:17 AM, Xavier ***@***.***> wrote:   


Closed #862 as completed.
