### ISSUE TITLE
Bug: Russian achievement translations don't get updated in Steam

### ISSUE THREAD

**Issue by SyberiaK** [binogure-studio/city-game-studio-i18n#863]
**Describe the bug**
Russian achievements translations don't get updated in Steam and stay the same as before f8ab091b74de19e929305a3efef112ccbad22da8.

**To Reproduce**
1. Set Steam language to Russian
2. Go to 'Library'
2. Click on 'City Game Studio'
3. Go to 'Achievements' section
4. Some of the achievements uses outdated translations, for example "Свои колёса" ("Create a game engine") instead of "Свой велосипед"

**Expected behavior**
The translations got updated.

:)

**Comment by xsellier** [comment]
Hey,

Thank you for the report. Forgot to update the achievement in Steam. I just udpated it, so maybe you need to restart steam to see the changes.

Cheers.

**Comment by SyberiaK** [comment]
Turns out that one of the achievement titles (NEW_ACHIEVMENT_12_20_NAME) has been cut off due to quotes.
![image](https://github.com/binogure-studio/city-game-studio-i18n/assets/97897772/f12fef09-06b6-4adb-9081-9f2bd1f0a294)
Does YAML support escaping quotes? If it does - can you fix this?

**Comment by SyberiaK** [comment]
Fixed in #864.
