### ISSUE TITLE
Show how many gauges have been unlocked

### ISSUE THREAD

**Issue by RedditCaptain** [binogure-studio/city-game-studio-i18n#87]
Add the amount of gauges that have been unlocked for each genre.

![gauges](https://i.imgur.com/1dWUNr9.jpg)

Not sure if that would be the best way, because it might confuse new players. Maybe it would show when you hover over the genre.

**Comment by xsellier** [comment]
Tells you that you have unlocked at least 5 gauges:
![image](https://user-images.githubusercontent.com/6616005/54565036-a21fca00-49a3-11e9-92fe-60b29bc8c3f2.png)

**Comment by xsellier** [comment]
Ok done in v0.17.1

![image](https://user-images.githubusercontent.com/6616005/55984144-cc933900-5c6a-11e9-9613-50c18aa27907.png)
