### ISSUE TITLE
Suggestion: Adding a new theme for a video game

### ISSUE THREAD

**Issue by XHFlamer** [binogure-studio/city-game-studio-i18n#872]
The problem is that there are very few themes in the game for creating games. I understand that there are mods in the workshop, but I want to get only the themes and not the functions of the engine, console, company, etc. 

**Binogure please add more themes for games**

**Comment by xsellier** [comment]
Please use this ticket to suggest new themes, then I might add them to the game:
https://github.com/binogure-studio/city-game-studio-i18n/issues/388
