### ISSUE TITLE
Developing games for consoles

### ISSUE THREAD

**Issue by TakiSeba** [binogure-studio/city-game-studio-i18n#878]
It is now possible to develop games for consoles after the console has been in production for a long time. Devkits, on the other hand, can be distributed to other companies immediately. I have noticed that as the owner of such a console, we can't create games for currently manufactured console right away, making it damaging to the process of increasing the library of games and inconsistent with the fact that we can sell to competitors the ability to create games at an early stage of its production.
![CityGameStudio](https://github.com/binogure-studio/city-game-studio-i18n/assets/161274227/8c5a43e0-a826-410b-8282-ca107b1f6508)

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion, this is planned for the v1.18.

**Comment by xsellier** [comment]
And it's been implemented already!
