### ISSUE TITLE
Bug [minor]: All engine features in "new technology available" mails are listed as design features

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#885]
Regardless of the actual type of newly available engine feature, in the English localization at least, the "new technology available" mails will always list the new feature as a "design" feature:

![image](https://github.com/binogure-studio/city-game-studio-i18n/assets/25114435/99b2eed7-50c0-4352-a12e-e72057789254)
![image](https://github.com/binogure-studio/city-game-studio-i18n/assets/25114435/016f440f-c9f2-45a8-a748-f94499dc175b)
![image](https://github.com/binogure-studio/city-game-studio-i18n/assets/25114435/f969602e-377a-43ae-97ba-0114d3fe6996)
![image](https://github.com/binogure-studio/city-game-studio-i18n/assets/25114435/bbe44ce7-ec90-48a4-8d92-166f6e78edb3)

**Comment by xsellier** [comment]
Thanks, fixed in the v1.19.0-rc0
