### ISSUE TITLE
Matching (genre/platform/theme) correction

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#89]
I think the themes fantasy, history and archeology should be a perfect match for TBStrat.
Atm they are a poor match.

Zombie and survival poor match should be perfect match.

City builder isn't a perfect match for skylight 10 right now (dont know the other platforms for now) but it should be a perfect match.

**Comment by xsellier** [comment]
Fixed, thank you @Tesba
