### ISSUE TITLE
Suggestion: Add buttons for Discounts

### ISSUE THREAD

**Issue by weaktt** [binogure-studio/city-game-studio-i18n#890]
Add few buttons when you are trying to make game discounts:
max = 95%
half  = 50%
mb some others like 10-25%
and for time add "Do Forever" button

**Comment by VeteranXT** [comment]
Would like to add: Add events and Seasoned Discounts. Like every Decembar at X price.

**Comment by xsellier** [comment]
Added a max and min tot he game. It should be part of the next update (or the unstable branch later today).

**Comment by xsellier** [comment]
This one is a duplicate of this ticket, I'm closing it in favor of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/896
