### ISSUE TITLE
Bug: Hidden Charges on Game Development

### ISSUE THREAD

**Issue by VeteranXT** [binogure-studio/city-game-studio-i18n#894]
**Describe the bug**
Whatever i start developing game i get charged for "something".
I pay one time licence and that is fine, but cancel game and start new game dev charged me 1.5k - 150K depending on year/console.
For example: Skylight 10 License cost 500$. That i pay, but whatever i start development i get charged 150K,

**To Reproduce**
Start new game, 
Select Console Pay for Licence
Start Development.
Cancel Game.
Start Development For same console
Look finances

**Expected behavior**

**Logs**
Attach log files to this ticket:
[citygamestudio-0.log](https://github.com/user-attachments/files/17179779/citygamestudio-0.log)

**Screenshots**
License 500$ (fine) start developing
![image](https://github.com/user-attachments/assets/794c3e0d-8047-4c54-a9be-e25ee41a853b)
Get Charged off start 165K For what?
![image](https://github.com/user-attachments/assets/4f8fc6fc-482e-4d60-b0bb-1b8ee672bfec)
Financial Result didn't say what was charged for? Development cost was charged for license and  that is fine.
![image](https://github.com/user-attachments/assets/43aeb4f1-9bb5-4ee2-8db9-1f8483f9fed9)

**Additional context**
This applies to ALL consoles not just end game. Creating new game and starting charges you 1.5k per game creation.

**Comment by xsellier** [comment]
Hey, it's hidden but it's written when you hover the Monhtly Costs. I'm gonna shar ea better screenshot, improve the tooltip delay and I think it's gonna get fixed later today.
![image](https://github.com/user-attachments/assets/59f4ecf6-5a8f-4b68-a0bb-d4ebad13860f)
