### ISSUE TITLE
Stray cat feature

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#90]
LOW PRIORITY 

since you want to animate the cat in the future, give it a live.
so if the event fires let the cat live 9-15 years. right now the cat gives a small bonus to dev., so if it dies it could make the devs sad, so the productivity goes down by 5 % for a 3 months.
set a trigger that checks if the studio has a cat:
if yes => event will not trigger
if not => event triggers with a chance of 5% each month.

**Comment by xsellier** [comment]
Cat gives you a bonus already, it is a small one. I do need to draw/animate it anyway.

**Comment by xsellier** [comment]
Cat gives you a bonus already, it stays for a month or 2 at max.
Cat animation has been implemented ;)

If you agree, I'm going to close this issue
