### ISSUE TITLE
Suggestion: Marketing all button and automation

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#92]
add a button to start & cancel all the marketing at once.

for automation take look at my sketch ;) automation fires on game release.
![marketing](https://user-images.githubusercontent.com/48098478/53681225-ba76c000-3ce6-11e9-88a1-b96c82fc2b9c.jpg)

**Comment by xsellier** [comment]
Hey,

A global marketing button has been implemented, however the automatic marketing button does not exists yet.

**Comment by xsellier** [comment]
Global marketing has been implemented.
A marketing campaign lasts for 2 years, but I'm changing it to lasts for 4 years with v0.28.0
Automatic conventions have been implemented too
