### ISSUE TITLE
Suggestion: Add fan letters / feedback from fans

### ISSUE THREAD

**Issue by Tesba** [binogure-studio/city-game-studio-i18n#96]
Add emails from fans for flavor, should not be a rapid fire feature that fills the box
max. 2 letters a game overall (its time on the market), or for especially good (above 90%)
or bad (below 30% )games 3-5 letters overall

**negative (0-49% (or where you set the threshold for a bad game that decreases fanbase); they will tell their friends):**
sorry to say but your game is utterly trash, i'm gonna refund that crap.
(-1k $ & sale decrease next month)

who the hell you think you are, a super developer, to release such a mess.
you will never become as good as Binogure.
(-1k Fans & sale decrease next month) 

hell no, what is that? is your name "Tha Butchering Floors" (pun to jim sterling's mess with The Slaughtering Grounds, perhaps people will get it ;) )
(for really bad and messed up games (rating below 25%) => - 100k dollar and fans & sale decrease next month)  (if a game so crap that it gets below 15% take 90% of the players cash and fanbase)

**neutral (games with overall rating 50-75 %):**
all neutral letters will give you a hint to one slider setting, could grant 5% slider knowledge
e.g.:
i really like your game so far, it's not bad but not great either
i think you should have put more effort in the UI.
and so on....

**positive: (they will tell their friends, games with overall rating 75% and above):**
wow this is phenomenal, thank you for this gem, i will tell all my friends at school :)
(+1k fans & sale increase next month)

i really love your game and i bought copies for my whole family and all my friends.
they will tell about it everywhere.
(+1k $ & sale increase next month)

that's the best game i ever played, for real, it's unbelievable.
(+1k $ & sale increase next month)

**Letters from youtubers:**
negative: -5k fans + sale decrease next month
 neutral +-0 fans/sale
positive +5k fans +sale increase next month

**Letters from modders:**
will only fire at really good games, should work like a marketing campaign, so the game lasts longer in the sales (boosts hype and sales for a few months)

**Comment by xsellier** [comment]
This has been implemented in v1.11.0
